import type { Pattern } from '../types';

export const ANDEAN_SOUTH_AMERICA_PATTERNS: Pattern[] = [
  {
    id: 'huayno',
    name: 'Huayno',
    origin: 'Peru · Bolivia · Ecuador · Andean highlands',
    tradition: 'Pan-Andean couple dance',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 440, min: 380, max: 520 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 1, 1, 0, 0, 1, 1],
      HH: [2, 0, 1, 1, 2, 0, 1, 1],
    },
    defaultKit: '727',
    country: 'PE',
    region: 'andean-south-america',
    tags: ['andean', 'quechua', 'huayno', 'bombo', 'quena'],
    instruments: ['bombo andino', 'charango', 'quena'],
    swingable: false,
    story: 'The Andes\' most widespread dance — a pre-Hispanic heartbeat that still fills every highland festival from Cuzco to La Paz. The bounce is quarter-eighth-eighth: long-short-short.',
    relatedIds: ['carnavalito', 'cueca'],
  },
  {
    id: 'chacarera',
    name: 'Chacarera',
    origin: 'Argentina · Santiago del Estero',
    tradition: 'Northwestern Argentine folk',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 135, min: 115, max: 155 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
      SN: [0, 0, 1, 0, 0, 2, 0, 0, 1, 0, 2, 2],
      HH: [2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1],
    },
    defaultKit: '727',
    country: 'AR',
    region: 'andean-south-america',
    tags: ['argentina', 'bombo-legüero', 'zapateo', '6-8'],
    instruments: ['bombo legüero', 'guitar', 'violin'],
    swingable: false,
    story: 'From the dry province of Santiago del Estero. The bombo legüero — a huge poncho-wrapped bass drum — alternates head and rim to build the chacarera\'s signature galloping feel.',
    relatedIds: ['zamba'],
  },
  {
    id: 'zamba',
    name: 'Zamba',
    origin: 'Argentina · Northwest',
    tradition: 'Slow romantic folk dance',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 80, min: 70, max: 95 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2],
      HH: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
    },
    defaultKit: '727',
    country: 'AR',
    region: 'andean-south-america',
    tags: ['argentina', 'bombo-legüero', 'pañuelo', 'slow'],
    instruments: ['bombo legüero', 'guitar'],
    swingable: false,
    story: 'Not to be confused with Brazilian samba — zamba is a slow, contemplative courtship dance where partners circle each other behind waving handkerchiefs. Atahualpa Yupanqui\'s heartland.',
    relatedIds: ['chacarera', 'cueca'],
  },
  {
    id: 'cueca',
    name: 'Cueca',
    origin: 'Chile · Bolivia · Argentina',
    tradition: 'National courtship dance',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 115, min: 100, max: 130 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 2],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'CL',
    region: 'andean-south-america',
    tags: ['cueca', 'sesquialtera', 'chile', 'pañuelo'],
    instruments: ['guitar', 'accordion', 'handclaps'],
    swingable: false,
    story: 'Chile\'s national dance (declared 1979). A rooster courts a hen — handkerchiefs wave overhead, feet stamp the sesquiáltera, where 6/8 melody and 3/4 claps occupy the same bar.',
    relatedIds: ['zamba', 'chacarera', 'fandango-huelva', 'verdiales'],
  },
  {
    id: 'carnavalito',
    name: 'Carnavalito',
    origin: 'Argentina · Bolivia · Altiplano',
    tradition: 'Andean carnival dance',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 520, min: 460, max: 600 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 1, 0, 0, 2, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'AR',
    region: 'andean-south-america',
    tags: ['carnival', 'quebrada-de-humahuaca', 'charango', 'siku'],
    instruments: ['bombo andino', 'charango', 'siku'],
    swingable: false,
    story: 'The festive cousin of huayno — faster, brighter, the sound of Andean carnival snaking through the Quebrada de Humahuaca behind panpipes and charango.',
    relatedIds: ['huayno'],
  },
];
