import type { Pattern } from '../types';

export const ARABIC_SWANA_PATTERNS: Pattern[] = [
  {
    id: 'maqsoum',
    name: 'Maqsoum',
    origin: 'Egypt',
    tradition: 'Pan-Arab pop',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 120, min: 100, max: 140 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 1, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'EG',
    region: 'arabic-swana',
    tags: ['pop', 'foundation', 'darbuka', 'bellydance'],
    instruments: ['darbuka', 'riqq', 'tabla baladi'],
    swingable: false,
    story: 'Dum-tek-tek, dum-tek. If you\'ve heard any Arabic pop song, you\'ve heard this — the most ubiquitous rhythm in the SWANA world.',
  },
  {
    id: 'baladi',
    name: 'Baladi',
    origin: 'Egypt',
    tradition: 'Folk / belly dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 100, min: 80, max: 120 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'EG',
    region: 'arabic-swana',
    tags: ['folk', 'bellydance', 'egyptian'],
    instruments: ['tabla baladi', 'mizmar', 'rebaba'],
    swingable: false,
    story: '"Baladi" means "of the country" — heavier and earthier than Maqsoum thanks to the double doum at the top of the bar.',
    relatedIds: ['maqsoum'],
  },
  {
    id: 'saidi',
    name: 'Saidi',
    origin: 'Egypt · Upper Egypt',
    tradition: 'Stick-dance (tahtib)',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 115, min: 100, max: 140 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'EG',
    region: 'arabic-swana',
    tags: ['folk', 'tahtib', 'martial', 'saidi'],
    instruments: ['tabla baladi', 'mizmar', 'rababa'],
    swingable: false,
    story: 'The rhythm of the Sa\'id region — Upper Egypt\'s stick-fighting dance. Heavy and martial, with a double-doum stomp that shakes the floor.',
  },
  {
    id: 'masmoudi-kebir',
    name: 'Masmoudi Kebir',
    origin: 'Egypt · Pan-Arab',
    tradition: 'Classical / belly dance entrance',
    genre: 'classical',
    timeSig: '8/4',
    grouping: [4, 4, 4, 4, 4, 4, 4, 4],
    stepUnit: 16,
    steps: 32,
    bpm: { default: 80, min: 60, max: 100 },
    difficulty: 'intermediate',
    tracks: {
      KK: [
        2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      ],
      SN: [
        0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0,
        0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0,
      ],
      HH: [
        2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1,
        2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1,
      ],
    },
    defaultKit: 'frameDrum',
    region: 'arabic-swana',
    tags: ['classical', 'bellydance', 'grand', 'entrance'],
    instruments: ['darbuka', 'riqq', 'oud'],
    swingable: false,
    story: '"Grand Masmoudi" — a stately 8-beat cycle used for dignified entrances and the openings of belly-dance sets. The spaciousness leaves room for dramatic gestures.',
  },
  {
    id: 'wahda',
    name: 'Wahda',
    origin: 'Pan-Arab',
    tradition: 'Classical taxim',
    genre: 'classical',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 65, min: 40, max: 90 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
    },
    defaultKit: 'frameDrum',
    region: 'arabic-swana',
    tags: ['classical', 'taxim', 'slow', 'unity'],
    instruments: ['riqq', 'oud', 'ney'],
    swingable: false,
    story: '"Wahda" means "one" — the rhythm of unity. Slow and spacious, it frames the soloist\'s taxim improvisation in classical wasla.',
  },
  {
    id: 'ayoub',
    name: 'Ayoub',
    origin: 'Egypt · Levant',
    tradition: 'Sufi / zar',
    genre: 'devotional',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 120, min: 80, max: 160 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    region: 'arabic-swana',
    tags: ['sufi', 'zar', 'trance', 'ancient'],
    instruments: ['bendir', 'daf', 'tar'],
    swingable: false,
    story: 'One of the oldest rhythms in SWANA — hypnotic simplicity that drives Sufi dhikr and zar healing ceremonies into trance as the tempo climbs.',
  },
  {
    id: 'samai-thaqil',
    name: 'Samai Thaqil',
    origin: 'Pan-Arab · Ottoman',
    tradition: 'Classical wasla',
    genre: 'classical',
    timeSig: '10/8',
    grouping: [3, 2, 2, 3],
    stepUnit: 8,
    steps: 10,
    bpm: { default: 75, min: 60, max: 100 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 2, 0, 2, 0, 0],
      SN: [0, 0, 0, 2, 0, 0, 2, 0, 0, 2],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    region: 'arabic-swana',
    tags: ['classical', 'ottoman', 'samai', 'wasla'],
    instruments: ['riqq', 'qanun', 'ud'],
    swingable: false,
    story: 'The grand classical rhythm of the samai compositional form — stately, slow, and central to the Arabic wasla suite.',
  },
  {
    id: 'chiftetelli',
    name: 'Chiftetelli',
    origin: 'Turkey · Pan-Ottoman',
    tradition: 'Belly dance / Romani',
    genre: 'popular',
    timeSig: '8/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 100, min: 80, max: 120 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'TR',
    region: 'arabic-swana',
    tags: ['bellydance', 'romani', 'ottoman', 'oriental'],
    instruments: ['darbuka', 'ud', 'clarinet'],
    swingable: false,
    story: 'The iconic belly-dance rhythm — "double-stringed," deep in Romani and oriental dance traditions from Istanbul to Athens.',
  },
];
