import type { Pattern } from '../types';

export const BALKANS_PATTERNS: Pattern[] = [
  {
    id: 'ruchenitsa',
    name: 'Rŭchenitsa',
    origin: 'Bulgaria',
    tradition: 'Folk dance',
    genre: 'folk-dance',
    timeSig: '7/8',
    grouping: [2, 2, 3],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 320, min: 240, max: 420 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0],
      SN: [0, 0, 0, 0, 0, 1, 1],
      HH: [2, 1, 2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'balkans',
    country: 'BG',
    tags: ['dance', 'line-dance', 'bulgarian'],
    instruments: ['gaida', 'kaval', 'tapan'],
    swingable: false,
    story: "Bulgaria's most danced rhythm — \"quick-quick-sloooow\" is how kids learn it.",
    relatedIds: ['horon'],
  },
  {
    id: 'kopanitsa',
    name: 'Kopanitsa',
    origin: 'Bulgaria · Shope',
    tradition: 'Folk dance',
    genre: 'folk-dance',
    timeSig: '11/8',
    grouping: [2, 2, 3, 2, 2],
    stepUnit: 8,
    steps: 11,
    bpm: { default: 400, min: 320, max: 520 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0],
      SN: [0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: 'frameDrum',
    region: 'balkans',
    country: 'BG',
    tags: ['dance', 'advanced', 'shope'],
    instruments: ['gaida', 'kaval', 'tapan'],
    swingable: false,
    story: '11/8 stomping through a tavern. The long beat is in the middle here.',
  },
  {
    id: 'daichovo',
    name: 'Daichovo',
    origin: 'Bulgaria',
    tradition: 'Folk dance',
    genre: 'folk-dance',
    timeSig: '9/8',
    grouping: [2, 2, 2, 3],
    stepUnit: 8,
    steps: 9,
    bpm: { default: 340, min: 280, max: 440 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 0, 1, 0, 1, 1],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: 'frameDrum',
    region: 'balkans',
    country: 'BG',
    tags: ['dance', 'bulgarian'],
    instruments: ['gaida', 'kaval'],
    swingable: false,
    story: 'Same 2+2+2+3 skeleton as Karşılama but faster, bouncier, pan-flute territory.',
    relatedIds: ['karsilama'],
  },
  {
    id: 'cocek',
    name: 'Čoček',
    origin: 'Balkans · Romani',
    tradition: 'Romani dance',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 240, min: 180, max: 340 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 1, 0],
      SN: [0, 0, 2, 0, 2, 0, 1, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'RS',
    region: 'balkans',
    tags: ['romani', 'dance', 'ottoman', 'syncopated'],
    instruments: ['zurna', 'tupan', 'clarinet'],
    swingable: false,
    story: 'The signature Romani dance of the Balkans — descended from Ottoman court dance, played on zurna and tupan at weddings.',
  },
  {
    id: 'kalamatianos',
    name: 'Kalamatianós',
    origin: 'Greece · Peloponnese',
    tradition: 'Circle dance',
    genre: 'folk-dance',
    timeSig: '7/8',
    grouping: [3, 2, 2],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 270, min: 220, max: 340 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 2, 0],
      SN: [0, 0, 1, 0, 1, 0, 1],
      HH: [2, 1, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'GR',
    region: 'balkans',
    tags: ['dance', 'circle', 'greek'],
    instruments: ['bouzouki', 'klarino', 'toubeleki'],
    swingable: false,
    story: 'The Greek national circle dance. Long-short-short, everyone holding hands.',
  },
  {
    id: 'gankino',
    name: 'Gankino',
    origin: 'Bulgaria · Thrace',
    tradition: 'Folk dance',
    genre: 'folk-dance',
    timeSig: '11/8',
    grouping: [2, 2, 3, 2, 2],
    stepUnit: 8,
    steps: 11,
    bpm: { default: 360, min: 280, max: 440 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0],
      SN: [0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1],
      HH: [2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'BG',
    region: 'balkans',
    tags: ['dance', 'bulgarian', '11-8'],
    instruments: ['gaida', 'tapan', 'gadulka'],
    swingable: false,
    story: 'Kopanitsa by another name — the Thracian take on 11/8. Slightly more relaxed, but the same quick-quick-slow-quick-quick drive.',
    relatedIds: ['kopanitsa'],
  },
  {
    id: 'pravo-horo',
    name: 'Pravo Horo',
    origin: 'Bulgaria',
    tradition: 'Folk line dance',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 220, min: 180, max: 280 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'BG',
    region: 'balkans',
    tags: ['dance', 'bulgarian', 'line-dance', 'beginner'],
    instruments: ['gaida', 'gadulka', 'tapan'],
    swingable: false,
    story: 'The "straight" dance — the 2/4 baseline of Bulgarian horo. Simple meter, elaborate ornaments on top from the gaida.',
  },
  {
    id: 'lesnoto',
    name: 'Lesnoto',
    origin: 'North Macedonia',
    tradition: 'Folk circle dance',
    genre: 'folk-dance',
    timeSig: '7/8',
    grouping: [3, 2, 2],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 200, min: 160, max: 260 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 2, 0],
      SN: [0, 1, 1, 0, 1, 0, 1],
      HH: [2, 1, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'MK',
    region: 'balkans',
    tags: ['dance', 'macedonian', 'circle'],
    instruments: ['gaida', 'tupan', 'kaval'],
    swingable: false,
    story: '"The easy one" — in name only. Long-short-short Macedonian oro, stately and communal, every wedding opens with it.',
    relatedIds: ['kalamatianos'],
  },
  {
    id: 'syrtos',
    name: 'Syrtós',
    origin: 'Greece',
    tradition: 'Circle dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 130, min: 110, max: 160 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'GR',
    region: 'balkans',
    tags: ['dance', 'greek', 'circle', 'ancient'],
    instruments: ['lyra', 'laouto', 'daouli'],
    swingable: false,
    story: 'The "dragging" dance — the oldest and most widespread Greek folk form. A gliding 4/4, smooth where kalamatianos is bouncy.',
  },
  {
    id: 'tsamiko',
    name: 'Tsámiko',
    origin: 'Greece',
    tradition: 'Warrior dance',
    genre: 'folk-dance',
    timeSig: '3/4',
    grouping: [4, 4, 4],
    stepUnit: 16,
    steps: 12,
    bpm: { default: 100, min: 80, max: 130 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 1, 0],
      HH: [2, 0, 1, 0, 2, 0, 1, 0, 2, 0, 1, 0],
    },
    defaultKit: 'frameDrum',
    country: 'GR',
    region: 'balkans',
    tags: ['dance', 'greek', 'warrior', '3-4'],
    instruments: ['klarino', 'laouto', 'daouli'],
    swingable: false,
    story: 'The proud warrior dance of the Greek War of Independence — danced by men with high leaps. Stately 3/4 with a martial weight.',
  },
  {
    id: 'hasapiko',
    name: 'Hasápiko',
    origin: 'Greece · Constantinople',
    tradition: 'Butchers\' guild dance',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 140, min: 100, max: 200 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'GR',
    region: 'balkans',
    tags: ['dance', 'greek', 'rebetiko', 'ottoman'],
    instruments: ['bouzouki', 'baglama', 'toubeleki'],
    swingable: false,
    story: 'The butchers\' dance of Constantinople — from kasap (Turkish for butcher). The fast version became the Zorba sirtaki the world knows.',
  },
  {
    id: 'eleno-mome',
    name: 'Eleno Mome',
    origin: 'Bulgaria',
    tradition: 'Wedding song',
    genre: 'folk-dance',
    timeSig: '7/8',
    grouping: [2, 2, 3],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 280, min: 220, max: 360 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 0, 1, 1],
      HH: [2, 1, 2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    country: 'BG',
    region: 'balkans',
    tags: ['dance', 'bulgarian', 'wedding', 'song'],
    instruments: ['gaida', 'voice', 'tapan'],
    swingable: false,
    story: '"Elena, girl" — one of the most beloved Bulgarian folk songs, recorded by Le Mystère des Voix Bulgares. Same 7/8 as ruchenitsa, line-dance feel.',
    relatedIds: ['ruchenitsa'],
  },
  {
    id: 'sadi-moma',
    name: 'Sadi Moma',
    origin: 'Bulgaria',
    tradition: 'Folk dance (extended asymmetric)',
    genre: 'folk-dance',
    timeSig: '22/16',
    grouping: [2, 2, 2, 3, 2, 2, 2, 3, 2, 2],
    stepUnit: 16,
    steps: 22,
    bpm: { default: 360, min: 280, max: 440 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0],
      SN: [0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1],
      HH: [2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'BG',
    region: 'balkans',
    tags: ['dance', 'bulgarian', 'asymmetric', 'advanced', '22-16'],
    instruments: ['gaida', 'kaval', 'tapan'],
    swingable: false,
    story: '22/16 danced by entire villages — ten beats of "quick-quick-quick-slow-quick-quick-quick-slow-quick-quick." The math terrifies; the feet know.',
  },
  {
    id: 'krivo-horo',
    name: 'Krivo Horo',
    origin: 'Bulgaria · Plovdiv',
    tradition: 'Folk line dance',
    genre: 'folk-dance',
    timeSig: '13/16',
    grouping: [2, 2, 3, 2, 2, 2],
    stepUnit: 16,
    steps: 13,
    bpm: { default: 380, min: 300, max: 460 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 0],
      SN: [0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1],
      HH: [2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'BG',
    region: 'balkans',
    tags: ['dance', 'bulgarian', 'asymmetric', '13-16', 'plovdiv'],
    instruments: ['gaida', 'tapan', 'gadulka'],
    swingable: false,
    story: 'The "crooked dance of Plovdiv" — 13/16 with the long beat early. Krivo literally means "bent" — Bulgarians hear asymmetry as a kink in the line.',
  },
  {
    id: 'pajdusko',
    name: 'Pajduško',
    origin: 'North Macedonia · Bulgaria',
    tradition: 'Folk line dance',
    genre: 'folk-dance',
    timeSig: '5/8',
    grouping: [2, 3],
    stepUnit: 8,
    steps: 5,
    bpm: { default: 300, min: 240, max: 380 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 1],
      HH: [2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    country: 'MK',
    region: 'balkans',
    tags: ['dance', 'macedonian', 'bulgarian', '5-8', 'limp'],
    instruments: ['gaida', 'tapan', 'kaval'],
    swingable: false,
    story: 'The "limping" dance — 5/8 as short-long. One foot hops longer than the other; the limp is the point, not a flaw.',
  },
  {
    id: 'trite-puti',
    name: 'Trite Pŭti',
    origin: 'North Macedonia',
    tradition: 'Folk oro',
    genre: 'folk-dance',
    timeSig: '7/8',
    grouping: [2, 2, 3],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 260, min: 200, max: 320 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 0, 1, 1],
      HH: [2, 1, 2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    country: 'MK',
    region: 'balkans',
    tags: ['dance', 'macedonian', '7-8', 'circle'],
    instruments: ['gaida', 'kaval', 'tupan'],
    swingable: false,
    story: '"Three times" — a Macedonian 7/8 oro where each phrase crosses the circle in three gestures. Quick-quick-slow, the third beat holding the group together.',
    relatedIds: ['ruchenitsa', 'lesnoto'],
  },
  {
    id: 'oro-kolo',
    name: 'Oro (Standard)',
    origin: 'Former Yugoslavia',
    tradition: 'South Slavic circle dance',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 240, min: 200, max: 300 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 1, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'RS',
    region: 'balkans',
    tags: ['dance', 'serbian', 'macedonian', 'circle', 'kolo'],
    instruments: ['accordion', 'violin', 'tupan'],
    swingable: false,
    story: 'The pan-Balkan "wheel" — kolo in Serbian, oro in Macedonian. The 2/4 default every band can fall into without a word.',
  },
  {
    id: 'kukunesko',
    name: 'Kukuneško Horo',
    origin: 'Bulgaria',
    tradition: 'Folk line dance',
    genre: 'folk-dance',
    timeSig: '15/16',
    grouping: [2, 2, 2, 2, 3, 2, 2],
    stepUnit: 16,
    steps: 15,
    bpm: { default: 380, min: 300, max: 460 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0],
      SN: [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'BG',
    region: 'balkans',
    tags: ['dance', 'bulgarian', 'asymmetric', '15-16'],
    instruments: ['gaida', 'tapan', 'kaval'],
    swingable: false,
    story: '15/16 in seven beats — six shorts around a single long. At tempo the subdivisions blur and the ear hears only that one moment of expansion.',
    relatedIds: ['kopanitsa'],
  },
  {
    id: 'sandansko-horo',
    name: 'Sandansko Horo',
    origin: 'Bulgaria · Sandanski',
    tradition: 'Folk line dance',
    genre: 'folk-dance',
    timeSig: '22/16',
    grouping: [2, 2, 2, 3, 2, 2, 2, 3, 2, 2],
    stepUnit: 16,
    steps: 22,
    bpm: { default: 400, min: 320, max: 480 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0],
      SN: [0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1],
      HH: [2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'BG',
    region: 'balkans',
    tags: ['dance', 'bulgarian', 'asymmetric', '22-16', 'advanced'],
    instruments: ['gaida', 'tapan', 'gadulka'],
    swingable: false,
    story: 'Among the longest standard folk meters on Earth — a doubled 11-beat cycle from the town of Sandanski. Mathematicians love it; dancers live inside it.',
    relatedIds: ['sadi-moma', 'kopanitsa'],
  },
  {
    id: 'bucimis',
    name: 'Bučimiš',
    origin: 'Bulgaria · Shope',
    tradition: 'Folk line dance',
    genre: 'folk-dance',
    timeSig: '15/16',
    grouping: [2, 2, 2, 2, 3, 2, 2],
    stepUnit: 16,
    steps: 15,
    bpm: { default: 420, min: 340, max: 500 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0],
      SN: [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2],
    },
    defaultKit: 'frameDrum',
    country: 'BG',
    region: 'balkans',
    tags: ['dance', 'bulgarian', 'asymmetric', '15-16', 'shope', 'competition'],
    instruments: ['gaida', 'tapan', 'kaval'],
    swingable: false,
    story: 'Competition-tempo 15/16 from the Shope region around Sofia — the pattern every folk ensemble shows off with. Seven beats, one long, pure exhilaration.',
    relatedIds: ['kukunesko', 'kopanitsa'],
  },
];
