import type { Pattern } from '../types';

export const BALKANS_PATTERNS: Pattern[] = [
  {
    id: 'ruchenitsa',
    name: 'Rŭchenitsa',
    origin: 'Bulgaria',
    tradition: 'Folk dance',
    genre: 'folk-dance',
    timeSig: '7/8',
    grouping: [2, 2, 3],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 320, min: 240, max: 420 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0],
      SN: [0, 0, 0, 0, 0, 1, 1],
      HH: [2, 1, 2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'balkans',
    country: 'BG',
    tags: ['dance', 'line-dance', 'bulgarian'],
    instruments: ['gaida', 'kaval', 'tapan'],
    swingable: false,
    story: "Bulgaria's most danced rhythm — \"quick-quick-sloooow\" is how kids learn it.",
    relatedIds: ['horon'],
  },
  {
    id: 'kopanitsa',
    name: 'Kopanitsa',
    origin: 'Bulgaria · Shope',
    tradition: 'Folk dance',
    genre: 'folk-dance',
    timeSig: '11/8',
    grouping: [2, 2, 3, 2, 2],
    stepUnit: 8,
    steps: 11,
    bpm: { default: 400, min: 320, max: 520 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0],
      SN: [0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: 'frameDrum',
    region: 'balkans',
    country: 'BG',
    tags: ['dance', 'advanced', 'shope'],
    instruments: ['gaida', 'kaval', 'tapan'],
    swingable: false,
    story: '11/8 stomping through a tavern. The long beat is in the middle here.',
  },
  {
    id: 'daichovo',
    name: 'Daichovo',
    origin: 'Bulgaria',
    tradition: 'Folk dance',
    genre: 'folk-dance',
    timeSig: '9/8',
    grouping: [2, 2, 2, 3],
    stepUnit: 8,
    steps: 9,
    bpm: { default: 340, min: 280, max: 440 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 0, 1, 0, 1, 1],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: 'frameDrum',
    region: 'balkans',
    country: 'BG',
    tags: ['dance', 'bulgarian'],
    instruments: ['gaida', 'kaval'],
    swingable: false,
    story: 'Same 2+2+2+3 skeleton as Karşılama but faster, bouncier, pan-flute territory.',
    relatedIds: ['karsilama'],
  },
  {
    id: 'cocek',
    name: 'Čoček',
    origin: 'Balkans · Romani',
    tradition: 'Romani dance',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 240, min: 180, max: 340 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 1, 0],
      SN: [0, 0, 2, 0, 2, 0, 1, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'RS',
    region: 'balkans',
    tags: ['romani', 'dance', 'ottoman', 'syncopated'],
    instruments: ['zurna', 'tupan', 'clarinet'],
    swingable: false,
    story: 'The signature Romani dance of the Balkans — descended from Ottoman court dance, played on zurna and tupan at weddings.',
  },
  {
    id: 'kalamatianos',
    name: 'Kalamatianós',
    origin: 'Greece · Peloponnese',
    tradition: 'Circle dance',
    genre: 'folk-dance',
    timeSig: '7/8',
    grouping: [3, 2, 2],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 270, min: 220, max: 340 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 2, 0],
      SN: [0, 0, 1, 0, 1, 0, 1],
      HH: [2, 1, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'GR',
    region: 'balkans',
    tags: ['dance', 'circle', 'greek'],
    instruments: ['bouzouki', 'klarino', 'toubeleki'],
    swingable: false,
    story: 'The Greek national circle dance. Long-short-short, everyone holding hands.',
  },
];
