import type { Pattern } from '../types';

export const BRAZIL_PATTERNS: Pattern[] = [
  {
    id: 'bossa-nova',
    name: 'Bossa Nova',
    origin: 'Brazil · Rio de Janeiro',
    tradition: 'Cool jazz / samba',
    genre: 'jazz',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 128, min: 70, max: 160 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['jazz', 'cool', 'partido-alto', 'ipanema'],
    instruments: ['nylon guitar', 'brushes', 'surdo'],
    swingable: true,
    story: 'Jobim and João Gilberto slowed samba down, stripped it bare, and dressed it in cool-jazz harmony. The cross-stick traces the partido-alto skeleton.',
    relatedIds: ['samba-partido-alto'],
  },
  {
    id: 'samba-partido-alto',
    name: 'Samba Partido Alto',
    origin: 'Brazil · Rio de Janeiro',
    tradition: 'Samba subgenre',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 110, min: 90, max: 130 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 2, 0, 0, 2, 0],
      HH: [2, 0, 1, 0, 2, 0, 1, 0],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['samba', 'partido-alto', 'pagode', 'pandeiro'],
    instruments: ['pandeiro', 'tantã', 'cavaquinho'],
    swingable: true,
    story: 'Older, rootsier samba — circled around improvised verses and hand percussion. The partido-alto pattern became the "Brazilian clave" that crossed into bossa and jazz.',
  },
  {
    id: 'samba-reggae',
    name: 'Samba-Reggae',
    origin: 'Brazil · Salvador, Bahia',
    tradition: 'Olodum / bloco afro',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 105, min: 90, max: 120 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['bahia', 'olodum', 'bloco-afro', 'interlocking-surdos'],
    instruments: ['surdo', 'repique', 'caixa'],
    swingable: false,
    story: 'Created in 1986 by Neguinho do Samba for Olodum — samba\'s surdo foundation married to reggae\'s tempo, three drums interlocking into a wall of bass through the streets of Salvador.',
  },
  {
    id: 'baiao',
    name: 'Baião',
    origin: 'Brazil · Northeast',
    tradition: 'Forró',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 120, min: 100, max: 140 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 1, 0, 0, 0, 0, 1],
      HH: [2, 0, 2, 2, 2, 0, 2, 2],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['forró', 'zabumba', 'accordion', 'sertão'],
    instruments: ['zabumba', 'triangle', 'sanfona'],
    swingable: false,
    story: 'The foundational rhythm of forró, from the arid sertão of Pernambuco — zabumba bass-and-slap, triangle, accordion. Luiz Gonzaga brought it to the whole country.',
  },
  {
    id: 'maracatu',
    name: 'Maracatu',
    origin: 'Brazil · Pernambuco',
    tradition: 'Afro-Brazilian procession',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 95, min: 80, max: 110 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['afro-brazilian', 'procession', 'alfaia', 'candomble'],
    instruments: ['alfaia', 'gongue', 'caixa'],
    swingable: false,
    story: 'One of Brazil\'s oldest Afro-descended traditions — born from the coronation processions of enslaved African "kings and queens" in colonial Pernambuco.',
  },
  {
    id: 'samba-enredo',
    name: 'Samba-Enredo',
    origin: 'Brazil · Rio de Janeiro',
    tradition: 'Escola de samba carnival parade',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 135, min: 125, max: 145 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 1, 0, 0, 2, 1],
      HH: [2, 2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['samba', 'bateria', 'sambadrome', 'carnival'],
    instruments: ['surdo', 'caixa', 'tamborim'],
    swingable: true,
    story: 'The theme-song samba written yearly by each escola de samba for the Rio parade. 300+ drummers strong, telling a story the whole school will sing above the bateria.',
    relatedIds: ['samba-partido-alto'],
  },
  {
    id: 'pagode',
    name: 'Pagode',
    origin: 'Brazil · Rio de Janeiro',
    tradition: 'Backyard hand-percussion samba',
    genre: 'popular',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 95, min: 80, max: 110 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 1, 2, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 2],
      HH: [2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['pagode', 'tantã', 'cavaquinho', 'fundo-de-quintal'],
    instruments: ['tantã', 'repique de mão', 'pandeiro'],
    swingable: true,
    story: 'When the batucada got too big, pagode moved the party back to the backyard. Tantã and repique de mão (hand-drums) replaced the sticks; intimacy replaced spectacle.',
    relatedIds: ['samba-partido-alto'],
  },
  {
    id: 'frevo',
    name: 'Frevo',
    origin: 'Brazil · Recife, Pernambuco',
    tradition: 'Carnival brass-band dance',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 175, min: 150, max: 200 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0],
      SN: [2, 2, 2, 0, 2, 2, 2, 2],
      HH: [2, 2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['frevo', 'recife', 'carnival', 'capoeira', 'unesco'],
    instruments: ['caixa', 'surdo', 'trumpets'],
    swingable: false,
    story: 'Recife\'s "ferver" — to boil. Brass bands blow at 180 BPM while dancers kick and jump with a tiny umbrella, the descendants of capoeira fighters who cleared the street.',
  },
  {
    id: 'forro',
    name: 'Forró',
    origin: 'Brazil · Northeast',
    tradition: 'Pé-de-serra trio (accordion + zabumba + triangle)',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 120, min: 100, max: 140 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 1, 0, 0, 0, 1, 0],
      HH: [2, 2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['forró', 'pé-de-serra', 'luiz-gonzaga', 'accordion'],
    instruments: ['zabumba', 'triangle', 'sanfona'],
    swingable: false,
    story: 'The generic, foundational forró — the zabumba\'s mallet-and-stick conversation under an accordion. Luiz Gonzaga called himself the King of Baião and made the whole Northeast sing.',
    relatedIds: ['baiao'],
  },
  {
    id: 'xote',
    name: 'Xote',
    origin: 'Brazil · Northeast',
    tradition: 'Slow forró cousin (from Schottische)',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 95, min: 80, max: 115 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 1, 0, 0, 0, 0, 1],
      HH: [2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['xote', 'forró', 'schottische', 'romantic'],
    instruments: ['zabumba', 'triangle', 'sanfona'],
    swingable: false,
    story: 'The slower, romantic sibling of baião. The name is Brazilian-Portuguese for "Schottische" — a European dance that arrived in the 1800s and settled in the sertão.',
    relatedIds: ['forro', 'baiao'],
  },
  {
    id: 'coco',
    name: 'Coco',
    origin: 'Brazil · Northeast',
    tradition: 'Afro-Brazilian foot-stomping circle',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 115, min: 100, max: 130 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['coco', 'afro-brazilian', 'stomping', 'jackson-do-pandeiro'],
    instruments: ['surdo', 'pandeiro', 'ganzá'],
    swingable: false,
    story: 'A circle dance from Alagoas and Pernambuco, stamped out in wooden clogs on hard ground. Indigenous and African ancestry meet in the stomp-clap-chant.',
  },
  {
    id: 'ijexa',
    name: 'Ijexá',
    origin: 'Brazil · Salvador, Bahia',
    tradition: 'Afoxé / Candomblé rhythm for Oxum',
    genre: 'devotional',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 95, min: 80, max: 110 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 0, 0, 2, 0, 2, 2, 0, 0, 2, 0, 2, 2, 0, 0, 2],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['candomblé', 'oxum', 'afoxé', 'filhos-de-gandhy'],
    instruments: ['agogô', 'atabaque', 'xequerê'],
    swingable: false,
    story: 'The rhythm of the orixá Oxum — goddess of rivers, love, gold. When 10,000 Filhos de Gandhy process through Salvador\'s carnival playing ijexá, the city becomes a trance.',
    relatedIds: ['samba-reggae'],
  },
  {
    id: 'axe',
    name: 'Axé',
    origin: 'Brazil · Salvador, Bahia',
    tradition: 'Bahian carnival pop',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 125, min: 110, max: 140 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 1],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['axé', 'trio-elétrico', 'daniela-mercury', 'bahia'],
    instruments: ['timbau', 'caixa', 'surdo'],
    swingable: false,
    story: 'The pop-carnival sound of Salvador\'s trios elétricos. "Axé" is Yoruba for life-force; the music fuses samba-reggae, ijexá, frevo, merengue into a stadium-sized groove.',
    relatedIds: ['samba-reggae', 'ijexa'],
  },
  {
    id: 'samba-batucada',
    name: 'Samba Batucada',
    origin: 'Brazil · Rio de Janeiro',
    tradition: 'Escola de samba surdo battery',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 100, min: 85, max: 120 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['samba', 'batucada', 'surdo', 'street-samba'],
    instruments: ['surdo', 'tamborim', 'agogô'],
    swingable: true,
    story: 'The street-samba battery pared down to its core: three interlocking surdos, a tamborim syncopating above, and agogô shimmer on top. The sound of Rio\'s neighborhood rehearsal halls.',
    relatedIds: ['samba-enredo', 'samba-partido-alto'],
  },
  {
    id: 'samba-de-roda',
    name: 'Samba de Roda',
    origin: 'Brazil · Recôncavo Baiano',
    tradition: 'Circle samba (UNESCO heritage)',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 110, min: 95, max: 125 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 0, 2, 1, 2, 0, 2, 1],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['samba-de-roda', 'bahia', 'recôncavo', 'unesco', 'root'],
    instruments: ['atabaque', 'pandeiro', 'palmas'],
    swingable: true,
    story: 'The root of all samba. In the Recôncavo villages around the Bay of All Saints, dancers step into a circle one at a time, invited by an umbigada — a belly-bump — to the next. UNESCO Intangible Heritage, 2005.',
    relatedIds: ['samba-partido-alto', 'samba-enredo'],
  },
];
