import type { Pattern } from '../types';

export const BRAZIL_PATTERNS: Pattern[] = [
  {
    id: 'bossa-nova',
    name: 'Bossa Nova',
    origin: 'Brazil · Rio de Janeiro',
    tradition: 'Cool jazz / samba',
    genre: 'jazz',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 128, min: 70, max: 160 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['jazz', 'cool', 'partido-alto', 'ipanema'],
    instruments: ['nylon guitar', 'brushes', 'surdo'],
    swingable: true,
    story: 'Jobim and João Gilberto slowed samba down, stripped it bare, and dressed it in cool-jazz harmony. The cross-stick traces the partido-alto skeleton.',
    relatedIds: ['samba-partido-alto'],
  },
  {
    id: 'samba-partido-alto',
    name: 'Samba Partido Alto',
    origin: 'Brazil · Rio de Janeiro',
    tradition: 'Samba subgenre',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 110, min: 90, max: 130 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 2, 0, 0, 2, 0],
      HH: [2, 0, 1, 0, 2, 0, 1, 0],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['samba', 'partido-alto', 'pagode', 'pandeiro'],
    instruments: ['pandeiro', 'tantã', 'cavaquinho'],
    swingable: true,
    story: 'Older, rootsier samba — circled around improvised verses and hand percussion. The partido-alto pattern became the "Brazilian clave" that crossed into bossa and jazz.',
  },
  {
    id: 'samba-reggae',
    name: 'Samba-Reggae',
    origin: 'Brazil · Salvador, Bahia',
    tradition: 'Olodum / bloco afro',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 105, min: 90, max: 120 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['bahia', 'olodum', 'bloco-afro', 'interlocking-surdos'],
    instruments: ['surdo', 'repique', 'caixa'],
    swingable: false,
    story: 'Created in 1986 by Neguinho do Samba for Olodum — samba\'s surdo foundation married to reggae\'s tempo, three drums interlocking into a wall of bass through the streets of Salvador.',
  },
  {
    id: 'baiao',
    name: 'Baião',
    origin: 'Brazil · Northeast',
    tradition: 'Forró',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 120, min: 100, max: 140 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 1, 0, 0, 0, 0, 1],
      HH: [2, 0, 2, 2, 2, 0, 2, 2],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['forró', 'zabumba', 'accordion', 'sertão'],
    instruments: ['zabumba', 'triangle', 'sanfona'],
    swingable: false,
    story: 'The foundational rhythm of forró, from the arid sertão of Pernambuco — zabumba bass-and-slap, triangle, accordion. Luiz Gonzaga brought it to the whole country.',
  },
  {
    id: 'maracatu',
    name: 'Maracatu',
    origin: 'Brazil · Pernambuco',
    tradition: 'Afro-Brazilian procession',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 95, min: 80, max: 110 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['afro-brazilian', 'procession', 'alfaia', 'candomble'],
    instruments: ['alfaia', 'gongue', 'caixa'],
    swingable: false,
    story: 'One of Brazil\'s oldest Afro-descended traditions — born from the coronation processions of enslaved African "kings and queens" in colonial Pernambuco.',
  },
];
