import type { Pattern } from '../types';

export const CARIBBEAN_PATTERNS: Pattern[] = [
  {
    id: 'reggaeton-dembow',
    name: 'Reggaeton Dembow',
    origin: 'Puerto Rico · Dominican Republic',
    tradition: 'Urbano',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 95, min: 85, max: 105 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
      SN: [0, 0, 0, 1, 2, 0, 0, 1, 0, 0, 0, 1, 2, 0, 0, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '808',
    country: 'PR',
    region: 'caribbean',
    tags: ['urbano', 'dembow', 'perreo', 'latin'],
    instruments: ['808 kick', 'clap', 'timbale'],
    swingable: false,
    story: 'The dembow riddim that conquered the world — Jamaican dancehall mutated through Panama, Puerto Rico and the DR into the global sound of reggaeton.',
    relatedIds: ['dancehall'],
  },
  {
    id: 'dancehall',
    name: 'Dancehall',
    origin: 'Jamaica',
    tradition: 'Dancehall riddim',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 100, min: 80, max: 120 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '808',
    country: 'JM',
    region: 'caribbean',
    tags: ['jamaica', 'riddim', 'sound-system'],
    instruments: ['808', 'syndrum', 'bass'],
    swingable: false,
    story: 'Kingston sound systems, digital riddims, Shabba Ranks and Vybz Kartel. Every modern Caribbean dance pattern traces back here.',
  },
  {
    id: 'kompa',
    name: 'Kompa',
    origin: 'Haiti',
    tradition: 'Haitian popular',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 115, min: 100, max: 130 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '808',
    country: 'HT',
    region: 'caribbean',
    tags: ['haiti', 'tanbou', 'sensual', 'mini-djaz'],
    instruments: ['tanbou', 'cowbell', 'bass'],
    swingable: false,
    story: 'Nemours Jean-Baptiste\'s 1955 invention — a slow, sensual grind built on cowbell, tanbou, and bass. Haiti\'s national sound, and UNESCO heritage since 2025.',
  },
  {
    id: 'soca',
    name: 'Soca',
    origin: 'Trinidad and Tobago',
    tradition: 'Carnival',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 142, min: 130, max: 160 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 1],
      HH: [2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1],
    },
    defaultKit: '808',
    country: 'TT',
    region: 'caribbean',
    tags: ['carnival', 'trinidad', 'indian-fusion', 'soca'],
    instruments: ['drums', 'iron', 'tassa'],
    swingable: false,
    story: 'Lord Shorty\'s 1970s fusion of calypso with East Indian rhythms — the "soul of calypso." The signature hi-hat opens on the last sixteenth of every beat.',
  },
];
