import type { Pattern } from '../types';

export const CARIBBEAN_PATTERNS: Pattern[] = [
  {
    id: 'reggaeton-dembow',
    name: 'Reggaeton Dembow',
    origin: 'Puerto Rico · Dominican Republic',
    tradition: 'Urbano',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 380, min: 340, max: 420 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
      SN: [0, 0, 0, 1, 2, 0, 0, 1, 0, 0, 0, 1, 2, 0, 0, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '808',
    country: 'PR',
    region: 'caribbean',
    tags: ['urbano', 'dembow', 'perreo', 'latin'],
    instruments: ['808 kick', 'clap', 'timbale'],
    swingable: false,
    story: 'The dembow riddim that conquered the world — Jamaican dancehall mutated through Panama, Puerto Rico and the DR into the global sound of reggaeton.',
    relatedIds: ['dancehall', 'moombahton', 'bongo-flava', 'gengetone'],
  },
  {
    id: 'dancehall',
    name: 'Dancehall',
    origin: 'Jamaica',
    tradition: 'Dancehall riddim',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 400, min: 320, max: 480 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '808',
    country: 'JM',
    region: 'caribbean',
    tags: ['jamaica', 'riddim', 'sound-system'],
    instruments: ['808', 'syndrum', 'bass'],
    swingable: false,
    story: 'Kingston sound systems, digital riddims, Shabba Ranks and Vybz Kartel. Every modern Caribbean dance pattern traces back here.',
    relatedIds: ['reggaeton-dembow', 'jamaica-one-drop', 'moombahton'],
  },
  {
    id: 'kompa',
    name: 'Kompa',
    origin: 'Haiti',
    tradition: 'Haitian popular',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 460, min: 400, max: 520 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '808',
    country: 'HT',
    region: 'caribbean',
    tags: ['haiti', 'tanbou', 'sensual', 'mini-djaz'],
    instruments: ['tanbou', 'cowbell', 'bass'],
    swingable: false,
    story: 'Nemours Jean-Baptiste\'s 1955 invention — a slow, sensual grind built on cowbell, tanbou, and bass. Haiti\'s national sound, and UNESCO heritage since 2025.',
    relatedIds: ['zouk-bass', 'kizomba', 'merengue'],
  },
  {
    id: 'soca',
    name: 'Soca',
    origin: 'Trinidad and Tobago',
    tradition: 'Carnival',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 568, min: 520, max: 640 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 1],
      HH: [2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1],
    },
    defaultKit: '727',
    country: 'TT',
    region: 'caribbean',
    tags: ['carnival', 'trinidad', 'indian-fusion', 'soca'],
    instruments: ['drums', 'iron', 'tassa'],
    swingable: false,
    story: 'Lord Shorty\'s 1970s fusion of calypso with East Indian rhythms — the "soul of calypso." The signature hi-hat opens on the last sixteenth of every beat.',
    relatedIds: ['calypso', 'bhangra'],
  },
  {
    id: 'calypso',
    name: 'Calypso',
    origin: 'Trinidad and Tobago',
    tradition: 'Storytelling / topical song',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 460, min: 400, max: 520 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 1, 0],
      SN: [0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'TT',
    region: 'caribbean',
    tags: ['calypso', 'kaiso', 'lord-kitchener', 'mighty-sparrow'],
    instruments: ['drums', 'iron', 'steel pan'],
    swingable: true,
    story: 'Trinidad\'s newspaper of the people — Lord Kitchener and Mighty Sparrow used the form to praise, satirise, and scandalise. The lilt swings around the offbeats.',
    relatedIds: ['soca', 'mento'],
  },
  {
    id: 'mento',
    name: 'Mento',
    origin: 'Jamaica',
    tradition: 'Jamaican folk (pre-ska)',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 420, min: 360, max: 480 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'JM',
    region: 'caribbean',
    tags: ['mento', 'jamaican-folk', 'jolly-boys', 'rumba-box'],
    instruments: ['banjo', 'rumba box', 'hand drum'],
    swingable: true,
    story: 'Before ska, before reggae — mento was Jamaica\'s own folk music. Banjo, rumba box, and bawdy social commentary. The Jolly Boys from Port Antonio carried it into the 21st century.',
    relatedIds: ['calypso', 'ska'],
  },
  {
    id: 'ska',
    name: 'Ska',
    origin: 'Jamaica · Kingston',
    tradition: 'Skatalites / Studio One',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 580, min: 480, max: 720 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
      CP: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'JM',
    region: 'caribbean',
    tags: ['ska', 'offbeat', 'skatalites', 'lloyd-knibb'],
    instruments: ['drums', 'guitar chop', 'piano'],
    swingable: false,
    story: 'Jamaica 1962 — the year of independence and the year the offbeat became a national identity. Lloyd Knibb\'s drums turned American R&B inside out.',
    relatedIds: ['rocksteady', 'jamaica-one-drop', 'ska-classic', 'mento'],
  },
  {
    id: 'rocksteady',
    name: 'Rocksteady',
    origin: 'Jamaica · Kingston',
    tradition: 'Alton Ellis / Studio One',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 320, min: 280, max: 360 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
      CP: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'JM',
    region: 'caribbean',
    tags: ['rocksteady', 'alton-ellis', 'bass-forward', 'bubble-organ'],
    instruments: ['drums', 'bass', 'bubble organ'],
    swingable: false,
    story: 'Summer 1966 — the music slowed down. Nobody is sure why, but when it did, space opened up for the bass to step forward and become the lead instrument.',
    relatedIds: ['ska', 'jamaica-one-drop'],
  },
  {
    id: 'jamaica-one-drop',
    name: 'Reggae One-Drop',
    origin: 'Jamaica',
    tradition: 'Carlton Barrett / Bob Marley',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 300, min: 260, max: 360 },
    difficulty: 'beginner',
    tracks: {
      KK: [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
      CP: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'JM',
    region: 'caribbean',
    tags: ['reggae', 'one-drop', 'carlton-barrett', 'bob-marley'],
    instruments: ['drums', 'bass', 'skank guitar'],
    swingable: false,
    story: 'Beat 1 is empty — dropped. Carlton Barrett turned the downbeat\'s absence into gravity itself. Everything leans toward the snare-kick unison on beat 3.',
    relatedIds: ['rocksteady', 'jamaica-rockers', 'jamaica-steppers', 'reggae-one-drop', 'samba-reggae'],
  },
  {
    id: 'jamaica-rockers',
    name: 'Reggae Rockers',
    origin: 'Jamaica',
    tradition: 'Sly Dunbar / Black Uhuru',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 320, min: 280, max: 380 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
      CP: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'JM',
    region: 'caribbean',
    tags: ['reggae', 'rockers', 'sly-dunbar', 'driving'],
    instruments: ['drums', 'bass', 'skank guitar'],
    swingable: false,
    story: 'Sly Dunbar\'s answer to the one-drop — put the kick back on beat 1 AND beat 3. Harder, more driving, built for dub plates at the dance.',
    relatedIds: ['jamaica-one-drop', 'jamaica-steppers'],
  },
  {
    id: 'jamaica-steppers',
    name: 'Reggae Steppers',
    origin: 'Jamaica',
    tradition: 'Burning Spear / Marley "Exodus"',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 340, min: 300, max: 400 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
      CP: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'JM',
    region: 'caribbean',
    tags: ['reggae', 'steppers', 'four-on-floor', 'exodus'],
    instruments: ['drums', 'bass', 'skank guitar'],
    swingable: false,
    story: 'Four on the floor, reggae style. "Exodus," "Marcus Garvey" — the ancestor of the whole electronic dance family.',
    relatedIds: ['jamaica-one-drop', 'jamaica-rockers'],
  },
  {
    id: 'bachata',
    name: 'Bachata',
    origin: 'Dominican Republic',
    tradition: 'Guitar-led romantic music',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 520, min: 480, max: 580 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'DO',
    region: 'caribbean',
    tags: ['bachata', 'dominican', 'bongo', 'derecho'],
    instruments: ['bongó', 'güira', 'guitar'],
    swingable: false,
    story: 'José Manuel Calderón cut the first bachata in 1962. For decades the Dominican elite dismissed it as cabaret music — until Juan Luis Guerra took it to the world.',
    relatedIds: ['bolero', 'merengue'],
  },
];
