import type { Pattern } from '../types';

export const CELTIC_EUROPE_PATTERNS: Pattern[] = [
  {
    id: 'irish-reel',
    name: 'Irish Reel',
    origin: 'Ireland',
    tradition: 'Ceili session',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 115, min: 100, max: 130 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '707',
    country: 'IE',
    region: 'celtic-europe',
    tags: ['celtic', 'irish', 'session', 'bodhran'],
    instruments: ['bodhrán', 'fiddle', 'tin whistle'],
    swingable: false,
    story: 'The most common tune type in Irish sessions — driving eighth notes, strong pulse on 1 and 3, bodhrán accenting the main beats with a tipper.',
  },
  {
    id: 'jig',
    name: 'Irish Jig',
    origin: 'Ireland',
    tradition: 'Ceili / dance',
    genre: 'folk-dance',
    timeSig: '6/8',
    grouping: [3, 3],
    stepUnit: 8,
    steps: 6,
    bpm: { default: 120, min: 100, max: 135 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 1, 0, 0],
      SN: [0, 0, 2, 0, 0, 2],
      HH: [2, 1, 2, 2, 1, 2],
    },
    defaultKit: '707',
    country: 'IE',
    region: 'celtic-europe',
    tags: ['celtic', 'irish', 'compound', '6-8', 'dance'],
    instruments: ['bodhrán', 'fiddle', 'flute'],
    swingable: false,
    story: 'Two groups of three — "DI-di-di, DI-di-di" — the bouncing lilt that fuels half the Irish repertoire after the reel.',
  },
  {
    id: 'scandi-polska',
    name: 'Scandi Polska',
    origin: 'Sweden · Dalarna',
    tradition: 'Swedish folk couple dance',
    genre: 'folk-dance',
    timeSig: '3/4',
    grouping: [4, 4, 4],
    stepUnit: 16,
    steps: 12,
    bpm: { default: 120, min: 100, max: 140 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0],
      HH: [2, 0, 1, 0, 2, 0, 1, 0, 2, 0, 1, 0],
    },
    defaultKit: '707',
    country: 'SE',
    region: 'celtic-europe',
    tags: ['scandinavian', 'swedish', 'asymmetric', 'nyckelharpa'],
    instruments: ['nyckelharpa', 'fiddle'],
    swingable: true,
    story: 'A Swedish couple dance in 3 — but the beats are unequal. Played on nyckelharpa, the beat-2 delay is an intentional feature tied to the dance, not a mistake.',
  },
];
