import type { Pattern } from '../types';

export const CELTIC_EUROPE_PATTERNS: Pattern[] = [
  {
    id: 'irish-reel',
    name: 'Irish Reel',
    origin: 'Ireland',
    tradition: 'Ceili session',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 460, min: 400, max: 520 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '707',
    country: 'IE',
    region: 'celtic-europe',
    tags: ['celtic', 'irish', 'session', 'bodhran'],
    instruments: ['bodhrán', 'fiddle', 'tin whistle'],
    swingable: false,
    story: 'The most common tune type in Irish sessions — driving eighth notes, strong pulse on 1 and 3, bodhrán accenting the main beats with a tipper.',
  },
  {
    id: 'jig',
    name: 'Irish Jig',
    origin: 'Ireland',
    tradition: 'Ceili / dance',
    genre: 'folk-dance',
    timeSig: '6/8',
    grouping: [3, 3],
    stepUnit: 8,
    steps: 6,
    bpm: { default: 120, min: 100, max: 135 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 1, 0, 0],
      SN: [0, 0, 2, 0, 0, 2],
      HH: [2, 1, 2, 2, 1, 2],
    },
    defaultKit: '707',
    country: 'IE',
    region: 'celtic-europe',
    tags: ['celtic', 'irish', 'compound', '6-8', 'dance'],
    instruments: ['bodhrán', 'fiddle', 'flute'],
    swingable: false,
    story: 'Two groups of three — "DI-di-di, DI-di-di" — the bouncing lilt that fuels half the Irish repertoire after the reel.',
  },
  {
    id: 'scandi-polska',
    name: 'Scandi Polska',
    origin: 'Sweden · Dalarna',
    tradition: 'Swedish folk couple dance',
    genre: 'folk-dance',
    timeSig: '3/4',
    grouping: [4, 4, 4],
    stepUnit: 16,
    steps: 12,
    bpm: { default: 480, min: 400, max: 560 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0],
      HH: [2, 0, 1, 0, 2, 0, 1, 0, 2, 0, 1, 0],
    },
    defaultKit: '707',
    country: 'SE',
    region: 'celtic-europe',
    tags: ['scandinavian', 'swedish', 'asymmetric', 'nyckelharpa'],
    instruments: ['nyckelharpa', 'fiddle'],
    swingable: true,
    story: 'A Swedish couple dance in 3 — but the beats are unequal. Played on nyckelharpa, the beat-2 delay is an intentional feature tied to the dance, not a mistake.',
  },
  {
    id: 'hornpipe',
    name: 'Irish Hornpipe',
    origin: 'Ireland · England',
    tradition: 'Hard-shoe dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 340, min: 280, max: 400 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0],
      HH: [2, 0, 0, 1, 2, 0, 0, 1, 2, 0, 0, 1, 2, 0, 0, 1],
    },
    defaultKit: '707',
    country: 'IE',
    region: 'celtic-europe',
    tags: ['celtic', 'irish', 'hornpipe', 'dotted', 'hard-shoe'],
    instruments: ['bodhrán', 'fiddle', 'flute'],
    swingable: true,
    story: 'A dotted, swaggering 4/4 — long-short, long-short — built for the audible clicks of hard-shoe dancing. Apply about 66% swing to hear it breathe.',
    relatedIds: ['irish-reel'],
  },
  {
    id: 'slip-jig',
    name: 'Slip Jig',
    origin: 'Ireland',
    tradition: 'Soft-shoe solo dance',
    genre: 'folk-dance',
    timeSig: '9/8',
    grouping: [3, 3, 3],
    stepUnit: 8,
    steps: 9,
    bpm: { default: 120, min: 100, max: 135 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 1, 0, 0, 1, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 0, 2],
      HH: [2, 1, 2, 2, 1, 2, 2, 1, 2],
    },
    defaultKit: '707',
    country: 'IE',
    region: 'celtic-europe',
    tags: ['celtic', 'irish', 'compound', '9-8', 'slip-jig', 'graceful'],
    instruments: ['bodhrán', 'fiddle', 'flute'],
    swingable: false,
    story: 'The most graceful Irish form — three threes instead of two, a waltz-lilt with a distinctly Irish roll. Historically a woman\'s soft-shoe solo.',
    relatedIds: ['jig', 'semachi', 'yuruk-semai'],
  },
  {
    id: 'slide',
    name: 'Slide',
    origin: 'Ireland · Sliabh Luachra',
    tradition: 'Set dance',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 145, min: 125, max: 165 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 1, 0, 0, 2, 0, 0, 1, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2],
    },
    defaultKit: '707',
    country: 'IE',
    region: 'celtic-europe',
    tags: ['celtic', 'irish', 'slide', '12-8', 'sliabh-luachra'],
    instruments: ['bodhrán', 'fiddle', 'accordion'],
    swingable: false,
    story: 'The fast 12/8 of Sliabh Luachra — four compound beats, played in medleys with polkas at dance sets on the Cork-Kerry border.',
    relatedIds: ['irish-polka'],
  },
  {
    id: 'irish-polka',
    name: 'Irish Polka',
    origin: 'Ireland · Sliabh Luachra',
    tradition: 'Set dance',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 520, min: 480, max: 560 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 1, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '707',
    country: 'IE',
    region: 'celtic-europe',
    tags: ['celtic', 'irish', 'polka', 'sliabh-luachra', 'party'],
    instruments: ['bodhrán', 'fiddle', 'accordion'],
    swingable: false,
    story: 'The party rhythm of the Cork-Kerry borderlands — brighter and punchier than any reel. Strong on 1, light on 2, usually paired with slides.',
    relatedIds: ['slide'],
  },
  {
    id: 'strathspey',
    name: 'Strathspey',
    origin: 'Scotland · Highlands',
    tradition: 'Highland dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 560, min: 520, max: 608 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [1, 0, 0, 2, 2, 0, 0, 1, 1, 0, 2, 0, 2, 0, 0, 1],
      HH: [2, 0, 0, 1, 2, 0, 0, 1, 2, 0, 0, 1, 2, 0, 0, 1],
    },
    defaultKit: '707',
    country: 'GB',
    region: 'celtic-europe',
    tags: ['celtic', 'scottish', 'strathspey', 'scotch-snap', 'highland'],
    instruments: ['fiddle', 'pipe-band-snare', 'bodhrán'],
    swingable: false,
    story: 'The Scotch snap — a short accented note followed by a longer unaccented one, reversing the dotted rhythm. The flamlike snap is Scotland\'s rhythmic signature.',
  },
  {
    id: 'waltz',
    name: 'Waltz',
    origin: 'Central Europe',
    tradition: 'Couple ballroom dance',
    genre: 'folk-dance',
    timeSig: '3/4',
    grouping: [4, 4, 4],
    stepUnit: 16,
    steps: 12,
    bpm: { default: 600, min: 480, max: 720 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '707',
    country: 'AT',
    region: 'celtic-europe',
    tags: ['european', 'waltz', 'couple-dance', '3-4'],
    instruments: ['accordion', 'fiddle', 'guitar'],
    swingable: false,
    story: 'The universal 3/4 — one-two-three, one-two-three. Folk waltzes from Scandinavia to Ireland to Bavaria all share the same oom-pah-pah skeleton.',
  },
  {
    id: 'mazurka',
    name: 'Mazurka',
    origin: 'Poland · Mazovia',
    tradition: 'Folk couple dance',
    genre: 'folk-dance',
    timeSig: '3/4',
    grouping: [4, 4, 4],
    stepUnit: 16,
    steps: 12,
    bpm: { default: 640, min: 520, max: 760 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 1, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '707',
    country: 'PL',
    region: 'celtic-europe',
    tags: ['european', 'polish', 'mazurka', 'couple-dance', '3-4'],
    instruments: ['accordion', 'fiddle', 'frame-drum'],
    swingable: false,
    story: 'A 3/4 with the accent on beat 2 or 3, never the downbeat — the quirk that distinguishes the Mazovian mazur from a waltz. Chopin made it international.',
    relatedIds: ['waltz'],
  },
  {
    id: 'schottische',
    name: 'Schottische',
    origin: 'Central Europe',
    tradition: 'Couple folk dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 440, min: 360, max: 520 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '707',
    country: 'DE',
    region: 'celtic-europe',
    tags: ['european', 'schottische', 'couple-dance', 'bouncy'],
    instruments: ['accordion', 'fiddle', 'guitar'],
    swingable: false,
    story: 'A 19th-century "Scottish" dance invented in Bohemia — bouncy 4/4 with a hop on the fourth beat. Spread through dance halls from Scandinavia to the American frontier.',
    relatedIds: ['xote', 'bourree'],
  },
  {
    id: 'czardas',
    name: 'Csárdás',
    origin: 'Hungary',
    tradition: 'National dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 560, min: 400, max: 800 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0],
      HH: [2, 0, 0, 1, 2, 0, 0, 1, 2, 0, 0, 1, 2, 0, 0, 1],
    },
    defaultKit: '707',
    country: 'HU',
    region: 'celtic-europe',
    tags: ['hungarian', 'csardas', 'friss', 'romani', 'accelerando'],
    instruments: ['violin', 'cimbalom', 'bass'],
    swingable: true,
    story: 'The Hungarian national dance — starts slow and stately (lassú), then explodes into wild accelerando (friss). Built by Romani musicians at Hussar recruiting parties.',
    relatedIds: ['cocek', 'roman-havasi'],
  },
  {
    id: 'bourree',
    name: 'Bourrée',
    origin: 'France · Auvergne · Berry',
    tradition: 'Folk dance',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 480, min: 400, max: 560 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 1, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '707',
    country: 'FR',
    region: 'celtic-europe',
    tags: ['european', 'french', 'bourree', 'village', 'cabrette'],
    instruments: ['cabrette', 'vielle', 'accordion'],
    swingable: false,
    story: 'The village dance of central France — played on the Auvergnat cabrette bagpipe and the vielle à roue hurdy-gurdy. A bright 2/4 under melody built on drones.',
  },
  {
    id: 'pols',
    name: 'Pols',
    origin: 'Sweden',
    tradition: 'Folk couple dance',
    genre: 'folk-dance',
    timeSig: '3/4',
    grouping: [4, 4, 4],
    stepUnit: 16,
    steps: 12,
    bpm: { default: 520, min: 440, max: 600 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '707',
    country: 'SE',
    region: 'celtic-europe',
    tags: ['scandinavian', 'swedish', 'pols', 'couple-dance', '3-4'],
    instruments: ['nyckelharpa', 'fiddle'],
    swingable: true,
    story: 'The straighter Swedish cousin of the polska — still 3/4, still couple-turning, but with more even beats. The bridge between polska asymmetry and plain waltz.',
    relatedIds: ['scandi-polska'],
  },
  {
    id: 'halling',
    name: 'Halling',
    origin: 'Norway · Hallingdal',
    tradition: 'Men\'s showcase dance',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 520, min: 440, max: 600 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 1, 0],
      SN: [0, 0, 2, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '707',
    country: 'NO',
    region: 'celtic-europe',
    tags: ['scandinavian', 'norwegian', 'halling', 'acrobatic', 'hardanger-fiddle'],
    instruments: ['hardingfele', 'langeleik'],
    swingable: false,
    story: 'Norway\'s acrobatic men\'s dance — 2/4 for kicks, spins, and the famous hat-knocking high kick. Played on the Hardanger fiddle with its ringing sympathetic strings.',
  },
];
