import type { Pattern } from '../types';

export const CENTRAL_ASIAN_PACIFIC_PATTERNS: Pattern[] = [
  // ============================================================
  // Central Asia / Silk Road
  // ============================================================
  {
    id: 'uzbek-doira-basic',
    name: 'Uzbek Doira Usul',
    origin: 'Uzbekistan',
    tradition: 'Uzbek classical / folk',
    genre: 'folk-dance',
    timeSig: '6/8',
    grouping: [3, 3],
    stepUnit: 8,
    steps: 6,
    bpm: { default: 220, min: 180, max: 260 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0],
      SN: [0, 0, 2, 0, 0, 2],
      HH: [2, 1, 2, 2, 1, 2],
    },
    defaultKit: 'frameDrum',
    country: 'UZ',
    region: 'central-asian-pacific',
    tags: ['doira', 'frame-drum', 'silk-road', 'uzbek'],
    instruments: ['doira', 'dutar'],
    swingable: false,
    story: 'The foundational "Bum–Bak" alternation every doira student learns. Metal rings shimmer on every edge stroke underneath Uzbek folk song and Shashmaqom.',
  },
  {
    id: 'uzbek-lapar',
    name: 'Lapar / Yalla',
    origin: 'Uzbekistan · Ferghana',
    tradition: 'Uzbek folk song-dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 440, min: 400, max: 480 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'UZ',
    region: 'central-asian-pacific',
    tags: ['lapar', 'yalla', 'song-dance', 'ferghana'],
    instruments: ['doira', 'rubab', 'voice'],
    swingable: false,
    story: 'Lapar and yalla are antiphonal song-dances from the Ferghana valley — women and men trading verses while the doira drives the celebration.',
  },
  {
    id: 'tajik-dumbak',
    name: 'Tajik Dumbak Groove',
    origin: 'Tajikistan',
    tradition: 'Tajik classical / folk',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 400, min: 360, max: 440 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 2, 0, 0, 1, 0, 0, 2, 0, 2, 0, 0, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'TJ',
    region: 'central-asian-pacific',
    tags: ['dumbak', 'tablak', 'tajik', 'persianate'],
    instruments: ['dumbak', 'dutar', 'gijak'],
    swingable: false,
    story: 'Tajik dumbak (tablak) patterns bridge Persian zarb technique and Central Asian doira language — doum on centre, tek on the edge, ghost notes threading between.',
  },
  {
    id: 'uyghur-muqam-78',
    name: 'Uyghur Muqam (7/8)',
    origin: 'Xinjiang · Uyghur',
    tradition: 'Twelve Muqam · Mashrap',
    genre: 'classical',
    timeSig: '7/8',
    grouping: [2, 2, 3],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 260, min: 220, max: 300 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0],
      SN: [0, 0, 0, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    country: 'CN',
    region: 'central-asian-pacific',
    tags: ['muqam', 'uyghur', 'aqsaq', 'silk-road'],
    instruments: ['dap', 'rubab', 'satar'],
    swingable: false,
    story: 'Aqsaq ("limping") 2+2+3 cycle from the Mashrap dance section of the Twelve Muqam. Dap frame drum rings chime on every edge stroke.',
    relatedIds: ['karsilama'],
  },
  {
    id: 'turkmen-suzme',
    name: 'Turkmen Suzme',
    origin: 'Turkmenistan',
    tradition: 'Turkmen folk',
    genre: 'folk-dance',
    timeSig: '6/8',
    grouping: [3, 3],
    stepUnit: 8,
    steps: 6,
    bpm: { default: 240, min: 200, max: 280 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0],
      SN: [0, 2, 0, 0, 2, 1],
      HH: [2, 1, 2, 2, 1, 2],
    },
    defaultKit: 'frameDrum',
    country: 'TM',
    region: 'central-asian-pacific',
    tags: ['suzme', 'turkmen', 'bagshy'],
    instruments: ['dep', 'dutar', 'gidjak'],
    swingable: false,
    story: 'Suzme ("the strained one") is the signature rolling 6/8 of Turkmen bagshy bards — rhythm of nomadic horsemen set into song.',
  },
  {
    id: 'afghan-attan',
    name: 'Afghan Attan',
    origin: 'Afghanistan · Pashtun',
    tradition: 'National circle dance',
    genre: 'folk-dance',
    timeSig: '7/8',
    grouping: [3, 2, 2],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 260, min: 180, max: 320 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 2, 0],
      SN: [0, 0, 2, 0, 2, 0, 2],
      HH: [2, 1, 2, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'AF',
    region: 'central-asian-pacific',
    tags: ['attan', 'pashtun', 'circle-dance', 'accelerando'],
    instruments: ['dhol', 'sorna'],
    swingable: false,
    story: 'Afghanistan\'s national dance — a 3+2+2 circle that starts dignified and accelerates for hours. The dhol drives the spiral, hundreds of feet answering.',
  },
  {
    id: 'afghan-tabla-dhol',
    name: 'Afghan Tabla + Dhol',
    origin: 'Afghanistan · Kabul / Herat',
    tradition: 'Afghan classical / film song',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 376, min: 340, max: 420 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0],
      SN: [0, 0, 2, 0, 2, 0, 0, 1, 0, 0, 2, 0, 2, 0, 0, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'AF',
    region: 'central-asian-pacific',
    tags: ['tabla', 'dhol', 'afghan', 'kabul'],
    instruments: ['tabla', 'dhol', 'rubab', 'harmonium'],
    swingable: false,
    story: 'Kabul radio orchestras stacked Indian tabla under Pashtun dhol — Ahmad Zahir, Ustad Sarahang and the soft-power soundtrack of 1970s Afghanistan.',
  },
  {
    id: 'kyrgyz-komuz',
    name: 'Kyrgyz Komuz Gallop',
    origin: 'Kyrgyzstan',
    tradition: 'Kyrgyz komuz / manaschi',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 520, min: 440, max: 600 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 2, 2, 0, 0, 2],
      SN: [0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'KG',
    region: 'central-asian-pacific',
    tags: ['komuz', 'kyrgyz', 'gallop', 'steppe'],
    instruments: ['komuz', 'kyl-kyiak'],
    swingable: false,
    story: 'Three-string komuz strumming that imitates a horse galloping across the Tien Shan. Not a drum tradition but a rhythm carved from hooves.',
  },

  // ============================================================
  // Polynesia / Pacific
  // ============================================================
  {
    id: 'samoan-sasa',
    name: 'Samoan Sasa',
    origin: 'Samoa',
    tradition: 'Samoan group dance',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 440, min: 400, max: 520 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'gamelan',
    country: 'WS',
    region: 'central-asian-pacific',
    tags: ['sasa', 'samoa', 'group-dance', 'pate'],
    instruments: ['pate', 'body-percussion', 'voice'],
    swingable: false,
    story: 'The sasa is a seated group dance where dozens of bodies slap legs, chests and pate slit-drums in perfect unison — rhythm as collective architecture.',
  },
  {
    id: 'tahitian-toere',
    name: 'Tahitian Toere',
    origin: 'Tahiti · French Polynesia',
    tradition: 'Ote\'a dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 760, min: 640, max: 880 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 2, 2],
      HH: [2, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 0, 2, 0],
    },
    defaultKit: 'gamelan',
    country: 'PF',
    region: 'central-asian-pacific',
    tags: ['toere', 'tahiti', 'ote-a', 'slit-drum'],
    instruments: ['to\'ere', 'fa\'atete', 'tariparau'],
    swingable: false,
    story: 'The to\'ere slit-drum hits with cone-shaped sticks at speeds closer to Morse code than music — interlocking cells that drive the ote\'a dance.',
  },
  {
    id: 'hawaiian-pahu',
    name: 'Hawaiian Pahu',
    origin: 'Hawai\'i',
    tradition: 'Hula kahiko',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 380, min: 320, max: 440 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: 'gamelan',
    country: 'US',
    region: 'central-asian-pacific',
    tags: ['pahu', 'hula', 'hawaii', 'sacred'],
    instruments: ['pahu', 'ipu', 'voice'],
    swingable: false,
    story: 'The sharkskin-headed pahu is the most sacred drum in Hawaiian culture — reserved for temple hula, synchronised precisely with the chanter\'s breath.',
  },
  {
    id: 'hawaiian-ipu-heke',
    name: 'Ipu Heke',
    origin: 'Hawai\'i',
    tradition: 'Hula · ho\'opa\'a',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 400, min: 320, max: 480 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: 'gamelan',
    country: 'US',
    region: 'central-asian-pacific',
    tags: ['ipu-heke', 'hula', 'gourd-drum', 'hawaii'],
    instruments: ['ipu heke', 'voice'],
    swingable: false,
    story: 'Two calabashes joined in a figure-eight — ground-strike bass and finger-tap treble, earth and air, the Hawaiian cosmology of duality.',
  },
  {
    id: 'maori-haka',
    name: 'Maori Haka',
    origin: 'Aotearoa · New Zealand',
    tradition: 'Kapa haka',
    genre: 'ceremonial',
    timeSig: '3/4',
    grouping: [3, 3, 3, 3],
    stepUnit: 16,
    steps: 12,
    bpm: { default: 432, min: 360, max: 520 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'gamelan',
    country: 'NZ',
    region: 'central-asian-pacific',
    tags: ['haka', 'maori', 'body-percussion', 'kapa-haka'],
    instruments: ['stomp', 'thigh-slap', 'voice'],
    swingable: false,
    story: 'The haka has no instruments — the body IS the drum. Stomping feet, thigh slaps and chest strikes in triple meter, amplified by dozens of voices in unison.',
  },
  {
    id: 'fijian-meke',
    name: 'Fijian Meke',
    origin: 'Fiji',
    tradition: 'Meke dance',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 420, min: 360, max: 480 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: 'gamelan',
    country: 'FJ',
    region: 'central-asian-pacific',
    tags: ['meke', 'fiji', 'lali', 'pacific'],
    instruments: ['lali', 'derua', 'voice'],
    swingable: false,
    story: 'Fijian meke is sung poetry with choreographed movement — the lali log drum and derua bamboo stamping tubes keep the villagers moving as one body.',
  },
  {
    id: 'aboriginal-clapsticks',
    name: 'Aboriginal Clapsticks',
    origin: 'Australia',
    tradition: 'Songline · ceremonial',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 400, min: 360, max: 480 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
      HH: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
    },
    defaultKit: 'gamelan',
    country: 'AU',
    region: 'central-asian-pacific',
    tags: ['bilma', 'clapsticks', 'aboriginal', 'songline'],
    instruments: ['bilma', 'yidaki', 'voice'],
    swingable: false,
    story: 'Bilma eucalyptus clapsticks hold the structural timeline for Aboriginal song. A generalised public-domain pulse — ceremonial songline rhythms remain culturally restricted.',
  },
  {
    id: 'aboriginal-yidaki',
    name: 'Yidaki Drone + Clapsticks',
    origin: 'Australia · Arnhem Land',
    tradition: 'Yolngu yidaki · Songline',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 360, min: 320, max: 440 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0],
      SN: [0, 2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: 'gamelan',
    country: 'AU',
    region: 'central-asian-pacific',
    tags: ['yidaki', 'didgeridoo', 'circular-breathing', 'yolngu'],
    instruments: ['yidaki', 'bilma', 'voice'],
    swingable: false,
    story: 'The yidaki never stops — circular breathing turns a drone into rhythm through tongue pops, vocal harmonics and the whispered pulse of breath transitions.',
    relatedIds: ['aboriginal-clapsticks'],
  },
  {
    id: 'filipino-kulintang',
    name: 'Filipino Kulintang',
    origin: 'Philippines · Mindanao',
    tradition: 'Maguindanaon kulintang',
    genre: 'classical',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 440, min: 400, max: 520 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 0, 2],
      SN: [0, 2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 2, 0, 2, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'gamelan',
    country: 'PH',
    region: 'central-asian-pacific',
    tags: ['kulintang', 'mindanao', 'gong-chime', 'maguindanao'],
    instruments: ['kulintang', 'agung', 'dabakan'],
    swingable: false,
    story: 'A row of eight tuned bronze kettle-gongs across the southern Philippines. The kulintang cycle interlocks with agung gongs and dabakan drum like a Pacific gamelan.',
  },
  {
    id: 'powwow-round-dance',
    name: 'Powwow Round Dance',
    origin: 'North America · Intertribal',
    tradition: 'Round dance · social',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 400, min: 360, max: 440 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: 'frameDrum',
    region: 'central-asian-pacific',
    tags: ['powwow', 'round-dance', 'indigenous', 'intertribal'],
    instruments: ['hand-drum', 'voice', 'rattle'],
    swingable: false,
    story: 'An intertribal social dance — a circle of linked hands moves sideways to a steady heartbeat hand-drum. All are welcome to join.',
  },
];
