import type { Pattern } from '../types';

export const CUBA_AFROCARIBBEAN_PATTERNS: Pattern[] = [
  {
    id: 'son-clave',
    name: 'Son Clave 3-2',
    origin: 'Cuba',
    tradition: 'Afro-Cuban',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 380, min: 280, max: 800 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1],
    },
    defaultKit: '727',
    region: 'cuba-afrocaribbean',
    country: 'CU',
    tags: ['clave', 'foundation', 'salsa'],
    instruments: ['claves', 'congas', 'bongos'],
    swingable: true,
    story: 'The spine of every Cuban son, salsa, and half of Latin music since 1800.',
    relatedIds: ['bossa-nova', 'samba-partido-alto', 'funk-second-line', 'bomba-sica', 'agbekor'],
  },
  {
    id: 'bembe',
    name: 'Bembé',
    origin: 'Cuba · Yoruba diaspora',
    tradition: 'Sacred bell pattern',
    genre: 'devotional',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 230, min: 180, max: 300 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    region: 'cuba-afrocaribbean',
    country: 'CU',
    tags: ['bell', 'sacred', 'afrobeat-ancestor'],
    instruments: ['atoke', 'congas', 'bata'],
    swingable: false,
    story: 'The 12/8 bell that underlies bembé, abakuá, and half the West African diaspora.',
    relatedIds: ['bembe-68', 'agbekor', 'atsiagbekor', 'buleria', 'ijexa'],
  },
  {
    id: 'rumba-clave-3-2',
    name: 'Rumba Clave 3-2',
    origin: 'Cuba',
    tradition: 'Afro-Cuban rumba',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 400, min: 320, max: 560 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['clave', 'rumba', 'foundation'],
    instruments: ['claves', 'congas', 'palitos'],
    swingable: true,
    story: "Rumba's clave — the three-side's last stroke comes one 16th later than son. That delay is everything.",
    relatedIds: ['son-clave', 'guaguanco', 'samba-partido-alto'],
  },
  {
    id: 'bolero',
    name: 'Bolero Cubano',
    origin: 'Cuba · Santiago',
    tradition: 'Afro-Cuban ballad',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 640, min: 400, max: 880 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 1, 0, 2, 0, 1, 0, 2, 0, 1, 0, 2, 0, 1, 0],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['romantic', 'slow', 'trova'],
    instruments: ['guitar', 'bongo', 'maracas'],
    swingable: false,
    story: 'The Cuban ballad — slow, tender, and built around the trova tradition of moonlit guitar serenades.',
  },
  {
    id: 'cha-cha',
    name: 'Cha-Cha-Chá',
    origin: 'Cuba',
    tradition: 'Dance hall',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 512, min: 400, max: 640 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['dance', 'ballroom', 'popular'],
    instruments: ['güiro', 'cha-cha bell', 'congas'],
    swingable: false,
    story: 'Violinist Enrique Jorrín slowed the mambo down so everybody could dance. The name comes from dancers\' shuffling feet.',
  },
  {
    id: 'mambo',
    name: 'Mambo',
    origin: 'Cuba · Havana',
    tradition: 'Dance hall / salsa',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 760, min: 640, max: 920 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 1, 0, 2, 0, 1, 0, 0, 1, 2, 0, 1, 0, 1, 0],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['salsa', 'big-band', 'dance'],
    instruments: ['timbales', 'mambo bell', 'conga'],
    swingable: true,
    story: 'The climax section of any salsa arrangement — when the band opens up and the mambo bell takes over.',
    relatedIds: ['son-clave', 'soukous', 'mozambique'],
  },
  {
    id: 'guaguanco',
    name: 'Guaguancó',
    origin: 'Cuba · Havana / Matanzas',
    tradition: 'Rumba',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 432, min: 360, max: 520 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 1, 0, 0, 0, 2, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['rumba', 'folk', 'afro-cuban', 'palitos'],
    instruments: ['conga', 'claves', 'palitos'],
    swingable: false,
    story: 'The most popular form of rumba — a secular ritual born in Havana courtyards, where a male dancer pursues a female dancer in stylized courtship.',
    relatedIds: ['rumba-clave-3-2', 'rumba-columbia', 'samba-de-roda', 'yambu'],
  },
  {
    id: 'rumba-columbia',
    name: 'Rumba Columbia',
    origin: 'Cuba · Matanzas',
    tradition: 'Rumba (fast 6/8)',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 280, min: 240, max: 340 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
      SN: [0, 1, 0, 0, 0, 2, 0, 1, 0, 0, 0, 2],
      HH: [2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 0, 2],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['rumba', '12-8', 'abakua', 'virtuosic'],
    instruments: ['quinto', 'guataca', 'conga'],
    swingable: false,
    story: 'The fastest, most virtuosic rumba — a solo male dance of acrobatic and sometimes dangerous moves, rooted in Abakuá sacred rhythms from Calabar.',
    relatedIds: ['bembe', 'bembe-68', 'bata-shango', 'agbekor'],
  },
  {
    id: 'comparsa',
    name: 'Comparsa',
    origin: 'Cuba · Santiago',
    tradition: 'Carnival procession',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 500, min: 440, max: 560 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0],
      HH: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['carnival', 'procession', 'street'],
    instruments: ['sartén', 'cowbell', 'conga'],
    swingable: false,
    story: 'The costumed carnival processions of Santiago — frying pans mounted on blocks, cowbells, and a river of drums rolling through the streets.',
  },
  {
    id: 'cascara',
    name: 'Cáscara',
    origin: 'Cuba',
    tradition: 'Timbale shell pattern',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 220, min: 160, max: 320 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 1, 2],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['timbale', 'salsa', 'shell', 'verse'],
    instruments: ['timbales', 'palitos', 'cowbell'],
    swingable: true,
    story: 'Played on the side of a timbal — slinky, sideways, reserved for mambo verses before the montuno opens up.',
    relatedIds: ['mambo'],
  },
  {
    id: 'son-clave-2-3',
    name: 'Son Clave 2-3',
    origin: 'Cuba',
    tradition: 'Afro-Cuban (reverse clave)',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 720, min: 480, max: 960 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['clave', 'foundation', 'salsa', 'reverse'],
    instruments: ['claves', 'congas', 'bongos'],
    swingable: true,
    story: 'Son clave flipped — two side first, then three. Most Cuban charts start here because the melodic phrasing anticipates the "3" resolution.',
    relatedIds: ['son-clave'],
  },
  {
    id: 'danzon',
    name: 'Danzón',
    origin: 'Cuba · Matanzas',
    tradition: 'Cuban classical ballroom',
    genre: 'classical',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 440, min: 360, max: 520 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [2, 0, 2, 2, 0, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0],
      HH: [2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['cinquillo', 'danza', 'ballroom', 'habanera'],
    instruments: ['timbales', 'güiro', 'piano'],
    swingable: false,
    story: 'Cuba\'s national dance in 1879 — a ballroom form built on the cinquillo (3+3+2 sub-divisional cell). The timbale\'s baqueteo pattern is the rhythmic spine.',
    relatedIds: ['son-clave', 'bolero', 'milonga-flamenca'],
  },
  {
    id: 'songo',
    name: 'Songo',
    origin: 'Cuba · Havana',
    tradition: 'Los Van Van / Changuito',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 448, min: 360, max: 520 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['los-van-van', 'changuito', 'drum-set', 'modern'],
    instruments: ['drum kit', 'timbales', 'congas'],
    swingable: true,
    story: 'Changuito invented songo with Los Van Van in the 1970s — the first Cuban rhythm conceived for the drum set, fusing rumba, son, funk and jazz drumming.',
    relatedIds: ['timba', 'mambo'],
  },
  {
    id: 'timba',
    name: 'Timba',
    origin: 'Cuba',
    tradition: 'Modern Cuban dance',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 640, min: 560, max: 760 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['modern', 'gears', 'funk-influenced', 'los-van-van'],
    instruments: ['timbales', 'congas', 'kick drum'],
    swingable: true,
    story: 'NG La Banda, Los Van Van, Paulito FG — aggressive, funk-influenced, gear-shifting evolution of salsa. The kick drum arrives and the music gets denser.',
    relatedIds: ['songo', 'mambo'],
  },
  {
    id: 'yambu',
    name: 'Yambú',
    origin: 'Cuba · Havana / Matanzas',
    tradition: 'Slow rumba',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 300, min: 240, max: 340 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['rumba', 'slow', 'cajón', 'elders'],
    instruments: ['cajones', 'claves', 'palitos'],
    swingable: false,
    story: 'The oldest and slowest rumba — originally played on wooden shipping-crate cajones, imitating the movements of elderly people. No vacunao, no hurry.',
    relatedIds: ['guaguanco', 'rumba-columbia'],
  },
  {
    id: 'pilon',
    name: 'Pilón',
    origin: 'Cuba · Santiago',
    tradition: '1960s Cuban dance craze',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 520, min: 480, max: 580 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2],
      HH: [2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['santiago', 'enrique-bonne', 'pacho-alonso', '60s-dance'],
    instruments: ['paila', 'güiro', 'conga'],
    swingable: false,
    story: 'Enrique Bonne and Pacho Alonso built a dance craze around the pilón — the mortar used to grind sugar cane. The choreography imitates the pounding motion.',
  },
  {
    id: 'changui',
    name: 'Changüí',
    origin: 'Cuba · Guantánamo',
    tradition: 'Pre-son rural music',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 460, min: 360, max: 520 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['rural', 'pre-son', 'bongó', 'marímbula'],
    instruments: ['bongó', 'marímbula', 'tres'],
    swingable: true,
    story: 'The father of son. In the eastern sugar plantations of Guantánamo the bongó was the timeline — wilder, more improvisatory, more West African than the son that would follow.',
    relatedIds: ['son-clave', 'soukous'],
  },
  {
    id: 'mozambique',
    name: 'Mozambique',
    origin: 'Cuba · Havana',
    tradition: 'Pello el Afrokán carnival',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 460, min: 400, max: 520 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 2, 0, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['carnival', 'pello-afrokan', 'comparsa', 'eddie-palmieri'],
    instruments: ['bell', 'conga', 'bombo'],
    swingable: false,
    story: 'Pedro "Pello el Afrokán" Izquierdo invented the mozambique for Havana\'s 1960s carnival. It crossed the straits to Eddie Palmieri and lit up New York salsa.',
    relatedIds: ['comparsa', 'funk-second-line'],
  },
  {
    id: 'bomba-sica',
    name: 'Bomba Sicá',
    origin: 'Puerto Rico · Loíza / Ponce',
    tradition: 'Afro-Puerto Rican bomba',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 480, min: 400, max: 560 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 2],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'PR',
    region: 'cuba-afrocaribbean',
    tags: ['bomba', 'tresillo', 'dancer-drummer', 'loíza'],
    instruments: ['buleador', 'subidor', 'cuá'],
    swingable: false,
    story: 'The most widespread bomba style, built on the 3-3-2 tresillo. In bomba the dancer leads and the subidor drummer must follow — the conversation is the music.',
    relatedIds: ['son-clave', 'rumba-flamenca', 'kuduro'],
  },
  {
    id: 'bomba-holande',
    name: 'Bomba Holandé',
    origin: 'Puerto Rico · Loíza',
    tradition: 'Afro-Puerto Rican bomba (6/8)',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 95, min: 80, max: 110 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
      SN: [0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0],
      HH: [2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 0, 2],
    },
    defaultKit: '727',
    country: 'PR',
    region: 'cuba-afrocaribbean',
    tags: ['bomba', 'compound', '6-8', 'afro-puerto-rican'],
    instruments: ['buleador', 'subidor', 'cuá'],
    swingable: false,
    story: 'The 6/8 bomba that links Puerto Rican tradition back to West Africa. "Holandé" may nod to Dutch colonial traders — the rhythm sways like ocean swells.',
    relatedIds: ['bomba-sica', 'bembe', 'bembe-68', 'agbekor'],
  },
  {
    id: 'plena',
    name: 'Plena',
    origin: 'Puerto Rico · Ponce',
    tradition: 'Pandero ensemble (the sung newspaper)',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 500, min: 440, max: 560 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [0, 1, 0, 1, 2, 0, 0, 1, 0, 1, 2, 0, 0, 1, 0, 1],
    },
    defaultKit: '727',
    country: 'PR',
    region: 'cuba-afrocaribbean',
    tags: ['plena', 'pandero', 'ponce', 'social-commentary'],
    instruments: ['seguidor', 'segundo', 'requinto'],
    swingable: false,
    story: '"El periódico cantado" — the sung newspaper. Three hand-held panderos trade rhythms over Ponce\'s working-class streets, narrating whatever happened this week.',
  },
  {
    id: 'merengue',
    name: 'Merengue',
    origin: 'Dominican Republic',
    tradition: 'Dominican national dance',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 600, min: 520, max: 680 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2],
    },
    defaultKit: '727',
    country: 'DO',
    region: 'cuba-afrocaribbean',
    tags: ['merengue', 'tambora', 'güira', 'dominican'],
    instruments: ['tambora', 'güira', 'accordion'],
    swingable: false,
    story: 'The national rhythm of the Dominican Republic — tambora and güira against an accordion. Trujillo promoted it as a tool of the state; the country made it a birthright.',
    relatedIds: ['bachata', 'kompa'],
  },
  {
    id: 'charanga-francesa',
    name: 'Charanga',
    origin: 'Cuba · Havana',
    tradition: 'Charanga francesa (flute-and-violin orchestra)',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 460, min: 400, max: 540 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0],
      HH: [2, 0, 2, 1, 2, 0, 2, 1, 2, 0, 2, 1, 2, 0, 2, 1],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['charanga', 'danzon-lineage', 'flute', 'güiro', 'elegant'],
    instruments: ['güiro', 'timbales', 'flute', 'violin'],
    swingable: true,
    story: 'The charanga francesa — wooden flute, violins, piano, bass, timbales and güiro — was the elegant Cuban orchestra that birthed danzón, cha-cha and pachanga. Enrique Jorrín\'s Orquesta América shaped mid-century Havana dancing.',
    relatedIds: ['cha-cha', 'danzon'],
  },
  {
    id: 'danzon-cha',
    name: 'Danzón-Chá',
    origin: 'Cuba · Havana',
    tradition: 'Danzón third-section chá',
    genre: 'classical',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 420, min: 360, max: 480 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [2, 0, 2, 2, 0, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0],
      HH: [2, 0, 1, 0, 2, 0, 2, 0, 2, 0, 1, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['danzon', 'cinquillo', 'ballroom', 'charanga'],
    instruments: ['timbales', 'güiro', 'piano', 'flute'],
    swingable: false,
    story: 'The slower third section that opens out of a classic danzón — the baqueteo softens and the dancers step wider. The bridge between Cuba\'s Belle Époque ballroom and Jorrín\'s cha-cha-chá.',
    relatedIds: ['danzon', 'cha-cha', 'charanga-francesa'],
  },
  {
    id: 'mambo-rumba',
    name: 'Mambo-Rumba',
    origin: 'Cuba · Havana',
    tradition: 'Mambo-rumba fusion',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 540, min: 480, max: 640 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2],
      SN: [0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 1, 2, 0, 2, 1, 2, 0, 2, 1, 2, 0, 2, 1],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['mambo', 'rumba', 'fusion', 'palladium'],
    instruments: ['timbales', 'congas', 'mambo bell'],
    swingable: true,
    story: 'When the Palladium-era big bands brought guaguancó into the mambo arrangement — rumba clave sharpening the mambo\'s attack while the bell section churns on underneath.',
    relatedIds: ['mambo', 'guaguanco', 'rumba-clave-3-2'],
  },
  {
    id: 'son-montuno',
    name: 'Son Montuno',
    origin: 'Cuba · Oriente / Havana',
    tradition: 'Arsenio Rodríguez conjunto',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 420, min: 340, max: 500 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2],
      SN: [0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 1],
      HH: [2, 0, 2, 1, 2, 0, 2, 1, 2, 0, 2, 1, 2, 0, 2, 1],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['son', 'montuno', 'arsenio-rodriguez', 'salsa-root'],
    instruments: ['tres', 'congas', 'bongó', 'piano'],
    swingable: true,
    story: 'Arsenio Rodríguez electrified son in the 1940s — added conga, piano, a trumpet section. Montuno is the open call-and-response section where the band gears up. Everything that became salsa passes through here.',
    relatedIds: ['son-clave', 'son-clave-2-3', 'mambo', 'changui'],
  },
  {
    id: 'afro-68',
    name: 'Afro 6/8',
    origin: 'Cuba · Havana',
    tradition: 'Modern Afro-Cuban 6/8',
    genre: 'popular',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 270, min: 220, max: 340 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
      SN: [0, 0, 2, 0, 2, 0, 0, 1, 2, 0, 1, 2],
      HH: [2, 0, 2, 1, 2, 1, 2, 0, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['afro', '6-8', 'bembe-derived', 'drum-set'],
    instruments: ['drum kit', 'conga', 'cowbell'],
    swingable: false,
    story: 'The modern ensemble\'s take on the Yoruba bell — bembé translated to drum kit and bass for Afro-Cuban jazz and timba\'s 6/8 passages. Chucho Valdés, Irakere, Gonzalo Rubalcaba live in this meter.',
    relatedIds: ['bembe', 'bembe-68', 'rumba-columbia'],
  },
  {
    id: 'iyesa',
    name: 'Iyesá',
    origin: 'Cuba · Matanzas',
    tradition: 'Yoruba-Cuban ritual',
    genre: 'ceremonial',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 250, min: 200, max: 300 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
      SN: [0, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0, 2],
      HH: [2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 0, 2],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['yoruba', 'matanzas', 'ritual', 'drums-of-iron'],
    instruments: ['iyesá drums', 'agogô', 'chekeré'],
    swingable: false,
    story: 'The Iyesá are Yoruba descendants in Matanzas whose ritual drums preserve Ijesha regional rhythms from Nigeria. Four single-headed drums tuned by cords, an iron bell on top — a tradition older than recorded Cuba.',
    relatedIds: ['bembe', 'bata-shango', 'ijexa'],
  },
  {
    id: 'abakua',
    name: 'Abakuá',
    origin: 'Cuba · Havana / Matanzas',
    tradition: 'Efik/Ejagham secret society',
    genre: 'ceremonial',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 240, min: 200, max: 300 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0],
      HH: [2, 0, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['abakua', 'secret-society', 'cross-river', 'ekue', 'nyankue'],
    instruments: ['bonkó enchemiyá', 'obi-apá', 'ekón'],
    swingable: false,
    story: 'The only African secret society re-established in the Americas — founded Havana 1836 from the Efik/Ejagham Ekpe. The bonkó enchemiyá lead drum speaks over obi-apá shoulder drums; the sacred ekue friction drum stays hidden.',
    relatedIds: ['rumba-columbia', 'bembe', 'iyesa'],
  },
  {
    id: 'palo-kongo',
    name: 'Palo / Yuka',
    origin: 'Cuba · Pinar del Río',
    tradition: 'Bantu-Kongo secular drumming',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 380, min: 320, max: 440 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 2, 2, 0, 0, 2, 0, 2, 0, 2, 2],
      HH: [2, 0, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 2, 0, 2],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['palo', 'yuka', 'kongo', 'bantu', 'makuta', 'nganga'],
    instruments: ['caja', 'mula', 'cachimbo'],
    swingable: false,
    story: 'The Kongo-descended yuka drums of western Cuba — "yuka" means "to beat" in Bantu. Paired with the makuta, they underpin Las Reglas de Congo. Trance-inducing, driving, repetitive — the aesthetic of Central African ritual.',
    relatedIds: ['bembe', 'abakua', 'samba-de-roda'],
  },
  {
    id: 'guaguanco-habanero',
    name: 'Guaguancó Habanero',
    origin: 'Cuba · Havana',
    tradition: 'Havana-style rumba',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 460, min: 380, max: 540 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['guaguanco', 'havana', 'rumba', 'solares', 'yoruba-andabo'],
    instruments: ['tumbadora', 'segundo', 'quinto', 'palitos'],
    swingable: false,
    story: 'The Havana style of guaguancó — faster and more volatile than Matanzas, born in the solares (tenement courtyards) of the capital. Los Papines and Yoruba Andabo define the lineage.',
    relatedIds: ['guaguanco', 'guaguanco-matanzas', 'rumba-clave-3-2'],
  },
  {
    id: 'guaguanco-matanzas',
    name: 'Guaguancó Matancero',
    origin: 'Cuba · Matanzas',
    tradition: 'Matanzas-style rumba',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 380, min: 320, max: 440 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0],
      SN: [0, 0, 0, 2, 0, 0, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0],
      HH: [2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 2, 0, 2, 0, 2, 2],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['guaguanco', 'matanzas', 'rumba', 'tres-golpes', 'traditional'],
    instruments: ['tumbadora', 'segundo', 'quinto', 'palitos'],
    swingable: false,
    story: 'The Matanzas style of guaguancó — slower, more ritualistic, drier timbre on cajones. Los Muñequitos de Matanzas carry this lineage where Havana players push tempo, Matanceros hold the space.',
    relatedIds: ['guaguanco', 'rumba-clave-3-2', 'yambu'],
  },
];
