import type { Pattern } from '../types';

export const CUBA_AFROCARIBBEAN_PATTERNS: Pattern[] = [
  {
    id: 'son-clave',
    name: 'Son Clave 3-2',
    origin: 'Cuba',
    tradition: 'Afro-Cuban',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 380, min: 280, max: 800 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1],
    },
    defaultKit: '727',
    region: 'cuba-afrocaribbean',
    country: 'CU',
    tags: ['clave', 'foundation', 'salsa'],
    instruments: ['claves', 'congas', 'bongos'],
    swingable: true,
    story: 'The spine of every Cuban son, salsa, and half of Latin music since 1800.',
  },
  {
    id: 'bembe',
    name: 'Bembé',
    origin: 'Cuba · Yoruba diaspora',
    tradition: 'Sacred bell pattern',
    genre: 'devotional',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 230, min: 180, max: 300 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    region: 'cuba-afrocaribbean',
    country: 'CU',
    tags: ['bell', 'sacred', 'afrobeat-ancestor'],
    instruments: ['atoke', 'congas', 'bata'],
    swingable: false,
    story: 'The 12/8 bell that underlies bembé, abakuá, and half the West African diaspora.',
  },
  {
    id: 'rumba-clave-3-2',
    name: 'Rumba Clave 3-2',
    origin: 'Cuba',
    tradition: 'Afro-Cuban rumba',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 400, min: 320, max: 560 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['clave', 'rumba', 'foundation'],
    instruments: ['claves', 'congas', 'palitos'],
    swingable: true,
    story: "Rumba's clave — the three-side's last stroke comes one 16th later than son. That delay is everything.",
    relatedIds: ['son-clave', 'guaguanco'],
  },
  {
    id: 'bolero',
    name: 'Bolero Cubano',
    origin: 'Cuba · Santiago',
    tradition: 'Afro-Cuban ballad',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 160, min: 100, max: 220 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 1, 0, 2, 0, 1, 0, 2, 0, 1, 0, 2, 0, 1, 0],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['romantic', 'slow', 'trova'],
    instruments: ['guitar', 'bongo', 'maracas'],
    swingable: false,
    story: 'The Cuban ballad — slow, tender, and built around the trova tradition of moonlit guitar serenades.',
  },
  {
    id: 'cha-cha',
    name: 'Cha-Cha-Chá',
    origin: 'Cuba',
    tradition: 'Dance hall',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 128, min: 100, max: 160 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['dance', 'ballroom', 'popular'],
    instruments: ['güiro', 'cha-cha bell', 'congas'],
    swingable: false,
    story: 'Violinist Enrique Jorrín slowed the mambo down so everybody could dance. The name comes from dancers\' shuffling feet.',
  },
  {
    id: 'mambo',
    name: 'Mambo',
    origin: 'Cuba · Havana',
    tradition: 'Dance hall / salsa',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 190, min: 160, max: 230 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 1, 0, 2, 0, 1, 0, 0, 1, 2, 0, 1, 0, 1, 0],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['salsa', 'big-band', 'dance'],
    instruments: ['timbales', 'mambo bell', 'conga'],
    swingable: true,
    story: 'The climax section of any salsa arrangement — when the band opens up and the mambo bell takes over.',
    relatedIds: ['son-clave'],
  },
  {
    id: 'guaguanco',
    name: 'Guaguancó',
    origin: 'Cuba · Havana / Matanzas',
    tradition: 'Rumba',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 108, min: 90, max: 130 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 1, 0, 0, 0, 2, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['rumba', 'folk', 'afro-cuban', 'palitos'],
    instruments: ['conga', 'claves', 'palitos'],
    swingable: false,
    story: 'The most popular form of rumba — a secular ritual born in Havana courtyards, where a male dancer pursues a female dancer in stylized courtship.',
    relatedIds: ['rumba-clave-3-2', 'rumba-columbia'],
  },
  {
    id: 'rumba-columbia',
    name: 'Rumba Columbia',
    origin: 'Cuba · Matanzas',
    tradition: 'Rumba (fast 6/8)',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 280, min: 240, max: 340 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
      SN: [0, 1, 0, 0, 0, 2, 0, 1, 0, 0, 0, 2],
      HH: [2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 0, 2],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['rumba', '12-8', 'abakua', 'virtuosic'],
    instruments: ['quinto', 'guataca', 'conga'],
    swingable: false,
    story: 'The fastest, most virtuosic rumba — a solo male dance of acrobatic and sometimes dangerous moves, rooted in Abakuá sacred rhythms from Calabar.',
    relatedIds: ['bembe'],
  },
  {
    id: 'comparsa',
    name: 'Comparsa',
    origin: 'Cuba · Santiago',
    tradition: 'Carnival procession',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 125, min: 110, max: 140 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0],
      HH: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['carnival', 'procession', 'street'],
    instruments: ['sartén', 'cowbell', 'conga'],
    swingable: false,
    story: 'The costumed carnival processions of Santiago — frying pans mounted on blocks, cowbells, and a river of drums rolling through the streets.',
  },
  {
    id: 'cascara',
    name: 'Cáscara',
    origin: 'Cuba',
    tradition: 'Timbale shell pattern',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 220, min: 160, max: 320 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 1, 2],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['timbale', 'salsa', 'shell', 'verse'],
    instruments: ['timbales', 'palitos', 'cowbell'],
    swingable: true,
    story: 'Played on the side of a timbal — slinky, sideways, reserved for mambo verses before the montuno opens up.',
    relatedIds: ['mambo'],
  },
];
