import type { Pattern } from '../types';

export const EAST_ASIA_PATTERNS: Pattern[] = [
  {
    id: 'taiko-base',
    name: 'Taiko Jiuchi',
    origin: 'Japan',
    tradition: 'Kumi-daiko',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 130, min: 80, max: 180 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 1, 2, 0, 0, 1, 2, 0, 0, 1, 2, 0, 0, 1, 2],
      HH: [2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
    },
    defaultKit: '808',
    country: 'JP',
    region: 'east-asia',
    tags: ['taiko', 'matsuri', 'japanese', 'festival'],
    instruments: ['odaiko', 'shime-daiko', 'chappa'],
    swingable: false,
    story: 'The "don-ka don-ka" jiuchi that underlies nearly every matsuri festival piece — odaiko center hits, shime rim answers, the heartbeat of Japanese ensemble drumming.',
  },
  {
    id: 'samulnori',
    name: 'Samulnori · Jajinmori',
    origin: 'Korea',
    tradition: 'Four-instrument percussion',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 160, min: 140, max: 200 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2],
      HH: [2, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1],
      OH: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    defaultKit: 'gamelan',
    country: 'KR',
    region: 'east-asia',
    tags: ['korean', 'changdan', 'pungmul', 'percussion'],
    instruments: ['janggu', 'kkwaenggwari', 'buk', 'jing'],
    swingable: false,
    story: 'Kim Duk-soo\'s 1978 reinvention of outdoor pungmul drumming for the concert stage — small gong leads, hourglass janggu answers, barrel buk and great jing ground the cycle.',
  },
];
