import type { Pattern } from '../types';

export const EAST_ASIA_PATTERNS: Pattern[] = [
  {
    id: 'taiko-base',
    name: 'Taiko Jiuchi',
    origin: 'Japan',
    tradition: 'Kumi-daiko',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 520, min: 320, max: 720 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 1, 2, 0, 0, 1, 2, 0, 0, 1, 2, 0, 0, 1, 2],
      HH: [2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
    },
    defaultKit: '808',
    country: 'JP',
    region: 'east-asia',
    tags: ['taiko', 'matsuri', 'japanese', 'festival'],
    instruments: ['odaiko', 'shime-daiko', 'chappa'],
    swingable: false,
    story: 'The "don-ka don-ka" jiuchi that underlies nearly every matsuri festival piece — odaiko center hits, shime rim answers, the heartbeat of Japanese ensemble drumming.',
  },
  {
    id: 'samulnori',
    name: 'Samulnori · Jajinmori',
    origin: 'Korea',
    tradition: 'Four-instrument percussion',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 160, min: 140, max: 200 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2],
      HH: [2, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1],
      OH: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    defaultKit: 'gamelan',
    country: 'KR',
    region: 'east-asia',
    tags: ['korean', 'changdan', 'pungmul', 'percussion'],
    instruments: ['janggu', 'kkwaenggwari', 'buk', 'jing'],
    swingable: false,
    story: 'Kim Duk-soo\'s 1978 reinvention of outdoor pungmul drumming for the concert stage — small gong leads, hourglass janggu answers, barrel buk and great jing ground the cycle.',
  },
  {
    id: 'taiko-matsuri',
    name: 'Taiko · Matsuri',
    origin: 'Japan',
    tradition: 'Festival kumi-daiko',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 560, min: 400, max: 720 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
      HH: [2, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1],
    },
    defaultKit: '808',
    country: 'JP',
    region: 'east-asia',
    tags: ['taiko', 'matsuri', 'festival', 'odaiko'],
    instruments: ['odaiko', 'shime-daiko', 'kane'],
    swingable: false,
    story: 'The quintessential festival rhythm: "DON doko don DON" — heavy accents on the odaiko creating the joyful, driving feel that carries floats through streets during matsuri.',
    relatedIds: ['taiko-base', 'yatai-bayashi'],
  },
  {
    id: 'yatai-bayashi',
    name: 'Yatai-bayashi',
    origin: 'Japan · Chichibu',
    tradition: 'Festival float drumming',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 480, min: 360, max: 640 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
      SN: [0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
      HH: [2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2],
    },
    defaultKit: '808',
    country: 'JP',
    region: 'east-asia',
    tags: ['taiko', 'chichibu', 'float', 'endurance'],
    instruments: ['odaiko', 'shime-daiko', 'shinobue'],
    swingable: false,
    story: 'The relentless float-drumming rhythm of Chichibu\'s night festival — traditionally played lying on your back under the yatai cart, arms pounding overhead. Endurance as devotion.',
    relatedIds: ['taiko-matsuri'],
  },
  {
    id: 'gutgeori',
    name: 'Gutgeori Changdan',
    origin: 'Korea',
    tradition: 'Folk / shaman (gut)',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 80, min: 60, max: 110 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 0, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0],
      OH: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    defaultKit: 'gamelan',
    country: 'KR',
    region: 'east-asia',
    tags: ['korean', 'changdan', 'folk', 'janggu'],
    instruments: ['janggu', 'buk', 'kkwaenggwari'],
    swingable: false,
    story: 'A moderate 12/8 changdan — the most common folk cycle, swaying and dance-like. Vocalized "deong-gi-deok kung deo-reo-reo-reo" — the rhythmic DNA of countless Korean folk songs.',
    relatedIds: ['samulnori', 'semachi'],
  },
  {
    id: 'semachi',
    name: 'Semachi Changdan',
    origin: 'Korea',
    tradition: 'Folk / shaman',
    genre: 'folk-dance',
    timeSig: '9/8',
    grouping: [3, 3, 3],
    stepUnit: 8,
    steps: 9,
    bpm: { default: 120, min: 100, max: 160 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 0, 2],
      HH: [2, 0, 1, 0, 1, 1, 0, 1, 1],
    },
    defaultKit: 'gamelan',
    country: 'KR',
    region: 'east-asia',
    tags: ['korean', 'changdan', 'shaman', '9/8'],
    instruments: ['janggu', 'kkwaenggwari'],
    swingable: false,
    story: 'A 9/8 changdan — three groups of three, lighter and more buoyant than gutgeori. Central to shaman music and folk songs with spiritual themes.',
    relatedIds: ['gutgeori', 'samulnori'],
  },
  {
    id: 'hwimori',
    name: 'Hwimori Changdan',
    origin: 'Korea',
    tradition: 'Pansori / sanjo climax',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [2, 2, 2, 2],
    stepUnit: 8,
    steps: 8,
    bpm: { default: 190, min: 160, max: 230 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 2, 2, 0, 2, 2],
      SN: [2, 0, 2, 0, 2, 0, 2, 0],
      HH: [2, 0, 1, 1, 2, 0, 1, 1],
      OH: [2, 0, 0, 0, 0, 0, 0, 0],
    },
    defaultKit: 'gamelan',
    country: 'KR',
    region: 'east-asia',
    tags: ['korean', 'changdan', 'pansori', 'climax', 'fast'],
    instruments: ['buk', 'janggu', 'kkwaenggwari'],
    swingable: false,
    story: '"Whirling" — the fastest standard changdan, used for climactic passages of pansori and sanjo. Overwhelming rhythmic intensity as the gosu drummer drives the singer to catharsis.',
    relatedIds: ['samulnori', 'gutgeori'],
  },
  {
    id: 'lion-dance',
    name: 'Lion Dance',
    origin: 'China · Cantonese',
    tradition: 'Martial-arts lion dance',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 520, min: 400, max: 680 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 1, 0, 2, 0, 1, 0, 2, 0, 1, 0, 2, 0, 1, 0],
      SN: [0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2],
      HH: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    defaultKit: 'gamelan',
    country: 'CN',
    region: 'east-asia',
    tags: ['chinese', 'lion-dance', 'martial-arts', 'new-year'],
    instruments: ['datanggu', 'daluo', 'xiaobo'],
    swingable: false,
    story: 'The walking-prowling pattern: the lion follows the drum. Big tanggu drum leads, gong and cymbal answer — every martial arts school has its own vocabulary, but the head-swaying rhythm is universal.',
  },
  {
    id: 'bon-odori',
    name: 'Bon Odori',
    origin: 'Japan',
    tradition: 'Obon community dance',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 440, min: 360, max: 560 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 1, 0, 0, 2, 0, 0, 0, 2, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '808',
    country: 'JP',
    region: 'east-asia',
    tags: ['taiko', 'obon', 'folk', 'community', 'ancestral'],
    instruments: ['odaiko', 'shime-daiko', 'shamisen', 'shinobue'],
    swingable: false,
    story: 'The Obon dance rhythm — a taiko drummer on a raised yagura scaffold at the circle\'s center, providing the heartbeat for a community welcoming ancestral spirits home. Insistent, hypnotic, built to sustain hours.',
    relatedIds: ['taiko-base', 'taiko-matsuri'],
  },
  {
    id: 'jingju-opera',
    name: 'Jingju · Opera Entrance',
    origin: 'China · Beijing',
    tradition: 'Peking opera percussion',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 400, min: 280, max: 560 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
      CP: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
    },
    defaultKit: 'gamelan',
    country: 'CN',
    region: 'east-asia',
    tags: ['chinese', 'opera', 'jingju', 'command-language'],
    instruments: ['bangu', 'paiban', 'daluo', 'xiaoluo'],
    swingable: false,
    story: 'The bangu drum-master conducts the entire opera — paiban clapper marks the beat, daluo gong punctuates entrances, xiaoluo answers. Every pattern cues a specific dramatic action. Percussion as command language.',
    relatedIds: ['lion-dance'],
  },
];
