import type { Pattern } from '../types';

export const ELECTRONIC_WESTERN_PATTERNS: Pattern[] = [
  {
    id: 'boom-bap',
    name: 'Boom Bap',
    origin: 'USA · New York',
    tradition: 'Golden-era hip-hop',
    genre: 'hip-hop',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 90, min: 82, max: 98 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '808',
    country: 'US',
    region: 'electronic-western',
    tags: ['hip-hop', 'sampler', 'golden-era', 'sp-1200'],
    instruments: ['MPC', 'SP-1200', 'vinyl'],
    swingable: true,
    story: 'The crunchy, sampled drum break of 1990s New York hip-hop — DJ Premier, Pete Rock, and the SP-1200. Kick, snare, and swung sixteenths on a chopped loop.',
  },
  {
    id: 'four-on-the-floor',
    name: 'Four on the Floor',
    origin: 'USA · Chicago / Detroit',
    tradition: 'House / techno',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 124, min: 110, max: 140 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    defaultKit: '909',
    country: 'US',
    region: 'electronic-western',
    tags: ['house', 'techno', '909', 'foundation'],
    instruments: ['TR-909', 'clap', 'hi-hat'],
    swingable: false,
    story: 'Every 909 house record ever — four straight kicks, offbeat hats, clap on 2 and 4. The metronome-to-club pipeline in one bar.',
  },
];
