import type { Pattern } from '../types';

export const ELECTRONIC_WESTERN_PATTERNS: Pattern[] = [
  // ============================================================
  // Existing
  // ============================================================
  {
    id: 'boom-bap',
    name: 'Boom Bap',
    origin: 'USA · New York',
    tradition: 'Golden-era hip-hop',
    genre: 'hip-hop',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 360, min: 328, max: 392 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '808',
    country: 'US',
    region: 'electronic-western',
    tags: ['hip-hop', 'sampler', 'golden-era', 'sp-1200'],
    instruments: ['MPC', 'SP-1200', 'vinyl'],
    swingable: true,
    story: 'The crunchy, sampled drum break of 1990s New York hip-hop — DJ Premier, Pete Rock, and the SP-1200. Kick, snare, and swung sixteenths on a chopped loop.',
  },
  {
    id: 'four-on-the-floor',
    name: 'Four on the Floor',
    origin: 'USA · Chicago / Detroit',
    tradition: 'House / techno',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 496, min: 440, max: 560 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    defaultKit: '909',
    country: 'US',
    region: 'electronic-western',
    tags: ['house', 'techno', '909', 'foundation'],
    instruments: ['TR-909', 'clap', 'hi-hat'],
    swingable: false,
    story: 'Every 909 house record ever — four straight kicks, offbeat hats, clap on 2 and 4. The metronome-to-club pipeline in one bar.',
  },

  // ============================================================
  // Rock / Pop
  // ============================================================
  {
    id: 'rock-standard',
    name: 'Standard Rock Beat',
    origin: 'USA / UK',
    tradition: 'Classic rock',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 460, min: 400, max: 520 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '707',
    region: 'electronic-western',
    tags: ['rock', '4-4', 'straight', 'backbeat'],
    instruments: ['drum kit', 'bass', 'guitar'],
    swingable: false,
    story: 'Eighth-note hats, kick on 1 and the "and of 3," snare on 2 and 4. The backbeat that holds up half of Western popular music.',
  },
  {
    id: 'rock-anthemic',
    name: 'Anthemic Rock',
    origin: 'USA / UK · 1970s',
    tradition: 'Arena rock',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 328, min: 300, max: 360 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [0, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '707',
    region: 'electronic-western',
    tags: ['rock', 'anthem', '70s', 'arena'],
    instruments: ['drum kit', 'crash'],
    swingable: false,
    story: 'Slow, punishing backbeat with a crash on one — Queen, Zeppelin, U2. The grammar of the stadium singalong.',
  },
  {
    id: 'pop-clap-beat',
    name: 'Pop Clap Beat',
    origin: 'USA · contemporary pop',
    tradition: 'Top 40',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 472, min: 400, max: 512 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      CP: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '808',
    region: 'electronic-western',
    tags: ['pop', 'clap', 'radio'],
    instruments: ['drum machine', 'handclap'],
    swingable: false,
    story: 'Four-on-the-floor kick, clap on 2 and 4 — the default grid of modern radio pop from Max Martin to Dua Lipa.',
  },
  {
    id: 'disco-classic',
    name: 'Classic Disco',
    origin: 'USA · New York · 1970s',
    tradition: 'Disco',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 480, min: 440, max: 520 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      OH: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    defaultKit: '707',
    region: 'electronic-western',
    tags: ['disco', '70s', 'dance'],
    instruments: ['drum kit', 'hi-hat', 'cowbell'],
    swingable: false,
    story: 'Four-on-the-floor kick with pumping offbeat open hats — the sound of Studio 54, the Bee Gees, and the grandparent of every modern dance beat.',
  },
  {
    id: 'country-train-beat',
    name: 'Train Beat',
    origin: 'USA · Nashville',
    tradition: 'Country',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 560, min: 400, max: 720 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [1, 0, 1, 0, 2, 0, 1, 0, 1, 0, 1, 0, 2, 0, 1, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '707',
    country: 'US',
    region: 'electronic-western',
    tags: ['country', 'train', 'johnny-cash'],
    instruments: ['drum kit', 'brushes'],
    swingable: false,
    story: 'Constant eighth-note snare with accents on 2 and 4, mimicking a freight train rolling over rails. Johnny Cash built a career on top of it.',
  },
  {
    id: 'country-two-step',
    name: 'Country Two-Step',
    origin: 'USA · Texas',
    tradition: 'Country',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 520, min: 480, max: 640 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '707',
    country: 'US',
    region: 'electronic-western',
    tags: ['country', 'two-step', 'honky-tonk'],
    instruments: ['drum kit', 'pedal steel'],
    swingable: false,
    story: 'Honky-tonk dance floor pulse — four on the floor with a backbeat and nothing fancy. Built for boots sliding in unison.',
  },
  {
    id: 'pop-punk',
    name: 'Pop Punk',
    origin: 'USA · California · 1990s',
    tradition: 'Pop-punk',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 680, min: 640, max: 760 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '707',
    country: 'US',
    region: 'electronic-western',
    tags: ['punk', 'pop-punk', 'fast', 'california'],
    instruments: ['drum kit'],
    swingable: false,
    story: 'Chopping eighth hats, a sprint-tempo backbeat, and kicks snaking between guitar accents — Green Day, Blink-182, the mall in 2002.',
  },
  {
    id: 'metal-double-bass',
    name: 'Double Bass Metal',
    origin: 'USA / UK',
    tradition: 'Heavy metal',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 640, min: 560, max: 720 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '707',
    region: 'electronic-western',
    tags: ['metal', 'double-bass', 'fast'],
    instruments: ['drum kit', 'double pedal'],
    swingable: false,
    story: 'Sixteenth notes on two kick pedals, snare on the backbeat. The engine of thrash, death, and every Iron Maiden gallop since 1980.',
  },

  // ============================================================
  // Funk / R&B / Soul
  // ============================================================
  {
    id: 'funk-funky-drummer',
    name: 'Funky Drummer',
    origin: 'USA · Cincinnati · 1970',
    tradition: 'James Brown funk',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 400, min: 380, max: 440 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 1, 0, 2, 0, 0, 1, 1, 0, 1, 0, 2, 0, 0, 1],
      HH: [2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2],
    },
    defaultKit: '707',
    country: 'US',
    region: 'electronic-western',
    tags: ['funk', 'break', 'sampled', 'james-brown'],
    instruments: ['drum kit', 'ghost notes'],
    swingable: true,
    story: 'Clyde Stubblefield\'s 1970 two-bar break for James Brown — the most sampled rhythm in recorded history. Ghost-note lace between the main hits carries the groove.',
  },
  {
    id: 'funk-cissy-strut',
    name: 'Cissy Strut',
    origin: 'USA · New Orleans · 1969',
    tradition: 'Meters funk',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 400, min: 380, max: 420 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0],
      SN: [0, 0, 1, 0, 2, 0, 0, 1, 0, 0, 1, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '707',
    country: 'US',
    region: 'electronic-western',
    tags: ['funk', 'new-orleans', 'meters', 'zigaboo'],
    instruments: ['drum kit'],
    swingable: true,
    story: 'Zigaboo Modeliste with the Meters — New Orleans funk built out of negative space. Every gap is as composed as every hit.',
  },
  {
    id: 'funk-second-line',
    name: 'New Orleans Second Line',
    origin: 'USA · New Orleans',
    tradition: 'Brass band / second line',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 392, min: 360, max: 460 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 1, 1, 0, 2, 0, 0, 0, 1, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '707',
    country: 'US',
    region: 'electronic-western',
    tags: ['funk', 'new-orleans', 'parade', 'second-line'],
    instruments: ['snare', 'bass drum', 'brass band'],
    swingable: true,
    story: 'The syncopated parade rhythm that follows New Orleans brass bands down the street — African and Caribbean accents filtered through a marching drum tradition.',
  },
  {
    id: 'funk-parliament',
    name: 'P-Funk Groove',
    origin: 'USA · Detroit · 1970s',
    tradition: 'Parliament-Funkadelic',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 432, min: 400, max: 460 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0],
      SN: [0, 1, 1, 0, 2, 0, 0, 1, 0, 1, 1, 0, 2, 0, 0, 1],
      HH: [2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2],
      OH: [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
    },
    defaultKit: '707',
    country: 'US',
    region: 'electronic-western',
    tags: ['funk', 'p-funk', 'parliament', 'afrofuturism'],
    instruments: ['drum kit', 'clavinet'],
    swingable: false,
    story: 'George Clinton\'s Mothership rhythm — dense hat subdivisions, open-hat punctuation, kicks weaving around the groove. Afrofuturism in a drum pattern.',
  },
  {
    id: 'rnb-classic',
    name: 'Classic R&B',
    origin: 'USA',
    tradition: 'Rhythm and blues',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 368, min: 340, max: 400 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '707',
    country: 'US',
    region: 'electronic-western',
    tags: ['r-n-b', 'soul', 'backbeat'],
    instruments: ['drum kit'],
    swingable: false,
    story: 'The slow-burn backbeat that carries soul, Motown chart sides, and quiet-storm radio from the 1960s onward.',
  },
  {
    id: 'rnb-neo-soul-dilla',
    name: 'Neo-Soul Dilla Feel',
    origin: 'USA · Detroit · 2000s',
    tradition: 'Neo-soul / J Dilla school',
    genre: 'hip-hop',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 328, min: 300, max: 380 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 1, 0, 0, 2, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '707',
    country: 'US',
    region: 'electronic-western',
    tags: ['neo-soul', 'dilla', 'drunk-drums', 'humanized'],
    instruments: ['MPC3000', 'Rhodes', 'bass'],
    swingable: true,
    story: 'J Dilla\'s signature — kick and snare pushed and dragged off the grid so the beat limps with a human wobble. Questlove built Voodoo around it.',
  },
  {
    id: 'rnb-neo-soul-ghost',
    name: 'Neo-Soul Ghost Groove',
    origin: 'USA · Philadelphia · 1990s',
    tradition: 'Neo-soul',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 340, min: 300, max: 380 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0],
      SN: [1, 0, 1, 0, 2, 0, 1, 0, 1, 0, 1, 0, 2, 0, 1, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '707',
    country: 'US',
    region: 'electronic-western',
    tags: ['neo-soul', 'philly', 'ghost-notes'],
    instruments: ['drum kit', 'Rhodes'],
    swingable: true,
    story: 'Ghost notes carpet the space between backbeats — D\'Angelo, Erykah Badu, the Soulquarians crew turning funk into a whispered conversation.',
  },
  {
    id: 'motown-beat',
    name: 'Motown Beat',
    origin: 'USA · Detroit · 1960s',
    tradition: 'Motown',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 480, min: 440, max: 520 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
      CP: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
    },
    defaultKit: '707',
    country: 'US',
    region: 'electronic-western',
    tags: ['motown', 'soul', '60s', 'tambourine'],
    instruments: ['drum kit', 'tambourine', 'handclaps'],
    swingable: false,
    story: 'Benny Benjamin and the Funk Brothers: four-on-the-floor kick with handclaps and tambourine riding the backbeat. The sound of Hitsville U.S.A.',
  },

  // ============================================================
  // Reggae / Dub / Ska
  // ============================================================
  {
    id: 'reggae-one-drop',
    name: 'One Drop',
    origin: 'Jamaica · Kingston',
    tradition: 'Roots reggae',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 300, min: 260, max: 340 },
    difficulty: 'beginner',
    tracks: {
      KK: [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '707',
    country: 'JM',
    region: 'electronic-western',
    tags: ['reggae', 'one-drop', 'roots', 'bob-marley'],
    instruments: ['drum kit', 'cross-stick'],
    swingable: false,
    story: 'Carlton Barrett with Bob Marley & the Wailers. Beat 1 is empty — kick and rim shot both land on beat 3, and the bass plays the ghost of the downbeat.',
  },
  {
    id: 'reggae-rockers',
    name: 'Rockers',
    origin: 'Jamaica · 1970s',
    tradition: 'Reggae',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 312, min: 240, max: 360 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '707',
    country: 'JM',
    region: 'electronic-western',
    tags: ['reggae', 'rockers', 'sly-dunbar'],
    instruments: ['drum kit'],
    swingable: false,
    story: 'Sly Dunbar\'s answer to one-drop — steady quarter-note kick pulls the groove forward like a march while the snare keeps the reggae accent on beat 3.',
  },
  {
    id: 'reggae-steppers',
    name: 'Steppers',
    origin: 'Jamaica',
    tradition: 'Roots reggae / dub',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 320, min: 280, max: 380 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      HH: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      OH: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    defaultKit: '707',
    country: 'JM',
    region: 'electronic-western',
    tags: ['reggae', 'steppers', 'dub', 'militant'],
    instruments: ['drum kit', 'open hat'],
    swingable: false,
    story: 'Four-on-the-floor reggae — the militant, marching style of Burning Spear and Black Uhuru. A Rastafarian drumbeat dressed in dub clothing.',
  },
  {
    id: 'ska-classic',
    name: 'Classic Ska Offbeat',
    origin: 'Jamaica · 1960s',
    tradition: 'Ska',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 640, min: 600, max: 720 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    defaultKit: '707',
    country: 'JM',
    region: 'electronic-western',
    tags: ['ska', 'jamaica', 'offbeat', '60s'],
    instruments: ['drum kit', 'horns'],
    swingable: false,
    story: 'The offbeat "upstroke" — hi-hats and guitar stab only on the ands. The pre-reggae sound of Kingston dances in the independence era.',
  },

  // ============================================================
  // Hip-Hop
  // ============================================================
  {
    id: 'hiphop-trap',
    name: 'Trap',
    origin: 'USA · Atlanta · 2000s',
    tradition: 'Trap hip-hop',
    genre: 'hip-hop',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 560, min: 520, max: 600 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: '808',
    country: 'US',
    region: 'electronic-western',
    tags: ['hiphop', 'trap', 'half-time', 'atlanta', '808'],
    instruments: ['808', 'hi-hat', 'clap'],
    swingable: false,
    story: 'Half-time feel at 140 — snare on beat 3 only, 808 sub-kick booming, skittering hi-hats. The Atlanta template that swallowed pop radio in the 2010s.',
  },
  {
    id: 'hiphop-trap-triplet',
    name: 'Trap Triplet Hats',
    origin: 'USA · Atlanta',
    tradition: 'Trap',
    genre: 'hip-hop',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 560, min: 540, max: 592 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      HH: [2, 0, 1, 1, 1, 1, 2, 0, 2, 0, 1, 1, 1, 1, 2, 0],
    },
    defaultKit: '808',
    country: 'US',
    region: 'electronic-western',
    tags: ['hiphop', 'trap', 'triplet', 'hats'],
    instruments: ['808', 'hi-hat'],
    swingable: false,
    story: 'Hi-hat triplet rolls fired before beats 2 and 4 — Lex Luger, Metro Boomin, the stuttering detail that made trap drums feel alive.',
  },
  {
    id: 'hiphop-lofi',
    name: 'Lo-Fi Hip-Hop',
    origin: 'International · 2010s',
    tradition: 'Lo-fi beats',
    genre: 'hip-hop',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 320, min: 288, max: 360 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 1, 0, 0, 2, 0, 0, 0, 2, 0, 1, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0],
    },
    defaultKit: '707',
    region: 'electronic-western',
    tags: ['lofi', 'chillhop', 'study-beats'],
    instruments: ['MPC', 'vinyl crackle', 'jazz samples'],
    swingable: true,
    story: 'Tape-saturated, swung, and deliberately imperfect — the Nujabes-to-YouTube-radio pipeline that made hip-hop drums into study music.',
  },
  {
    id: 'hiphop-uk-drill',
    name: 'UK Drill',
    origin: 'UK · South London · 2010s',
    tradition: 'UK drill',
    genre: 'hip-hop',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 568, min: 560, max: 580 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 1, 1, 1, 0, 2, 0, 2, 0, 1, 1, 1, 0, 2, 0],
    },
    defaultKit: '808',
    country: 'GB',
    region: 'electronic-western',
    tags: ['drill', 'uk-drill', 'sliding-808'],
    instruments: ['808', 'hi-hat'],
    swingable: false,
    story: 'South London by way of Chicago — sliding 808 bass, off-kilter kicks, and snare rolls. Drill\'s syncopation rewrote the hip-hop rulebook in the late 2010s.',
  },
  {
    id: 'hiphop-phonk',
    name: 'Phonk',
    origin: 'USA · Memphis / internet · 2010s',
    tradition: 'Memphis phonk',
    genre: 'hip-hop',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 552, min: 520, max: 580 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0],
      CP: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
      OH: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    defaultKit: '808',
    country: 'US',
    region: 'electronic-western',
    tags: ['phonk', 'memphis', 'cowbell', 'drift'],
    instruments: ['808', 'cowbell', 'vocal chop'],
    swingable: false,
    story: 'Memphis underground cassette rap looped through the internet and turned into drift-race music. Cowbell on the ands, 808s everywhere.',
  },
  {
    id: 'hiphop-jersey-club',
    name: 'Jersey Club Bounce',
    origin: 'USA · Newark · 2000s',
    tradition: 'Jersey club',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 552, min: 520, max: 580 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
      CP: [0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 2, 2, 2, 0],
    },
    defaultKit: '808',
    country: 'US',
    region: 'electronic-western',
    tags: ['jersey-club', 'bounce', 'bed-squeak', 'dance'],
    instruments: ['808', 'bed squeak sample'],
    swingable: false,
    story: 'Newark club dance music — triplet kick burst ("bed-squeak") detonating on the ands, quintuplet chants on the breaks. Pure choreographed chaos.',
  },

  // ============================================================
  // House / Techno / Electronic
  // ============================================================
  {
    id: 'house-classic',
    name: 'Classic House',
    origin: 'USA · Chicago · 1980s',
    tradition: 'Chicago house',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 500, min: 488, max: 512 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      CP: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      OH: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    defaultKit: '909',
    country: 'US',
    region: 'electronic-western',
    tags: ['house', 'chicago', '909'],
    instruments: ['TR-909', 'clap'],
    swingable: false,
    story: 'Frankie Knuckles at the Warehouse — the stripped-down Roland-909 grid that built Chicago house and defined dance music worldwide.',
  },
  {
    id: 'house-deep',
    name: 'Deep House',
    origin: 'USA · New York / Chicago',
    tradition: 'Deep house',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 488, min: 472, max: 500 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      CP: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      OH: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    defaultKit: '909',
    region: 'electronic-western',
    tags: ['house', 'deep-house', 'shakers'],
    instruments: ['TR-909', 'shaker', 'pad'],
    swingable: false,
    story: 'Shaker-soft sixteenths under a four-on-the-floor groove. The Larry Heard / Masters at Work lineage — house music with soul.',
  },
  {
    id: 'house-acid',
    name: 'Acid House',
    origin: 'USA · Chicago · 1987',
    tradition: 'Acid house',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 504, min: 480, max: 520 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      CP: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
      OH: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    defaultKit: '909',
    country: 'US',
    region: 'electronic-western',
    tags: ['acid', 'chicago', '303', '1987'],
    instruments: ['TB-303', 'TR-909'],
    swingable: false,
    story: 'Phuture\'s "Acid Tracks" — house drums under a snaking TB-303. The accidental bass synth that sparked the UK rave scene.',
  },
  {
    id: 'techno-detroit',
    name: 'Detroit Techno',
    origin: 'USA · Detroit · 1980s',
    tradition: 'Detroit techno',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 520, min: 512, max: 540 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      CP: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      OH: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    defaultKit: '909',
    country: 'US',
    region: 'electronic-western',
    tags: ['techno', 'detroit', 'belleville-three'],
    instruments: ['TR-909', 'synth'],
    swingable: false,
    story: 'Juan Atkins, Derrick May, Kevin Saunderson — "Strings of Life," "Big Fun." Detroit techno as Black futurism at the end of Motown.',
  },
  {
    id: 'techno-berlin',
    name: 'Berlin Techno',
    origin: 'Germany · Berlin · 1990s',
    tradition: 'Berlin techno',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 540, min: 520, max: 560 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      CP: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '909',
    country: 'DE',
    region: 'electronic-western',
    tags: ['techno', 'berlin', 'driving', 'berghain'],
    instruments: ['TR-909', 'reverb'],
    swingable: false,
    story: 'Post-Wall warehouse techno — driving straight hats under an unrelenting kick. Tresor, Berghain, the sound of the tunnel.',
  },
  {
    id: 'techno-minimal',
    name: 'Minimal Techno',
    origin: 'Germany · 2000s',
    tradition: 'Minimal techno',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 512, min: 500, max: 540 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      HH: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    defaultKit: '909',
    country: 'DE',
    region: 'electronic-western',
    tags: ['techno', 'minimal', 'micro-house', 'kompakt'],
    instruments: ['TR-909', 'click'],
    swingable: false,
    story: 'Villalobos, Hawtin, Kompakt — techno stripped back to a kick, a rim, and a click. The DJ builds the record.',
  },

  // ============================================================
  // UK Garage / Dubstep / Bass
  // ============================================================
  {
    id: 'uk-garage-2step',
    name: 'UK Garage 2-Step',
    origin: 'UK · London · late 1990s',
    tradition: 'UK garage',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 536, min: 520, max: 552 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '909',
    country: 'GB',
    region: 'electronic-western',
    tags: ['garage', 'uk-garage', '2-step', 'shuffle'],
    instruments: ['drum machine', 'sub-bass'],
    swingable: true,
    story: 'The 2-step: garage with the kick skipping beat 3, snare still on 2 and 4. Add heavy swing and you\'ve got MJ Cole and Todd Edwards on a UK pirate station.',
  },
  {
    id: 'dubstep-classic',
    name: 'Classic Dubstep',
    origin: 'UK · Croydon · 2000s',
    tradition: 'Dubstep',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 560, min: 552, max: 568 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '909',
    country: 'GB',
    region: 'electronic-western',
    tags: ['dubstep', 'half-time', '140', 'croydon'],
    instruments: ['sub-bass', 'kit'],
    swingable: false,
    story: '140 BPM with a half-time snare on beat 3 — the South London template behind Skream, Benga, and every wobble bass on earth.',
  },

  // ============================================================
  // DnB / Breakbeat
  // ============================================================
  {
    id: 'dnb-amen-break',
    name: 'Amen Break',
    origin: 'USA · 1969 / UK · 1990s',
    tradition: 'Breakbeat / DnB',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 680, min: 640, max: 720 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 1, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '909',
    country: 'US',
    region: 'electronic-western',
    tags: ['breakbeat', 'dnb', 'amen', 'jungle'],
    instruments: ['sampled break', 'drum kit'],
    swingable: false,
    story: 'Gregory Coleman\'s six-second drum break on The Winstons\' "Amen, Brother" (1969). Chopped, pitched, and relooped, it became the DNA of jungle, DnB, and half of UK electronic music.',
  },
  {
    id: 'dnb-jungle',
    name: 'Jungle Break',
    origin: 'UK · early 1990s',
    tradition: 'Jungle',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 660, min: 620, max: 700 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 1, 0, 2, 0, 0, 0, 1, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 1],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '909',
    country: 'GB',
    region: 'electronic-western',
    tags: ['jungle', 'breakbeat', 'uk', 'hardcore'],
    instruments: ['sampled break', 'sub-bass'],
    swingable: false,
    story: 'UK hardcore sped up, dubwise bass dropped in, Amen breaks chopped to ribbons. The 1992–95 pirate radio sound that birthed DnB.',
  },

  // ============================================================
  // Jazz
  // ============================================================
  {
    id: 'jazz-swing-medium',
    name: 'Medium Jazz Swing',
    origin: 'USA',
    tradition: 'Swing / jazz',
    genre: 'jazz',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 560, min: 480, max: 720 },
    difficulty: 'intermediate',
    tracks: {
      KK: [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
      HH: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      OH: [2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0],
    },
    defaultKit: '707',
    country: 'US',
    region: 'electronic-western',
    tags: ['jazz', 'swing', 'ride', 'brushes'],
    instruments: ['ride cymbal', 'brushes', 'upright bass'],
    swingable: true,
    story: 'The spang-a-lang ride pattern, hat comping on 2 and 4, feathered bass drum. The backbone of every standard played after 1940.',
  },
  {
    id: 'jazz-bebop',
    name: 'Bebop Fast Ride',
    origin: 'USA · New York · 1940s',
    tradition: 'Bebop',
    genre: 'jazz',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 240, min: 200, max: 300 },
    difficulty: 'advanced',
    tracks: {
      KK: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      OH: [2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0],
      HH: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
    },
    defaultKit: '707',
    country: 'US',
    region: 'electronic-western',
    tags: ['jazz', 'bebop', 'fast', '40s'],
    instruments: ['ride', 'hi-hat'],
    swingable: true,
    story: 'Max Roach, Kenny Clarke — the bebop reinvention of time. Ride cymbal carries the swing pulse and the bass drum drops bombs.',
  },
  {
    id: 'jazz-waltz',
    name: 'Jazz Waltz',
    origin: 'USA',
    tradition: 'Jazz',
    genre: 'jazz',
    timeSig: '3/4',
    grouping: [3, 3, 3],
    stepUnit: 16,
    steps: 12,
    bpm: { default: 560, min: 480, max: 640 },
    difficulty: 'intermediate',
    tracks: {
      KK: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      OH: [2, 0, 0, 2, 1, 0, 2, 0, 2, 1, 0, 0],
      HH: [0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
    },
    defaultKit: '707',
    country: 'US',
    region: 'electronic-western',
    tags: ['jazz', 'waltz', '3-4', 'swing'],
    instruments: ['ride', 'brushes'],
    swingable: true,
    story: 'Ride pattern stretched over three beats. "My Favorite Things," "Bluesette," "Someday My Prince Will Come" — the jazz triple meter.',
  },
  {
    id: 'jazz-shuffle-purdie',
    name: 'Purdie Shuffle',
    origin: 'USA',
    tradition: 'Funk / R&B shuffle',
    genre: 'jazz',
    timeSig: '4/4',
    grouping: [3, 3, 3, 3],
    stepUnit: 16,
    steps: 12,
    bpm: { default: 380, min: 340, max: 440 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 1, 0, 2, 1, 0, 0, 1, 0, 2, 1, 0],
      HH: [2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 0, 2],
    },
    defaultKit: '707',
    country: 'US',
    region: 'electronic-western',
    tags: ['shuffle', 'purdie', 'funk', 'half-time'],
    instruments: ['drum kit', 'ghost notes'],
    swingable: true,
    story: 'Bernard Purdie\'s half-time triplet shuffle — "Babylon Sisters," "Home at Last." Ghost-note lace between backbeats, the holy grail of feel.',
  },
  {
    id: 'jazz-bossa-nova',
    name: 'Bossa Nova',
    origin: 'Brazil · Rio · 1960s',
    tradition: 'Bossa nova',
    genre: 'jazz',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 520, min: 480, max: 600 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '707',
    country: 'BR',
    region: 'electronic-western',
    tags: ['bossa', 'brazil', 'jazz', 'samba-feet'],
    instruments: ['brushes', 'cross-stick', 'nylon guitar'],
    swingable: false,
    story: 'Samba miniaturized for apartment music — Jobim, João Gilberto. Cross-stick clave on top, feathered kick below, hats whispering sixteenths.',
  },

  // ============================================================
  // World-adjacent / global electronic
  // ============================================================
  {
    id: 'afrobeat-tony-allen',
    name: 'Afrobeat (Tony Allen)',
    origin: 'Nigeria · Lagos · 1970s',
    tradition: 'Afrobeat',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 460, min: 420, max: 500 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
      OH: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    defaultKit: '707',
    country: 'NG',
    region: 'electronic-western',
    tags: ['afrobeat', 'tony-allen', 'fela', 'nigeria'],
    instruments: ['drum kit', 'shekere', 'congas'],
    swingable: false,
    story: 'Tony Allen: "without Tony Allen, there would be no Afrobeat." Four limbs acting as four players — Fela Kuti\'s Africa 70 engine room.',
  },
  {
    id: 'afrobeats-modern',
    name: 'Modern Afrobeats',
    origin: 'Nigeria · 2010s',
    tradition: 'Afrobeats (contemporary pop)',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 432, min: 400, max: 472 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 1, 0, 0, 1, 0, 2, 0, 0, 1, 0, 0, 1, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
      CP: [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0],
    },
    defaultKit: '808',
    country: 'NG',
    region: 'electronic-western',
    tags: ['afrobeats', 'nigeria', 'wizkid', 'burna-boy'],
    instruments: ['drum machine', 'shaker', 'talking drum'],
    swingable: false,
    story: 'Wizkid, Burna Boy, Davido — Lagos pop built on kick bounce, skipping hi-hats, and a layer of handclaps. Global radio since the late 2010s.',
  },
  {
    id: 'amapiano-log-drum',
    name: 'Amapiano',
    origin: 'South Africa · 2010s',
    tradition: 'Amapiano',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 456, min: 440, max: 472 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 2, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      HH: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      OH: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    defaultKit: '909',
    country: 'ZA',
    region: 'electronic-western',
    tags: ['amapiano', 'south-africa', 'log-drum', 'house'],
    instruments: ['log drum', 'shaker', 'deep bass'],
    swingable: false,
    story: 'Johannesburg deep house mutated into a bass-heavy sub-genre — shuffling shaker, percussive log drum, and a tempo built for slow-dance soweto.',
  },
  {
    id: 'gqom',
    name: 'Gqom',
    origin: 'South Africa · Durban · 2010s',
    tradition: 'Gqom',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 500, min: 480, max: 520 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 1, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0],
      SN: [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      CP: [0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0],
    },
    defaultKit: '808',
    country: 'ZA',
    region: 'electronic-western',
    tags: ['gqom', 'south-africa', 'durban', 'dark'],
    instruments: ['808', 'percussion'],
    swingable: false,
    story: 'Durban warehouse music — broken kick patterns, cavernous sub, percussive gqom ("drum" in isiZulu) clusters. Taxi-rank rhythm turned global.',
  },
  {
    id: 'footwork',
    name: 'Footwork',
    origin: 'USA · Chicago · 2000s',
    tradition: 'Chicago footwork / juke',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 640, min: 620, max: 660 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
      CP: [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
    },
    defaultKit: '808',
    country: 'US',
    region: 'electronic-western',
    tags: ['footwork', 'juke', 'chicago', '160bpm'],
    instruments: ['808', 'vocal chop'],
    swingable: false,
    story: 'DJ Rashad, Traxman — 160 BPM syncopated triplets and broken kicks built for competitive dance battles on the South Side of Chicago.',
  },
  // reggaeton-dembow: canonical entry lives in caribbean.ts (region: caribbean).
  {
    id: 'trance-classic',
    name: 'Classic Trance',
    origin: 'Germany · 1990s',
    tradition: 'Trance',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 552, min: 544, max: 568 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      CP: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      OH: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    defaultKit: '909',
    country: 'DE',
    region: 'electronic-western',
    tags: ['trance', 'germany', 'uplifting', '90s'],
    instruments: ['TR-909', 'supersaw'],
    swingable: false,
    story: 'Frankfurt and Ibiza — four-on-the-floor under supersaw pads, built for hands-in-the-air moments. Paul van Dyk, Tiësto, Armin.',
  },
];
