import type { Pattern } from '../types';

export const GAMELAN_SOUTHEAST_ASIA_PATTERNS: Pattern[] = [
  {
    id: 'lancaran',
    name: 'Lancaran',
    origin: 'Indonesia · Java',
    tradition: 'Javanese gamelan',
    genre: 'classical',
    timeSig: '16/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 8,
    steps: 16,
    bpm: { default: 120, min: 90, max: 160 },
    difficulty: 'intermediate',
    tracks: {
      KK: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2],
      SN: [0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
      OH: [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2],
      CP: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: 'gamelan',
    country: 'ID',
    region: 'gamelan-southeast-asia',
    tags: ['javanese', 'colotomic', 'fast', 'gongan'],
    instruments: ['gong', 'kenong', 'kempul', 'saron'],
    swingable: false,
    story: 'The shortest standard Javanese gongan — lively and fast. The gong ageng closes the 16-beat cycle, kenong marks each kenongan, and kempul fills in the middle.',
  },
  {
    id: 'kotekan',
    name: 'Kotekan',
    origin: 'Indonesia · Bali',
    tradition: 'Balinese gamelan',
    genre: 'classical',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 160, min: 140, max: 200 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
      OH: [0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2],
    },
    defaultKit: 'gamelan',
    country: 'ID',
    region: 'gamelan-southeast-asia',
    tags: ['balinese', 'interlocking', 'kebyar', 'polos-sangsih'],
    instruments: ['reyong', 'gangsa', 'gong'],
    swingable: false,
    story: 'The interlocking heart of Balinese kebyar — polos falls on the beat, sangsih between them. Alone each is incomplete; together they sound twice as fast as either can play.',
  },
  {
    id: 'gendhing-sederhana',
    name: 'Gendhing Sederhana',
    origin: 'Indonesia · Java',
    tradition: 'Javanese court gamelan',
    genre: 'classical',
    timeSig: '16/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 8,
    steps: 16,
    bpm: { default: 75, min: 50, max: 100 },
    difficulty: 'intermediate',
    tracks: {
      KK: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2],
      SN: [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2],
      HH: [2, 0, 1, 0, 2, 0, 1, 0, 2, 0, 1, 0, 2, 0, 1, 0],
      CP: [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
    },
    defaultKit: 'gamelan',
    country: 'ID',
    region: 'gamelan-southeast-asia',
    tags: ['javanese', 'colotomic', 'meditative', 'court'],
    instruments: ['gong ageng', 'kethuk', 'kempyang'],
    swingable: false,
    story: 'A simple gendhing — the meditative, introspective form heard in kraton court music and behind vocal and dance performance. The gong breathes slowly.',
  },
];
