import type { Pattern } from '../types';

export const IBERIA_FLAMENCO_PATTERNS: Pattern[] = [
  {
    id: 'buleria',
    name: 'Bulería',
    origin: 'Spain · Jerez',
    tradition: 'Flamenco fiesta',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [2, 2, 2, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 220, min: 180, max: 260 },
    difficulty: 'advanced',
    tracks: {
      KK: [0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0],
      SN: [2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'gitano', 'compas', 'fiesta'],
    instruments: ['cajón', 'palmas', 'guitarra'],
    swingable: false,
    story: 'The fastest flamenco palo — the climax of any Gitano fiesta in Jerez. Accents fall on 3, 6, 8, 10, and 12, but phrases typically start on beat 12 itself.',
    relatedIds: ['solea'],
  },
  {
    id: 'solea',
    name: 'Soleá',
    origin: 'Spain · Seville / Cádiz',
    tradition: 'Cante jondo',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [2, 2, 2, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 100, min: 80, max: 120 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 2, 0, 2, 0, 2],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'cante-jondo', 'compas', 'deep'],
    instruments: ['cajón', 'palmas', 'guitarra'],
    swingable: false,
    story: 'The "mother" of flamenco — slow, dignified, deeply emotional. Same 12-beat accent pattern as bulería but at half the speed and twice the weight.',
    relatedIds: ['buleria'],
  },
  {
    id: 'tangos-flamenco',
    name: 'Tangos (Flamenco)',
    origin: 'Spain · Cádiz / Seville',
    tradition: 'Flamenco palo',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 130, min: 120, max: 160 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'tangos', '4-beat', 'dance'],
    instruments: ['cajón', 'palmas', 'guitarra'],
    swingable: false,
    story: 'Not Argentine tango — the flamenco tangos of Cádiz and Triana. The first beat of each group is subdued; beats 2, 3, 4 carry the drive.',
  },
];
