import type { Pattern } from '../types';

export const IBERIA_FLAMENCO_PATTERNS: Pattern[] = [
  {
    id: 'buleria',
    name: 'Bulería',
    origin: 'Spain · Jerez',
    tradition: 'Flamenco fiesta',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [2, 2, 2, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 220, min: 180, max: 260 },
    difficulty: 'advanced',
    tracks: {
      KK: [0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0],
      SN: [2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'gitano', 'compas', 'fiesta'],
    instruments: ['cajón', 'palmas', 'guitarra'],
    swingable: false,
    story: 'The fastest flamenco palo — the climax of any Gitano fiesta in Jerez. Accents fall on 3, 6, 8, 10, and 12, but phrases typically start on beat 12 itself.',
    relatedIds: ['solea', 'bembe', 'bembe-68', 'alegrias'],
  },
  {
    id: 'solea',
    name: 'Soleá',
    origin: 'Spain · Seville / Cádiz',
    tradition: 'Cante jondo',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [2, 2, 2, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 100, min: 80, max: 120 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 2, 0, 2, 0, 2],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'cante-jondo', 'compas', 'deep'],
    instruments: ['cajón', 'palmas', 'guitarra'],
    swingable: false,
    story: 'The "mother" of flamenco — slow, dignified, deeply emotional. Same 12-beat accent pattern as bulería but at half the speed and twice the weight.',
    relatedIds: ['buleria', 'bembe', 'bembe-68', 'zambra', 'gnawa'],
  },
  {
    id: 'tangos-flamenco',
    name: 'Tangos (Flamenco)',
    origin: 'Spain · Cádiz / Seville',
    tradition: 'Flamenco palo',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 520, min: 480, max: 640 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'tangos', '4-beat', 'dance'],
    instruments: ['cajón', 'palmas', 'guitarra'],
    swingable: false,
    story: 'Not Argentine tango — the flamenco tangos of Cádiz and Triana. The first beat of each group is subdued; beats 2, 3, 4 carry the drive.',
  },
  {
    id: 'seguiriya',
    name: 'Seguiriya',
    origin: 'Spain · Cádiz / Jerez',
    tradition: 'Cante jondo',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [2, 2, 3, 3, 2],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 80, min: 60, max: 100 },
    difficulty: 'advanced',
    tracks: {
      KK: [0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0],
      SN: [2, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'cante-jondo', 'compas', 'grief', 'limping'],
    instruments: ['cajón', 'palmas', 'guitarra'],
    swingable: false,
    story: 'The other pillar of cante jondo alongside soleá — where soleá is regal, seguiriya is anguished. Accents on 1, 3, 5, 8, 11 create a limping 2+2+3+3+2 that never settles.',
    relatedIds: ['solea'],
  },
  {
    id: 'alegrias',
    name: 'Alegrías',
    origin: 'Spain · Cádiz',
    tradition: 'Cantinas flamenco',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [2, 2, 2, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 140, min: 120, max: 160 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 2, 0, 2, 0, 2],
      HH: [2, 1, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'cantinas', 'compas', 'cadiz', 'major-key'],
    instruments: ['cajón', 'palmas', 'guitarra'],
    swingable: false,
    story: 'Alegrías means "joys" — the signature palo of Cádiz. Same soleá compás, but bright, maritime, in a major key. Born when Aragonese jota mixed with Cádiz music during the Peninsular War.',
    relatedIds: ['solea', 'buleria'],
  },
  {
    id: 'rumba-flamenca',
    name: 'Rumba Flamenca',
    origin: 'Spain · Andalusia',
    tradition: 'Flamenco ida y vuelta',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 480, min: 400, max: 560 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'rumba', 'tresillo', 'popular', 'ida-y-vuelta'],
    instruments: ['cajón', 'palmas', 'guitarra'],
    swingable: false,
    story: 'The most internationally famous flamenco groove — Gipsy Kings territory. A 3+3+2 tresillo from Cuba married to tangos compás, strummed with the ventilador fan technique.',
    relatedIds: ['tangos-flamenco', 'son-clave', 'bomba-sica', 'colombianas'],
  },
  {
    id: 'fandango-huelva',
    name: 'Fandango de Huelva',
    origin: 'Spain · Huelva',
    tradition: 'Village festive palo',
    genre: 'folk-dance',
    timeSig: '3/4',
    grouping: [2, 2, 2],
    stepUnit: 8,
    steps: 6,
    bpm: { default: 280, min: 220, max: 340 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'fandango', 'village', 'huelva'],
    instruments: ['cajón', 'palmas', 'guitarra'],
    swingable: false,
    story: 'The only fandangos with a strict compás — every village of Huelva has its own. Six beats, accents on 3 and 5, the guitar rasgueo matching the palmas exactly.',
  },
  {
    id: 'martinete',
    name: 'Martinete',
    origin: 'Spain · Triana',
    tradition: 'Forge cante',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 360, min: 280, max: 440 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'cante-jondo', 'forge', 'martillo', 'a-palo-seco'],
    instruments: ['martillo', 'yunque', 'voz'],
    swingable: false,
    story: 'A cante of the forges — sung a palo seco over hammer on anvil, no guitar. Gitano blacksmiths in Triana turned their workday into this heavy 4/4 lament.',
  },
  {
    id: 'taranta',
    name: 'Taranta',
    origin: 'Spain · Linares · Almería',
    tradition: 'Miners\' cante',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 320, min: 240, max: 400 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'cante-de-las-minas', 'levante', 'free-rhythm'],
    instruments: ['guitarra', 'palmas', 'cajón'],
    swingable: false,
    story: 'From the mining towns of the Levante — dark, modal, full of coal-dust melancholy. Sung free over a guitar, but the accompanying baile takes a slow 4/4 pulse.',
  },
  {
    id: 'milonga-flamenca',
    name: 'Milonga',
    origin: 'Spain / Argentina · Cádiz',
    tradition: 'Ida y vuelta palo',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 720, min: 560, max: 880 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 1],
      SN: [0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'ida-y-vuelta', 'milonga', 'river-plate'],
    instruments: ['cajón', 'palmas', 'guitarra'],
    swingable: false,
    story: 'The Spanish-Argentine round-trip — the Rio de la Plata milonga reimagined as a flamenco palo. Habanera-bass undertow under the cajón, saudade in the melody.',
    relatedIds: ['tangos-flamenco', 'danzon', 'bolero'],
  },
  {
    id: 'zambra',
    name: 'Zambra',
    origin: 'Spain · Granada · Sacromonte',
    tradition: 'Moorish-Gitano cante',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 440, min: 360, max: 520 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'morisco', 'granada', 'sacromonte', 'cave'],
    instruments: ['cajón', 'palmas', 'guitarra', 'castañuelas'],
    swingable: false,
    story: 'The cave-dance of Sacromonte — Moorish wedding music preserved by Granada\'s Gitanos after the Reconquista. A hypnotic tangos cousin with a Maghrebi shimmer.',
    relatedIds: ['tangos-flamenco', 'chaabi-moroccan', 'gnawa'],
  },
  {
    id: 'verdiales',
    name: 'Verdiales',
    origin: 'Spain · Málaga',
    tradition: 'Málaga fandango',
    genre: 'folk-dance',
    timeSig: '3/4',
    grouping: [2, 2, 2],
    stepUnit: 8,
    steps: 6,
    bpm: { default: 300, min: 240, max: 360 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 2, 0],
      HH: [2, 2, 2, 2, 2, 2],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'fandango', 'malaga', 'village', 'panda'],
    instruments: ['violín', 'guitarra', 'pandero', 'platillos', 'palmas'],
    swingable: false,
    story: 'The wildest fandango — played by pandas of violin, guitar, cymbals, and tambourines in the mountains above Málaga. Dense, rattling, a village party rhythm.',
    relatedIds: ['fandango-huelva'],
  },
  {
    id: 'peteneras',
    name: 'Peteneras',
    origin: 'Spain · Cádiz · Paterna de Rivera',
    tradition: 'Flamenco palo',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 2, 2, 2],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 110, min: 90, max: 130 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 2, 0, 2, 0, 2],
      HH: [2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'compas', 'cursed', 'cadiz', 'funeral'],
    instruments: ['cajón', 'palmas', 'guitarra'],
    swingable: false,
    story: 'A 12-beat palo reputed to be cursed — many cantaores refuse to sing it. Starts with two threes before the familiar soleá tail, giving it an uncanny tilt.',
    relatedIds: ['solea'],
  },
  {
    id: 'garrotin',
    name: 'Garrotín',
    origin: 'Spain · Asturias → Andalusia',
    tradition: 'Flamenco palo',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 560, min: 440, max: 680 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'tangos-family', 'asturias', 'playful'],
    instruments: ['cajón', 'palmas', 'guitarra', 'sombrero'],
    swingable: false,
    story: 'An Asturian street dance adopted by flamenco Gitanos around 1900 — same family as tangos, but lighter, playful, traditionally danced with a hat.',
    relatedIds: ['tangos-flamenco'],
  },
  {
    id: 'colombianas',
    name: 'Colombianas',
    origin: 'Spain · Andalusia',
    tradition: 'Flamenco ida y vuelta',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 480, min: 400, max: 560 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'ida-y-vuelta', 'latin-american', 'pepe-marchena'],
    instruments: ['cajón', 'palmas', 'guitarra'],
    swingable: false,
    story: 'An invented round-trip palo — Pepe Marchena wrote it in the 1930s to evoke an imagined Colombia. Tangos bones, rumba tresillo, a postcard rhythm that stuck.',
    relatedIds: ['rumba-flamenca', 'tangos-flamenco', 'bomba-sica'],
  },
  {
    id: 'farruca',
    name: 'Farruca',
    origin: 'Spain · Andalusia (Galician origin)',
    tradition: 'Masculine flamenco palo',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 440, min: 360, max: 520 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'farruca', 'masculine', 'galician-origin', 'a-minor'],
    instruments: ['cajón', 'palmas', 'guitarra'],
    swingable: false,
    story: 'The baile masculino — a dark, martial 4/4 in A minor traditionally danced only by men. Likely Galician in origin; every farruca eventually accelerates into tangos.',
    relatedIds: ['tangos-flamenco', 'garrotin', 'muineira'],
  },
  {
    id: 'tientos',
    name: 'Tientos',
    origin: 'Spain · Cádiz / Seville',
    tradition: 'Slow tangos (cante hondo)',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 280, min: 240, max: 340 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 1, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'tangos-family', 'slow', 'sensual', 'accelerando'],
    instruments: ['cajón', 'palmas', 'guitarra'],
    swingable: false,
    story: 'Slow-tempo tangos — sensual, hypnotic, pregnant with ghost notes. Every tientos accelerates into full tangos by the end, a dramatic arc from contemplation to release.',
    relatedIds: ['tangos-flamenco', 'solea'],
  },
  {
    id: 'cantinas',
    name: 'Cantiñas',
    origin: 'Spain · Cádiz',
    tradition: 'Cantiñas family',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [2, 2, 2, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 155, min: 130, max: 180 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 1, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'cantinas', 'cadiz', 'festive'],
    instruments: ['cajón', 'palmas', 'guitarra'],
    swingable: false,
    story: 'The Cádiz cantiñas family — a light, maritime palo group that shares the alegrías compás but includes romeras, mirabrás, and caracoles as sub-tunes woven together.',
    relatedIds: ['alegrias', 'romeras', 'mirabras', 'caracoles'],
  },
  {
    id: 'romeras',
    name: 'Romeras',
    origin: 'Spain · Cádiz',
    tradition: 'Cantinas sub-palo',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [2, 2, 2, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 150, min: 130, max: 170 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 1, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'cantinas', 'cadiz', 'romeras', 'romero-el-tuerto'],
    instruments: ['cajón', 'palmas', 'guitarra'],
    swingable: false,
    story: 'A cantinas sub-palo created by Romero el Tuerto in 19th-century Cádiz — major key, brighter than alegrías, with a distinctive lilt on the last two threes of the compás.',
    relatedIds: ['cantinas', 'alegrias'],
  },
  {
    id: 'fado-menor',
    name: 'Fado Menor',
    origin: 'Portugal · Lisbon',
    tradition: 'Lisbon minor-key fado',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 220, min: 180, max: 260 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'PT',
    region: 'iberia-flamenco',
    tags: ['portuguese', 'fado', 'minor', 'amalia', 'saudade'],
    instruments: ['guitarra portuguesa', 'viola de fado'],
    swingable: false,
    story: 'The minor-key Lisbon fado — Amália Rodrigues\'s home key. Slow, tragic, open harmonies; the voice floats free of the beat while the guitarra holds the pulse.',
    relatedIds: ['milonga-flamenca'],
  },
  {
    id: 'muineira',
    name: 'Muiñeira',
    origin: 'Spain · Galicia',
    tradition: 'Galician gaita dance',
    genre: 'folk-dance',
    timeSig: '6/8',
    grouping: [3, 3],
    stepUnit: 8,
    steps: 6,
    bpm: { default: 130, min: 110, max: 150 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 1, 0, 0],
      SN: [0, 0, 2, 0, 0, 2],
      HH: [2, 1, 2, 2, 1, 2],
    },
    defaultKit: '707',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['galician', 'celtic-iberian', 'gaita', 'muineira', '6-8'],
    instruments: ['gaita gallega', 'pandeireta', 'tamboril'],
    swingable: false,
    story: '"The miller\'s dance" — Galicia\'s 6/8 answer to the Irish jig, played on the gaita gallega bagpipe. The bridge between Iberian and Celtic musical worlds.',
    relatedIds: ['jig', 'slide', 'farruca'],
  },
  {
    id: 'sardana',
    name: 'Sardana',
    origin: 'Spain · Catalonia',
    tradition: 'Catalan circle dance',
    genre: 'folk-dance',
    timeSig: '6/8',
    grouping: [3, 3],
    stepUnit: 8,
    steps: 6,
    bpm: { default: 110, min: 95, max: 125 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0],
      SN: [0, 0, 2, 0, 1, 2],
      HH: [2, 1, 2, 2, 1, 2],
    },
    defaultKit: '707',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['catalan', 'sardana', 'cobla', 'tenora', 'circle-dance'],
    instruments: ['tenora', 'tible', 'flabiol', 'tamborí'],
    swingable: false,
    story: 'Catalonia\'s national dance — danced in closed circles to the cobla ensemble\'s oboe-reed "tenora." Modest on the surface, intricately counted by dancers in silent subdivisions.',
    relatedIds: ['muineira'],
  },
  {
    id: 'jota-aragonesa',
    name: 'Jota Aragonesa',
    origin: 'Spain · Aragon',
    tradition: 'Aragonese national dance',
    genre: 'folk-dance',
    timeSig: '3/4',
    grouping: [2, 2, 2],
    stepUnit: 8,
    steps: 6,
    bpm: { default: 360, min: 280, max: 420 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 2, 0],
      HH: [2, 2, 2, 2, 2, 2],
    },
    defaultKit: '707',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['spanish', 'jota', 'aragon', 'castanets', 'rondalla'],
    instruments: ['castañuelas', 'bandurria', 'guitarra'],
    swingable: false,
    story: 'The jota of Aragon — high jumps, castanets, arms raised. A 3/4 that accelerates throughout, and the mother that bequeathed alegrías its flamenco compás.',
    relatedIds: ['alegrias', 'fandango-huelva', 'verdiales'],
  },
  {
    id: 'corri-corri',
    name: 'Corri-Corri',
    origin: 'Spain · Asturias',
    tradition: 'Asturian ritual dance',
    genre: 'folk-dance',
    timeSig: '6/8',
    grouping: [3, 3],
    stepUnit: 8,
    steps: 6,
    bpm: { default: 130, min: 115, max: 145 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0],
      SN: [0, 2, 0, 0, 2, 0],
      HH: [2, 1, 2, 2, 1, 2],
    },
    defaultKit: '707',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['asturian', 'corri-corri', 'ritual', 'pandereta'],
    instruments: ['pandereta', 'voz', 'gaita asturiana'],
    swingable: false,
    story: 'An ancient Asturian women\'s line-dance — performed without men, only tambourines and voices. Pre-Christian roots still visible in the ritual geometry of the steps.',
    relatedIds: ['muineira'],
  },
  {
    id: 'zortziko',
    name: 'Zortziko',
    origin: 'Spain · Basque Country',
    tradition: 'Basque asymmetric dance',
    genre: 'folk-dance',
    timeSig: '5/8',
    grouping: [3, 2],
    stepUnit: 8,
    steps: 5,
    bpm: { default: 180, min: 150, max: 210 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0],
      SN: [0, 1, 2, 0, 2],
      HH: [2, 1, 2, 2, 1],
    },
    defaultKit: '707',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['basque', 'zortziko', 'aksak', 'asymmetric', 'txistu'],
    instruments: ['txistu', 'tamboril', 'trikitixa'],
    swingable: false,
    story: 'The Basque 5/8 — one of Europe\'s few traditional asymmetric meters outside the Balkans. Ravel and Sarasate wrote zortzikos; the Basques have danced them for centuries.',
    relatedIds: ['pajdusko', 'aksak'],
  },
];
