import type { Pattern } from '../types';

export const INDIA_PATTERNS: Pattern[] = [
  {
    id: 'tintal',
    name: 'Tintal',
    origin: 'India · Hindustani',
    tradition: 'Tabla cycle',
    genre: 'classical',
    timeSig: '16/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 8,
    steps: 16,
    bpm: { default: 180, min: 120, max: 400 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 1, 0, 0, 0, 1, 0, 2, 0, 1, 0, 0, 0, 1, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'hindustani', 'foundation', 'classical'],
    instruments: ['tabla', 'sitar', 'sarod'],
    swingable: false,
    story: '16 beats, four vibhags, one of the most common cycles in Hindustani music. The khali on beat 9 is the moment everything relaxes before returning home.',
  },
  {
    id: 'dadra',
    name: 'Dadra',
    origin: 'India · Hindustani',
    tradition: 'Light classical / film',
    genre: 'classical',
    timeSig: '6/4',
    grouping: [3, 3],
    stepUnit: 4,
    steps: 6,
    bpm: { default: 110, min: 80, max: 140 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0],
      SN: [0, 2, 1, 0, 2, 1],
      HH: [2, 1, 2, 2, 1, 2],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'light-classical', 'thumri', 'film'],
    instruments: ['tabla', 'harmonium', 'sarangi'],
    swingable: false,
    story: 'A gentle 6-beat cycle that lilts like a waltz — the signature groove of thumri, bhajans, and romantic Bollywood ballads.',
  },
  {
    id: 'rupak',
    name: 'Rupak Tal',
    origin: 'India · Hindustani',
    tradition: 'Tabla cycle',
    genre: 'classical',
    timeSig: '7/4',
    grouping: [3, 2, 2],
    stepUnit: 4,
    steps: 7,
    bpm: { default: 90, min: 60, max: 130 },
    difficulty: 'intermediate',
    tracks: {
      KK: [0, 0, 0, 2, 0, 2, 0],
      SN: [2, 1, 1, 0, 0, 0, 0],
      HH: [1, 1, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'hindustani', 'asymmetric', 'khali-start'],
    instruments: ['tabla', 'bansuri', 'sitar'],
    swingable: false,
    story: 'Rupak is unusual — the first beat (sam) is actually a khali (empty) stroke. The cycle starts weak and resolves inward.',
  },
  {
    id: 'ektal',
    name: 'Ektal',
    origin: 'India · Hindustani',
    tradition: 'Vilambit khayal',
    genre: 'classical',
    timeSig: '12/4',
    grouping: [2, 2, 2, 2, 2, 2],
    stepUnit: 4,
    steps: 12,
    bpm: { default: 40, min: 20, max: 80 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0],
      SN: [0, 0, 0, 0, 2, 0, 2, 0, 0, 1, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'vilambit', 'khayal', 'slow'],
    instruments: ['tabla', 'sarangi', 'voice'],
    swingable: false,
    story: '12 beats, six vibhags. At vilambit tempo each beat becomes a canvas — the master tabla player elaborates endlessly between the landmarks.',
  },
  {
    id: 'jhaptal',
    name: 'Jhaptal',
    origin: 'India · Hindustani',
    tradition: 'Tabla cycle',
    genre: 'classical',
    timeSig: '10/4',
    grouping: [2, 3, 2, 3],
    stepUnit: 4,
    steps: 10,
    bpm: { default: 96, min: 60, max: 140 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 2, 0, 0, 2, 0],
      SN: [0, 1, 0, 0, 1, 0, 1, 0, 0, 1],
      HH: [2, 1, 1, 2, 1, 2, 1, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'hindustani', 'asymmetric', 'dhrupad'],
    instruments: ['tabla', 'rudra veena', 'voice'],
    swingable: false,
    story: '10 beats grouped 2+3+2+3 — the same skeleton as Ottoman Curcuna, but arrived at through a completely different tradition.',
    relatedIds: ['curcuna'],
  },
  {
    id: 'keherwa',
    name: 'Keherwa',
    origin: 'India · Hindustani',
    tradition: 'Folk / light classical',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4],
    stepUnit: 8,
    steps: 8,
    bpm: { default: 120, min: 80, max: 200 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 1, 0, 0, 2, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'folk', 'bhajan', 'qawwali', 'bollywood'],
    instruments: ['tabla', 'dholak', 'harmonium'],
    swingable: false,
    story: 'The most common tala in Indian light music — bhajans, ghazals, qawwalis, and half the Bollywood catalogue rest on this 8-beat foundation.',
  },
  {
    id: 'deepchandi',
    name: 'Deepchandi',
    origin: 'India · Hindustani',
    tradition: 'Thumri / romantic classical',
    genre: 'classical',
    timeSig: '14/4',
    grouping: [3, 4, 3, 4],
    stepUnit: 4,
    steps: 14,
    bpm: { default: 65, min: 40, max: 100 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0],
      HH: [2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'thumri', 'romantic', 'asymmetric'],
    instruments: ['tabla', 'sarangi', 'voice'],
    swingable: false,
    story: 'A majestic 14-beat tala for thumri and romantic classical forms — the alternating 3+4 grouping creates a long, lilting rocking cycle.',
  },
  {
    id: 'chautal',
    name: 'Chautal',
    origin: 'India · Hindustani',
    tradition: 'Dhrupad',
    genre: 'classical',
    timeSig: '12/4',
    grouping: [2, 2, 2, 2, 2, 2],
    stepUnit: 4,
    steps: 12,
    bpm: { default: 120, min: 80, max: 180 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 2, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['pakhawaj', 'dhrupad', 'classical'],
    instruments: ['pakhawaj', 'rudra veena', 'voice'],
    swingable: false,
    story: 'The 12-beat cycle of dhrupad — India\'s oldest surviving classical vocal form, played on the thunderous pakhawaj rather than tabla.',
  },
  {
    id: 'adi-tala',
    name: 'Adi Tala',
    origin: 'India · Carnatic',
    tradition: 'South Indian classical',
    genre: 'classical',
    timeSig: '8/4',
    grouping: [4, 2, 2],
    stepUnit: 8,
    steps: 16,
    bpm: { default: 110, min: 60, max: 160 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['mridangam', 'carnatic', 'foundation', 'classical'],
    instruments: ['mridangam', 'ghatam', 'veena'],
    swingable: false,
    story: 'The most common Carnatic tala — "adi" means "first" or "primary." 8 beats: laghu, drutam, drutam. The bedrock of South Indian classical music.',
  },
  {
    id: 'khanda-chapu',
    name: 'Khanda Chapu',
    origin: 'India · Carnatic',
    tradition: 'South Indian classical',
    genre: 'classical',
    timeSig: '5/4',
    grouping: [2, 1, 2],
    stepUnit: 8,
    steps: 10,
    bpm: { default: 120, min: 80, max: 160 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 1, 0, 0, 0, 0, 2, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['mridangam', 'carnatic', '5-beat', 'chapu'],
    instruments: ['mridangam', 'kanjira', 'voice'],
    swingable: false,
    story: '"Khanda" means five. A 5-beat Carnatic tala grouped 2+1+2 — uneven, with a distinctive hop at the single-beat middle.',
  },
];
