import type { Pattern } from '../types';

export const INDIA_PATTERNS: Pattern[] = [
  {
    id: 'tintal',
    name: 'Tintal',
    origin: 'India · Hindustani',
    tradition: 'Tabla cycle',
    genre: 'classical',
    timeSig: '16/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 8,
    steps: 16,
    bpm: { default: 180, min: 120, max: 400 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 1, 0, 0, 0, 1, 0, 2, 0, 1, 0, 0, 0, 1, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'hindustani', 'foundation', 'classical'],
    instruments: ['tabla', 'sitar', 'sarod'],
    swingable: false,
    story: '16 beats, four vibhags, one of the most common cycles in Hindustani music. The khali on beat 9 is the moment everything relaxes before returning home.',
    relatedIds: ['addha-tintal', 'tilwada', 'bollywood-classic', 'afghan-tabla-dhol'],
  },
  {
    id: 'dadra',
    name: 'Dadra',
    origin: 'India · Hindustani',
    tradition: 'Light classical / film',
    genre: 'classical',
    timeSig: '6/4',
    grouping: [3, 3],
    stepUnit: 4,
    steps: 6,
    bpm: { default: 110, min: 80, max: 140 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0],
      SN: [0, 2, 1, 0, 2, 1],
      HH: [2, 1, 2, 2, 1, 2],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'light-classical', 'thumri', 'film'],
    instruments: ['tabla', 'harmonium', 'sarangi'],
    swingable: false,
    story: 'A gentle 6-beat cycle that lilts like a waltz — the signature groove of thumri, bhajans, and romantic Bollywood ballads.',
    relatedIds: ['keherwa', 'reng', 'mahur-68', 'afghan-tabla-dhol'],
  },
  {
    id: 'rupak',
    name: 'Rupak Tal',
    origin: 'India · Hindustani',
    tradition: 'Tabla cycle',
    genre: 'classical',
    timeSig: '7/4',
    grouping: [3, 2, 2],
    stepUnit: 4,
    steps: 7,
    bpm: { default: 90, min: 60, max: 130 },
    difficulty: 'intermediate',
    tracks: {
      KK: [0, 0, 0, 2, 0, 2, 0],
      SN: [2, 1, 1, 0, 0, 0, 0],
      HH: [1, 1, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'hindustani', 'asymmetric', 'khali-start'],
    instruments: ['tabla', 'bansuri', 'sitar'],
    swingable: false,
    story: 'Rupak is unusual — the first beat (sam) is actually a khali (empty) stroke. The cycle starts weak and resolves inward.',
  },
  {
    id: 'ektal',
    name: 'Ektal',
    origin: 'India · Hindustani',
    tradition: 'Vilambit khayal',
    genre: 'classical',
    timeSig: '12/4',
    grouping: [2, 2, 2, 2, 2, 2],
    stepUnit: 4,
    steps: 12,
    bpm: { default: 40, min: 20, max: 80 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0],
      SN: [0, 0, 0, 0, 2, 0, 2, 0, 0, 1, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'vilambit', 'khayal', 'slow'],
    instruments: ['tabla', 'sarangi', 'voice'],
    swingable: false,
    story: '12 beats, six vibhags. At vilambit tempo each beat becomes a canvas — the master tabla player elaborates endlessly between the landmarks.',
  },
  {
    id: 'jhaptal',
    name: 'Jhaptal',
    origin: 'India · Hindustani',
    tradition: 'Tabla cycle',
    genre: 'classical',
    timeSig: '10/4',
    grouping: [2, 3, 2, 3],
    stepUnit: 4,
    steps: 10,
    bpm: { default: 96, min: 60, max: 140 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 2, 0, 0, 2, 0],
      SN: [0, 1, 0, 0, 1, 0, 1, 0, 0, 1],
      HH: [2, 1, 1, 2, 1, 2, 1, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'hindustani', 'asymmetric', 'dhrupad'],
    instruments: ['tabla', 'rudra veena', 'voice'],
    swingable: false,
    story: '10 beats grouped 2+3+2+3 — the same skeleton as Ottoman Curcuna, but arrived at through a completely different tradition.',
    relatedIds: ['curcuna'],
  },
  {
    id: 'keherwa',
    name: 'Keherwa',
    origin: 'India · Hindustani',
    tradition: 'Folk / light classical',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4],
    stepUnit: 8,
    steps: 8,
    bpm: { default: 120, min: 80, max: 200 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 1, 0, 0, 2, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'folk', 'bhajan', 'qawwali', 'bollywood'],
    instruments: ['tabla', 'dholak', 'harmonium'],
    swingable: false,
    story: 'The most common tala in Indian light music — bhajans, ghazals, qawwalis, and half the Bollywood catalogue rest on this 8-beat foundation.',
    relatedIds: ['qawwali', 'bollywood-classic', 'dadra', 'afghan-tabla-dhol'],
  },
  {
    id: 'deepchandi',
    name: 'Deepchandi',
    origin: 'India · Hindustani',
    tradition: 'Thumri / romantic classical',
    genre: 'classical',
    timeSig: '14/4',
    grouping: [3, 4, 3, 4],
    stepUnit: 4,
    steps: 14,
    bpm: { default: 65, min: 40, max: 100 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0],
      HH: [2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'thumri', 'romantic', 'asymmetric'],
    instruments: ['tabla', 'sarangi', 'voice'],
    swingable: false,
    story: 'A majestic 14-beat tala for thumri and romantic classical forms — the alternating 3+4 grouping creates a long, lilting rocking cycle.',
  },
  {
    id: 'chautal',
    name: 'Chautal',
    origin: 'India · Hindustani',
    tradition: 'Dhrupad',
    genre: 'classical',
    timeSig: '12/4',
    grouping: [2, 2, 2, 2, 2, 2],
    stepUnit: 4,
    steps: 12,
    bpm: { default: 120, min: 80, max: 180 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 2, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['pakhawaj', 'dhrupad', 'classical'],
    instruments: ['pakhawaj', 'rudra veena', 'voice'],
    swingable: false,
    story: 'The 12-beat cycle of dhrupad — India\'s oldest surviving classical vocal form, played on the thunderous pakhawaj rather than tabla.',
  },
  {
    id: 'adi-tala',
    name: 'Adi Tala',
    origin: 'India · Carnatic',
    tradition: 'South Indian classical',
    genre: 'classical',
    timeSig: '8/4',
    grouping: [4, 2, 2],
    stepUnit: 8,
    steps: 16,
    bpm: { default: 110, min: 60, max: 160 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['mridangam', 'carnatic', 'foundation', 'classical'],
    instruments: ['mridangam', 'ghatam', 'veena'],
    swingable: false,
    story: 'The most common Carnatic tala — "adi" means "first" or "primary." 8 beats: laghu, drutam, drutam. The bedrock of South Indian classical music.',
  },
  {
    id: 'khanda-chapu',
    name: 'Khanda Chapu',
    origin: 'India · Carnatic',
    tradition: 'South Indian classical',
    genre: 'classical',
    timeSig: '5/4',
    grouping: [2, 1, 2],
    stepUnit: 8,
    steps: 10,
    bpm: { default: 120, min: 80, max: 160 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 1, 0, 0, 0, 0, 2, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['mridangam', 'carnatic', '5-beat', 'chapu'],
    instruments: ['mridangam', 'kanjira', 'voice'],
    swingable: false,
    story: '"Khanda" means five. A 5-beat Carnatic tala grouped 2+1+2 — uneven, with a distinctive hop at the single-beat middle.',
  },
  {
    id: 'sultaal',
    name: 'Sultaal',
    origin: 'India · Hindustani',
    tradition: 'Dhrupad / pakhawaj',
    genre: 'classical',
    timeSig: '10/4',
    grouping: [2, 2, 2, 2, 2],
    stepUnit: 4,
    steps: 10,
    bpm: { default: 80, min: 60, max: 140 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 0, 2, 0, 2, 0, 0, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['pakhawaj', 'dhrupad', 'symmetric'],
    instruments: ['pakhawaj', 'rudra veena', 'voice'],
    swingable: false,
    story: '10 beats in five equal vibhags of 2 — a martial, processional cousin to Jhaptal. The perfect symmetry gives Sultaal the grandeur of Dhrupad.',
    relatedIds: ['jhaptal', 'chautal'],
  },
  {
    id: 'dhamar',
    name: 'Dhamar',
    origin: 'India · Hindustani',
    tradition: 'Dhrupad (Holi songs)',
    genre: 'classical',
    timeSig: '14/4',
    grouping: [5, 2, 3, 4],
    stepUnit: 4,
    steps: 14,
    bpm: { default: 80, min: 40, max: 120 },
    difficulty: 'advanced',
    tracks: {
      KK: [0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
      SN: [2, 0, 0, 0, 2, 0, 0, 0, 2, 1, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['pakhawaj', 'dhrupad', 'holi', 'asymmetric'],
    instruments: ['pakhawaj', 'voice', 'rudra veena'],
    swingable: false,
    story: '14 beats grouped 5+2+3+4 — the tala of Dhamar songs celebrating Krishna playing Holi. The stumbling asymmetry captures the joyful chaos of the festival of colors.',
    relatedIds: ['chautal', 'deepchandi'],
  },
  {
    id: 'addha-tintal',
    name: 'Addha (Drut Tintal)',
    origin: 'India · Hindustani',
    tradition: 'Fast khayal',
    genre: 'classical',
    timeSig: '16/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 8,
    steps: 16,
    bpm: { default: 200, min: 140, max: 260 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0],
      SN: [0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'drut', 'khayal', 'fast'],
    instruments: ['tabla', 'sitar', 'voice'],
    swingable: false,
    story: 'Tintal at breakneck speed. The bols shorten to "Dha Dhi Ta Dha" — crisp syllables that articulate cleanly as singer and tabla trade virtuosic volleys.',
    relatedIds: ['tintal'],
  },
  {
    id: 'jhumra',
    name: 'Jhumra',
    origin: 'India · Hindustani',
    tradition: 'Vilambit khayal',
    genre: 'classical',
    timeSig: '14/4',
    grouping: [3, 4, 3, 4],
    stepUnit: 4,
    steps: 14,
    bpm: { default: 45, min: 30, max: 80 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 0, 0, 2, 1, 0, 2, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'vilambit', 'khayal', 'rare'],
    instruments: ['tabla', 'sarangi', 'voice'],
    swingable: false,
    story: 'A rare 14-beat Hindustani tala shaped like Deepchandi (3+4+3+4) but stretched glacially slow — each matra breathes for seconds, giving the vocalist endless space to ornament.',
    relatedIds: ['deepchandi', 'ektal'],
  },
  {
    id: 'tilwada',
    name: 'Tilwada',
    origin: 'India · Hindustani',
    tradition: 'Medium khayal',
    genre: 'classical',
    timeSig: '16/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 4,
    steps: 16,
    bpm: { default: 70, min: 50, max: 110 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2],
      SN: [0, 0, 2, 0, 0, 0, 2, 1, 2, 0, 2, 1, 0, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'khayal', 'medium-tempo'],
    instruments: ['tabla', 'sarangi', 'voice'],
    swingable: false,
    story: 'A 16-beat cousin of Tintal — same vibhag skeleton but the theka is denser, filled with connecting strokes. The tabla breathes between the singer\'s long-held notes.',
    relatedIds: ['tintal'],
  },
  {
    id: 'teevra',
    name: 'Teevra',
    origin: 'India · Hindustani',
    tradition: 'Pakhawaj / dhrupad',
    genre: 'classical',
    timeSig: '7/4',
    grouping: [3, 2, 2],
    stepUnit: 4,
    steps: 7,
    bpm: { default: 100, min: 60, max: 140 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0],
      SN: [0, 2, 1, 0, 2, 0, 2],
      HH: [2, 1, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['pakhawaj', 'dhrupad', 'asymmetric'],
    instruments: ['pakhawaj', 'rudra veena', 'voice'],
    swingable: false,
    story: 'A 7-beat pakhawaj tala grouped 3+2+2. "Teevra" means sharp or intense — the asymmetry lends dhrupad compositions a bracing, forward lean.',
    relatedIds: ['rupak', 'misra-chapu'],
  },
  {
    id: 'punjabi-tal',
    name: 'Punjabi Tal',
    origin: 'India · Hindustani',
    tradition: 'Sikh kirtan / light classical',
    genre: 'devotional',
    timeSig: '16/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 8,
    steps: 16,
    bpm: { default: 160, min: 100, max: 220 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'sikh', 'kirtan', 'punjabi'],
    instruments: ['tabla', 'dholak', 'harmonium'],
    swingable: false,
    story: 'A 16-beat tala at home in Sikh kirtan and Punjabi light classical. Brisker and more insistent than Tintal, with the syncopated lean of Punjab\'s folk heritage.',
    relatedIds: ['tintal', 'bhangra'],
  },
  {
    id: 'misra-chapu',
    name: 'Misra Chapu',
    origin: 'India · Carnatic',
    tradition: 'South Indian classical',
    genre: 'classical',
    timeSig: '7/4',
    grouping: [3, 2, 2],
    stepUnit: 8,
    steps: 14,
    bpm: { default: 110, min: 80, max: 160 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['mridangam', 'carnatic', 'chapu', '7-beat'],
    instruments: ['mridangam', 'kanjira', 'voice'],
    swingable: false,
    story: '"Misra" means mixed — tisra (3) blended with chatusra (2+2). Kept with waves only, the tala floats in suspension, a hypnotic lilt beloved in Bharatanatyam choreography.',
    relatedIds: ['khanda-chapu', 'rupak'],
  },
  {
    id: 'rupaka-tala',
    name: 'Rupaka Tala',
    origin: 'India · Carnatic',
    tradition: 'South Indian classical',
    genre: 'classical',
    timeSig: '3/4',
    grouping: [1, 2],
    stepUnit: 4,
    steps: 3,
    bpm: { default: 140, min: 80, max: 200 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 2, 0],
      SN: [0, 0, 2],
      HH: [2, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['mridangam', 'carnatic', 'short-cycle'],
    instruments: ['mridangam', 'kanjira', 'veena'],
    swingable: false,
    story: 'The second most common Carnatic tala after Adi. Drutam (1) plus laghu (2) creates a brisk triple-time cycle — the engine behind many Tyagaraja kritis.',
    relatedIds: ['adi-tala'],
  },
  {
    id: 'eka-tala',
    name: 'Eka Tala',
    origin: 'India · Carnatic',
    tradition: 'South Indian classical',
    genre: 'classical',
    timeSig: '4/4',
    grouping: [4],
    stepUnit: 4,
    steps: 4,
    bpm: { default: 100, min: 60, max: 160 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0],
      SN: [0, 1, 2, 1],
      HH: [2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['mridangam', 'carnatic', 'simplest'],
    instruments: ['mridangam', 'ghatam', 'voice'],
    swingable: false,
    story: '"Eka" means one — a single laghu of 4 counts. The shortest Carnatic tala, used for devotional songs and learning exercises where the cycle turns over every bar.',
    relatedIds: ['adi-tala', 'rupaka-tala'],
  },
  {
    id: 'konnakol-takadimi',
    name: 'Konnakol · Ta-Ka-Di-Mi',
    origin: 'India · Carnatic',
    tradition: 'Vocal percussion (solkattu)',
    genre: 'classical',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 440, min: 240, max: 640 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['konnakol', 'solkattu', 'carnatic', 'chatusra'],
    instruments: ['voice', 'mridangam'],
    swingable: false,
    story: 'Chatusra gati — four syllables per beat. "Ta-Ka-Di-Mi" is the default subdivision of Carnatic music, spoken, clapped, and drummed as the foundation of all rhythmic training.',
    relatedIds: ['adi-tala', 'konnakol-takita'],
  },
  {
    id: 'konnakol-takita',
    name: 'Konnakol · Ta-Ki-Ta',
    origin: 'India · Carnatic',
    tradition: 'Vocal percussion (solkattu)',
    genre: 'classical',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 16,
    steps: 12,
    bpm: { default: 440, min: 240, max: 720 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2],
      HH: [2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['konnakol', 'solkattu', 'carnatic', 'tisra', 'triplet'],
    instruments: ['voice', 'mridangam'],
    swingable: false,
    story: 'Tisra gati — three syllables per beat. "Ta-Ki-Ta" is the triplet engine of Carnatic music, the gateway to polyrhythmic math and the lilting swing of South Indian groove.',
    relatedIds: ['konnakol-takadimi'],
  },
  {
    id: 'bhangra',
    name: 'Bhangra · Chaal',
    origin: 'India / Pakistan · Punjab',
    tradition: 'Dhol folk dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 380, min: 320, max: 440 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['dhol', 'punjabi', 'folk', 'harvest', 'bhangra'],
    instruments: ['dhol', 'chimta', 'algoza'],
    swingable: false,
    story: 'The thunderous dhol groove of Punjab. "Chaal" means walk — dagga heavy stick on the bass head, tilli thin stick on the treble. The half-time feel sounds faster as the dance accelerates.',
    relatedIds: ['punjabi-tal', 'dhamaal-sufi'],
  },
  {
    id: 'garba',
    name: 'Garba',
    origin: 'India · Gujarat',
    tradition: 'Navratri festival dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 600, min: 480, max: 800 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
      CP: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['dhol', 'gujarati', 'navratri', 'festival', 'unesco'],
    instruments: ['dhol', 'dholak', 'manjira'],
    swingable: false,
    story: 'Danced in concentric circles around a clay lamp during the nine nights of Navratri. The tempo builds through the night — UNESCO inscribed Garba as Intangible Cultural Heritage in 2023.',
    relatedIds: ['dandiya-raas', 'bhangra'],
  },
  {
    id: 'dandiya-raas',
    name: 'Dandiya Raas',
    origin: 'India · Gujarat',
    tradition: 'Stick dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 720, min: 600, max: 880 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0],
      SN: [0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 2, 2],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['dhol', 'gujarati', 'stick-dance', 'navratri'],
    instruments: ['dhol', 'dandiya sticks', 'harmonium'],
    swingable: false,
    story: 'The late-night escalation of Garba — partners face off striking decorated sticks in a "ta-ta, ta-ta-ta" pattern. Pure exhilaration as the circles break into partner formations.',
    relatedIds: ['garba'],
  },
  {
    id: 'lavani',
    name: 'Lavani',
    origin: 'India · Maharashtra',
    tradition: 'Theatrical folk dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 560, min: 480, max: 680 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['dholki', 'marathi', 'theater', 'ghungroo'],
    instruments: ['dholki', 'manjira', 'ghungroo'],
    swingable: false,
    story: 'Maharashtra\'s galloping dholki rhythm for Lavani — poetry, song, and dance fused. Ankle bells (ghungroo) interlock with the drum while the performer spins relentlessly.',
  },
  {
    id: 'kalbelia',
    name: 'Kalbelia',
    origin: 'India · Rajasthan',
    tradition: 'Snake-charmer dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 580, min: 520, max: 680 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 0, 2],
      SN: [0, 2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['dholak', 'rajasthani', 'desert', 'unesco'],
    instruments: ['dholak', 'pungi', 'khartal'],
    swingable: false,
    story: 'The sinuous Rajasthani dance of the Kalbeliya community — movement mimics the serpent. UNESCO-listed. The pungi (snake-charmer\'s pipe) sings over a dholak driving in uneven accents.',
    relatedIds: ['rajasthani-manganiar'],
  },
  {
    id: 'qawwali',
    name: 'Qawwali',
    origin: 'India / Pakistan · Sufi',
    tradition: 'Sufi devotional',
    genre: 'devotional',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 400, min: 320, max: 560 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
      CP: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'sufi', 'devotional', 'keherwa-derived'],
    instruments: ['tabla', 'dholak', 'harmonium', 'handclaps'],
    swingable: false,
    story: 'The propulsive Sufi devotional groove of the shrines — Keherwa tala driven hard, with group handclaps riding the 2 and 4. Nusrat Fateh Ali Khan carried this rhythm to the world.',
    relatedIds: ['keherwa', 'dhamaal-sufi'],
  },
  {
    id: 'bollywood-classic',
    name: 'Bollywood · Classic 4/4',
    origin: 'India · Mumbai',
    tradition: 'Hindi film music',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 460, min: 360, max: 560 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'dholak', 'bollywood', 'film', 'keherwa-derived'],
    instruments: ['tabla', 'dholak', 'harmonium', 'strings'],
    swingable: false,
    story: 'The timeless Bollywood groove from the golden era through today — Keherwa tala stretched into a punchy, cinematic 16-step pattern that carries half the Hindi film catalogue.',
    relatedIds: ['keherwa'],
  },
  {
    id: 'rajasthani-manganiar',
    name: 'Rajasthani Manganiar',
    origin: 'India · Rajasthan',
    tradition: 'Thar desert folk',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 480, min: 400, max: 600 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['dholak', 'khartal', 'rajasthani', 'desert', 'hereditary-musicians'],
    instruments: ['dholak', 'khartal', 'kamaicha'],
    swingable: false,
    story: 'The hereditary Manganiar musicians of the Thar Desert — dholak pulse underneath the shimmering clack of khartal wooden castanets. Centuries of Rajput patronage, now a global concert tradition.',
    relatedIds: ['kalbelia'],
  },
  {
    id: 'dhamaal-sufi',
    name: 'Dhamaal',
    origin: 'Pakistan · Sufi',
    tradition: 'Sufi ecstatic dance',
    genre: 'devotional',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 460, min: 400, max: 520 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'PK',
    region: 'india',
    tags: ['dhol', 'sufi', 'ecstatic', 'lahore'],
    instruments: ['dhol', 'naqqara', 'handclaps'],
    swingable: false,
    story: 'The ecstatic Sufi dhol rhythm of the shrines — associated with Shah Hussain\'s urs in Lahore. Devotees spin themselves into trance as the dhol\'s heavy stick drives the circle harder and harder.',
    relatedIds: ['bhangra', 'qawwali'],
  },
  {
    id: 'ghoomar',
    name: 'Ghoomar',
    origin: 'India · Rajasthan',
    tradition: 'Spinning dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 500, min: 440, max: 560 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['dhol', 'rajasthani', 'royal', 'wedding'],
    instruments: ['dhol', 'dholak', 'harmonium'],
    swingable: false,
    story: 'The Rajput women\'s spinning dance — wide circular steps in flowing skirts, performed at weddings and festivals. Elegant and graceful where Bhangra is thunderous.',
    relatedIds: ['kalbelia', 'rajasthani-manganiar'],
  },
];
