import type { Pattern } from '../types';

export const INTERNET_BORN_PATTERNS: Pattern[] = [
  // ============================================================
  // Vaporwave family
  // ============================================================
  {
    id: 'vaporwave',
    name: 'Vaporwave / Mallsoft',
    origin: 'Internet · Bandcamp / Tumblr',
    tradition: 'Vaporwave',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 280, min: 240, max: 320 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
    },
    defaultKit: '909',
    region: 'internet-born',
    tags: ['vaporwave', 'mallsoft', 'slowed', 'aesthetic'],
    instruments: ['LinnDrum', 'DMX', 'tape'],
    swingable: false,
    story: 'Slowed-and-pitched 1980s corporate muzak running through an abandoned shopping mall at 3am. LinnDrum samples drenched in reverb and longing.',
  },
  {
    id: 'future-funk',
    name: 'Future Funk',
    origin: 'Internet · YouTube / Bandcamp',
    tradition: 'Future funk',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 488, min: 472, max: 512 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      CP: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
      OH: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
    },
    defaultKit: '909',
    region: 'internet-born',
    tags: ['future-funk', 'city-pop', 'sidechain', 'macross-82-99'],
    instruments: ['909', 'sample', 'filter-sweep'],
    swingable: false,
    story: 'Vaporwave\'s dance-floor descendant — 1980s Japanese city pop chopped, pitched up and layered with sidechain-pumped French house drums.',
    relatedIds: ['vaporwave', 'disco-classic', 'nightcore'],
  },

  // ============================================================
  // Lo-fi
  // ============================================================
  {
    id: 'lofi-hiphop-standard',
    name: 'Lo-fi Hip-Hop',
    origin: 'Internet · YouTube (Lofi Girl)',
    tradition: 'Lo-fi beats',
    genre: 'hip-hop',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 312, min: 280, max: 340 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 1],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '808',
    region: 'internet-born',
    tags: ['lofi', 'lofi-girl', 'study-beats', 'chill'],
    instruments: ['MPC', 'vinyl crackle', 'Rhodes'],
    swingable: true,
    story: 'The beat 50,000 concurrent YouTube viewers studied to. J Dilla-descended "drunken" timing, warm tape hiss, and a cat-girl studying at her desk forever.',
    relatedIds: ['hiphop-lofi'],
  },

  // ============================================================
  // Nightcore / speed-up
  // ============================================================
  {
    id: 'nightcore',
    name: 'Nightcore',
    origin: 'Internet · YouTube',
    tradition: 'Nightcore',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 700, min: 640, max: 720 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      CP: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
      OH: [0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0],
    },
    defaultKit: '909',
    region: 'internet-born',
    tags: ['nightcore', 'sped-up', 'anime', 'eurodance'],
    instruments: ['909', 'supersaw', 'vocal'],
    swingable: false,
    story: 'A Norwegian school project turned global YouTube genre — any trance track sped 25% with pitch raised to chipmunk pop, paired with anime thumbnails.',
    relatedIds: ['hyperpop', 'happy-hardcore', 'future-funk', 'trance-classic'],
  },

  // ============================================================
  // Hyperpop
  // ============================================================
  {
    id: 'hyperpop',
    name: 'Hyperpop',
    origin: 'Internet · SoundCloud / Spotify',
    tradition: '100 gecs · PC Music',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 620, min: 560, max: 680 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 0, 2, 0],
      CP: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2],
    },
    defaultKit: '808',
    region: 'internet-born',
    tags: ['hyperpop', '100-gecs', 'pc-music', 'sophie', 'distortion'],
    instruments: ['808', 'supersaw', 'bitcrush', 'vocal chop'],
    swingable: false,
    story: '100 gecs and PC Music blending trap, happy hardcore, ska-punk and nightcore in a sonic blender set on fire. Genre-shift within the bar is the point.',
    relatedIds: ['nightcore', 'happy-hardcore', 'hiphop-trap-triplet', 'future-bass'],
  },

  // ============================================================
  // Phonk family
  // ============================================================
  {
    id: 'phonk-drift',
    name: 'Drift Phonk',
    origin: 'Internet · YouTube / TikTok',
    tradition: 'KORDHELL · drift phonk',
    genre: 'hip-hop',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 552, min: 540, max: 580 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      CP: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
      OH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '808',
    region: 'internet-born',
    tags: ['phonk', 'drift', 'kordhell', 'cowbell', 'tiktok'],
    instruments: ['808', 'saturated cowbell'],
    swingable: false,
    story: 'KORDHELL\'s "Murder In My Mind" soundtracked a million car-drift videos — relentless 8th-note cowbells distorted until they dominate the entire mix.',
    relatedIds: ['hiphop-phonk', 'phonk-brazilian', 'phonk-fish', 'hiphop-trap'],
  },
  {
    id: 'phonk-brazilian',
    name: 'Brazilian Phonk',
    origin: 'Internet · TikTok / Brazil',
    tradition: 'Phonk funk · MC GW',
    genre: 'hip-hop',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 580, min: 560, max: 620 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0],
      CP: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
      OH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '808',
    country: 'BR',
    region: 'internet-born',
    tags: ['phonk', 'brazilian', 'mc-gw', 'tamborzao', 'tiktok'],
    instruments: ['808', 'cowbell', 'agogo'],
    swingable: false,
    story: 'Drift phonk collides with Rio baile funk — tamborzão kick syncopation under distorted 808 cowbells. Gym TikTok\'s soundtrack of choice.',
    relatedIds: ['baile-funk-tamborzao', 'phonk-drift', 'hiphop-phonk', 'phonk-fish'],
  },
  {
    id: 'phonk-fish',
    name: 'Fish Phonk',
    origin: 'Internet · Brazil / TikTok',
    tradition: 'Fishphonk · hyper-drift',
    genre: 'hip-hop',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 680, min: 640, max: 720 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
      CP: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
      OH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '808',
    country: 'BR',
    region: 'internet-born',
    tags: ['phonk', 'fishphonk', 'hyper-drift', 'brazilian'],
    instruments: ['808', 'distorted cowbell', 'vocal chop'],
    swingable: false,
    story: 'The hyper-accelerated Brazilian mutation of drift phonk — every 16th sub-divided, cowbells saturated past clipping, built for TikTok attention spans.',
    relatedIds: ['phonk-drift', 'phonk-brazilian'],
  },

  // ============================================================
  // SoundCloud / bedroom / platform-shaped
  // ============================================================
  {
    id: 'soundcloud-rap',
    name: 'SoundCloud Rap',
    origin: 'Internet · SoundCloud',
    tradition: 'SoundCloud rap',
    genre: 'hip-hop',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 560, min: 520, max: 600 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 0, 2, 0],
      CP: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
    },
    defaultKit: '808',
    country: 'US',
    region: 'internet-born',
    tags: ['soundcloud-rap', 'lil-pump', 'xxxtentacion', 'distorted-808'],
    instruments: ['808', 'hi-hat', 'clap'],
    swingable: false,
    story: 'Lil Pump, XXXTentacion, Smokepurpp, Lil Peep — teenagers bypassing labels entirely by clipping their 808s into oblivion on SoundCloud.',
  },
  {
    id: 'bedroom-pop',
    name: 'Bedroom Pop',
    origin: 'Internet · YouTube / Spotify',
    tradition: 'Bedroom pop',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 392, min: 360, max: 420 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
      HH: [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
      CP: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    defaultKit: '808',
    region: 'internet-born',
    tags: ['bedroom-pop', 'clairo', 'boy-pablo', 'webcam'],
    instruments: ['drum machine', 'tambourine', 'guitar'],
    swingable: false,
    story: 'Clairo\'s "Pretty Girl" recorded on a webcam — music made in actual bedrooms on cheap gear. The imperfections are the aesthetic, authenticity over slickness.',
  },

  // ============================================================
  // Footwork variants
  // ============================================================
  {
    id: 'footwork-internet',
    name: 'Footwork (Internet Variants)',
    origin: 'Internet · Global diaspora',
    tradition: 'Post-Rashad footwork',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 640, min: 600, max: 680 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 2],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
      CP: [0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0],
    },
    defaultKit: '808',
    region: 'internet-born',
    tags: ['footwork', 'juke', 'teklife', 'internet', 'chicago-diaspora'],
    instruments: ['808', 'vocal chop'],
    swingable: false,
    story: 'Teklife\'s post-Rashad global diaspora — Chicago footwork mutated by Tokyo, Lisbon and London producers on SoundCloud, pushing beat-skipping into new territory.',
    relatedIds: ['footwork-juke', 'footwork'],
  },

  // ============================================================
  // Extreme / rhythm game
  // ============================================================
  {
    id: 'mashcore',
    name: 'Mashcore / Lolicore',
    origin: 'Internet · Japanese BMS',
    tradition: 'Mashcore · breakcore',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 880, min: 800, max: 960 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0],
      SN: [0, 2, 0, 2, 0, 0, 2, 2, 0, 0, 2, 0, 2, 2, 0, 0],
      HH: [2, 0, 0, 2, 2, 0, 2, 0, 0, 2, 2, 0, 2, 0, 0, 2],
      CP: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
    },
    defaultKit: '909',
    country: 'JP',
    region: 'internet-born',
    tags: ['mashcore', 'lolicore', 'breakcore', 'amen', 'bms'],
    instruments: ['chopped amen', 'gabber kick', 'anime vocal'],
    swingable: false,
    story: 'Japanese breakcore fused with anime samples — Goreshit, Sewerslvt, DJ Sharpnel chopping the Amen break past 220 BPM into textural wash.',
    relatedIds: ['dnb-amen-break'],
  },
];
