import type { Pattern } from '../types';

export const PERSIA_PATTERNS: Pattern[] = [
  {
    id: 'reng',
    name: 'Reng',
    origin: 'Iran',
    tradition: 'Persian classical finale',
    genre: 'classical',
    timeSig: '6/8',
    grouping: [3, 3],
    stepUnit: 8,
    steps: 6,
    bpm: { default: 150, min: 120, max: 200 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0],
      SN: [0, 0, 2, 0, 2, 1],
      HH: [2, 1, 2, 2, 1, 2],
    },
    defaultKit: 'frameDrum',
    country: 'IR',
    region: 'persia',
    tags: ['classical', 'dastgah', 'dance', 'finale'],
    instruments: ['tombak', 'daf', 'tar'],
    swingable: false,
    story: 'The dance finale of a Persian dastgah suite — light, playful, a release after the meditative avaz sections.',
  },
  {
    id: 'tasnif-4-4',
    name: 'Tasnif',
    origin: 'Iran',
    tradition: 'Persian art song',
    genre: 'classical',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 90, min: 70, max: 120 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'IR',
    region: 'persia',
    tags: ['art-song', 'classical', 'vocal'],
    instruments: ['tombak', 'tar', 'setar'],
    swingable: false,
    story: 'The metric art-song form at the heart of Persian classical music — a poem set within a rhythmic cycle, where tombak and voice weave together.',
  },
  {
    id: 'chaharmezrab',
    name: 'Chaharmezrab',
    origin: 'Iran',
    tradition: 'Persian virtuoso piece',
    genre: 'classical',
    timeSig: '6/16',
    grouping: [3, 3],
    stepUnit: 16,
    steps: 6,
    bpm: { default: 180, min: 140, max: 240 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0],
      SN: [0, 2, 1, 0, 2, 1],
      HH: [2, 2, 2, 2, 2, 2],
    },
    defaultKit: 'frameDrum',
    country: 'IR',
    region: 'persia',
    tags: ['virtuoso', 'fast', 'dastgah'],
    instruments: ['santur', 'tombak', 'tar'],
    swingable: false,
    story: '"Four-plectrum-strokes" — a fast, virtuosic instrumental étude built on a repeating rhythmic cell, used to display technique in a dastgah.',
  },
];
