import type { Pattern } from '../types';

export const TURKEY_OTTOMAN_PATTERNS: Pattern[] = [
  {
    id: 'karsilama',
    name: 'Karşılama',
    origin: 'Turkey · Thrace',
    tradition: 'Wedding dance',
    genre: 'folk-dance',
    timeSig: '9/8',
    grouping: [2, 2, 2, 3],
    stepUnit: 8,
    steps: 9,
    bpm: { default: 276, min: 200, max: 360 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 2, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 1, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['wedding', 'dance', 'romani', 'thracian'],
    instruments: ['frame drum', 'bağlama', 'clarinet'],
    swingable: false,
    story:
      'Karşılama means "face to face" — the dance has two rows of dancers greeting each other. The 2+2+2+3 grouping gives the whole thing its iconic skip.',
    relatedIds: ['daichovo'],
  },
  {
    id: 'horon',
    name: 'Horon',
    origin: 'Turkey · Black Sea',
    tradition: 'Coastal line dance',
    genre: 'folk-dance',
    timeSig: '7/8',
    grouping: [2, 2, 3],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 360, min: 280, max: 460 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 0, 1, 1],
      HH: [2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['dance', 'line-dance', 'coastal'],
    instruments: ['kemençe', 'davul', 'tulum'],
    swingable: false,
    story: 'Horon is the fisherman shaking on a trawler deck. Played at Mach speed on kemençe and davul.',
    relatedIds: ['ruchenitsa'],
  },
  {
    id: 'turk-aksagi',
    name: 'Türk Aksağı',
    origin: 'Turkey',
    tradition: 'Ottoman / folk',
    genre: 'classical',
    timeSig: '5/8',
    grouping: [2, 3],
    stepUnit: 8,
    steps: 5,
    bpm: { default: 260, min: 200, max: 340 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 1],
      HH: [2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['ottoman', 'asymmetric'],
    instruments: ['kudüm', 'def', 'ud'],
    swingable: false,
    story: 'The Turkish limp in 5 — two then three, forever rolling forward.',
  },
  {
    id: 'curcuna',
    name: 'Curcuna',
    origin: 'Turkey',
    tradition: 'Ottoman classical',
    genre: 'classical',
    timeSig: '10/8',
    grouping: [2, 3, 2, 3],
    stepUnit: 8,
    steps: 10,
    bpm: { default: 200, min: 140, max: 260 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 0, 2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 1, 0, 1, 0, 1, 1],
      HH: [2, 1, 2, 1, 1, 2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['ottoman', 'asymmetric', 'classical'],
    instruments: ['kudüm', 'bendir', 'ney'],
    swingable: false,
    story: 'Two Türk Aksağıs stacked — 2+3+2+3. The archetypal Ottoman asymmetric.',
  },
  {
    id: 'duyek',
    name: 'Düyek',
    origin: 'Turkey',
    tradition: 'Ottoman folk',
    genre: 'folk-dance',
    timeSig: '8/8',
    grouping: [4, 4],
    stepUnit: 8,
    steps: 8,
    bpm: { default: 220, min: 140, max: 280 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0],
      HH: [1, 1, 1, 1, 1, 1, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['beginner', 'foundation', 'darbuka'],
    instruments: ['darbuka', 'ud'],
    swingable: false,
    story: 'The first rhythm every darbuka student learns. A foundation stone of Ottoman music.',
  },
];
