import type { Pattern } from '../types';

export const TURKEY_OTTOMAN_PATTERNS: Pattern[] = [
  {
    id: 'karsilama',
    name: 'Karşılama',
    origin: 'Turkey · Thrace',
    tradition: 'Wedding dance',
    genre: 'folk-dance',
    timeSig: '9/8',
    grouping: [2, 2, 2, 3],
    stepUnit: 8,
    steps: 9,
    bpm: { default: 276, min: 200, max: 360 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 2, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 1, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['wedding', 'dance', 'romani', 'thracian'],
    instruments: ['frame drum', 'bağlama', 'clarinet'],
    swingable: false,
    story:
      'Karşılama means "face to face" — the dance has two rows of dancers greeting each other. The 2+2+2+3 grouping gives the whole thing its iconic skip.',
    relatedIds: ['daichovo'],
  },
  {
    id: 'horon',
    name: 'Horon',
    origin: 'Turkey · Black Sea',
    tradition: 'Coastal line dance',
    genre: 'folk-dance',
    timeSig: '7/8',
    grouping: [2, 2, 3],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 360, min: 280, max: 460 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 0, 1, 1],
      HH: [2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['dance', 'line-dance', 'coastal'],
    instruments: ['kemençe', 'davul', 'tulum'],
    swingable: false,
    story: 'Horon is the fisherman shaking on a trawler deck. Played at Mach speed on kemençe and davul.',
    relatedIds: ['ruchenitsa'],
  },
  {
    id: 'turk-aksagi',
    name: 'Türk Aksağı',
    origin: 'Turkey',
    tradition: 'Ottoman / folk',
    genre: 'classical',
    timeSig: '5/8',
    grouping: [2, 3],
    stepUnit: 8,
    steps: 5,
    bpm: { default: 260, min: 200, max: 340 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 1],
      HH: [2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['ottoman', 'asymmetric'],
    instruments: ['kudüm', 'def', 'ud'],
    swingable: false,
    story: 'The Turkish limp in 5 — two then three, forever rolling forward.',
  },
  {
    id: 'curcuna',
    name: 'Curcuna',
    origin: 'Turkey',
    tradition: 'Ottoman classical',
    genre: 'classical',
    timeSig: '10/8',
    grouping: [2, 3, 2, 3],
    stepUnit: 8,
    steps: 10,
    bpm: { default: 200, min: 140, max: 260 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 0, 2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 1, 0, 1, 0, 1, 1],
      HH: [2, 1, 2, 1, 1, 2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['ottoman', 'asymmetric', 'classical'],
    instruments: ['kudüm', 'bendir', 'ney'],
    swingable: false,
    story: 'Two Türk Aksağıs stacked — 2+3+2+3. The archetypal Ottoman asymmetric.',
  },
  {
    id: 'duyek',
    name: 'Düyek',
    origin: 'Turkey',
    tradition: 'Ottoman folk',
    genre: 'folk-dance',
    timeSig: '8/8',
    grouping: [4, 4],
    stepUnit: 8,
    steps: 8,
    bpm: { default: 220, min: 140, max: 280 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0],
      HH: [1, 1, 1, 1, 1, 1, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['beginner', 'foundation', 'darbuka'],
    instruments: ['darbuka', 'ud'],
    swingable: false,
    story: 'The first rhythm every darbuka student learns. A foundation stone of Ottoman music.',
  },
  {
    id: 'sofyan',
    name: 'Sofyan',
    origin: 'Turkey',
    tradition: 'Ottoman classical',
    genre: 'classical',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 360, min: 240, max: 480 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['ottoman', 'classical', 'sufi', 'art-music'],
    instruments: ['kudüm', 'ney', 'tanbur'],
    swingable: false,
    story: 'Stately, dignified, and named for a Sufi order — one of the most common usuls in Turkish art music. The usul a kudümcü cuts their teeth on.',
  },
  {
    id: 'nim-sofyan',
    name: 'Nim Sofyan',
    origin: 'Turkey',
    tradition: 'Ottoman classical',
    genre: 'classical',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 440, min: 320, max: 560 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['ottoman', 'classical', 'short-cycle'],
    instruments: ['kudüm', 'def', 'tanbur'],
    swingable: false,
    story: '"Half Sofyan" — compressed to two beats. Elegant and light, it underpins short vocal phrases in Turkish art music and many folk-influenced compositions.',
    relatedIds: ['sofyan'],
  },
  {
    id: 'yuruk-semai',
    name: 'Yürük Semai',
    origin: 'Turkey',
    tradition: 'Ottoman classical',
    genre: 'classical',
    timeSig: '6/8',
    grouping: [3, 3],
    stepUnit: 8,
    steps: 6,
    bpm: { default: 130, min: 100, max: 170 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0],
      SN: [0, 0, 2, 0, 0, 2],
      HH: [2, 1, 2, 2, 1, 2],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['ottoman', 'classical', 'fasil', 'semai'],
    instruments: ['kudüm', 'ud', 'ney'],
    swingable: false,
    story: 'The lilting 6/8 that closes a fasıl suite — the "walking semai," a dance-like release before the final longa. Light on the foot, warm in the chest.',
  },
  {
    id: 'devri-hindi',
    name: 'Devr-i Hindi',
    origin: 'Turkey',
    tradition: 'Ottoman classical',
    genre: 'classical',
    timeSig: '7/8',
    grouping: [3, 2, 2],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 110, min: 90, max: 140 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 2, 0],
      SN: [0, 0, 2, 0, 2, 0, 2],
      HH: [2, 1, 2, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['ottoman', 'classical', 'asymmetric'],
    instruments: ['kudüm', 'tanbur', 'ney'],
    swingable: false,
    story: '"The Indian cycle" — a 7/8 usul rumored to have drifted in from Hindustan, though it sits squarely in the Ottoman canon. The 3+2+2 grouping leans the bar forward.',
  },
  {
    id: 'aksak',
    name: 'Aksak',
    origin: 'Turkey',
    tradition: 'Ottoman classical',
    genre: 'classical',
    timeSig: '9/8',
    grouping: [2, 2, 2, 3],
    stepUnit: 8,
    steps: 9,
    bpm: { default: 130, min: 100, max: 160 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 2, 0, 0],
      SN: [0, 0, 2, 2, 0, 0, 0, 2, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['ottoman', 'classical', 'asymmetric', 'aksak'],
    instruments: ['kudüm', 'ud', 'ney'],
    swingable: false,
    story: '"Aksak" literally means limping — nine beats that tilt forward with every measure. The classical, measured sibling of Karşılama, spun slower for refined vocal sarkı.',
    relatedIds: ['karsilama', 'agir-aksak'],
  },
  {
    id: 'agir-aksak',
    name: 'Ağır Aksak',
    origin: 'Turkey',
    tradition: 'Ottoman classical',
    genre: 'classical',
    timeSig: '9/8',
    grouping: [2, 2, 2, 3],
    stepUnit: 8,
    steps: 9,
    bpm: { default: 130, min: 100, max: 160 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 0],
      SN: [0, 0, 2, 2, 0, 0, 2, 2, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['ottoman', 'classical', 'slow', 'asymmetric'],
    instruments: ['kudüm', 'tanbur', 'ney'],
    swingable: false,
    story: 'Aksak stretched out until each beat has room to bloom. At this tempo the sarkı singer can linger on a single syllable, curling it through every microtone of the makam.',
    relatedIds: ['aksak'],
  },
  {
    id: 'longa',
    name: 'Longa',
    origin: 'Turkey',
    tradition: 'Ottoman instrumental',
    genre: 'classical',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 680, min: 560, max: 880 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0],
      SN: [0, 2, 2, 0, 0, 2, 2, 0],
      HH: [2, 2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['ottoman', 'instrumental', 'fast', 'fasil-closer'],
    instruments: ['kemençe', 'kanun', 'darbuka'],
    swingable: false,
    story: 'The last piece of a fasıl — a frantic instrumental sprint that leaves the audience breathless. Often Greek or Romani in origin, adopted into the Ottoman repertoire at speed.',
  },
  {
    id: 'zeybek',
    name: 'Zeybek',
    origin: 'Turkey · Aegean',
    tradition: 'Aegean warrior dance',
    genre: 'folk-dance',
    timeSig: '9/8',
    grouping: [2, 2, 2, 3],
    stepUnit: 8,
    steps: 9,
    bpm: { default: 110, min: 80, max: 160 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 0],
      SN: [0, 0, 2, 2, 0, 0, 2, 2, 1],
      HH: [2, 1, 2, 2, 2, 1, 2, 2, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['folk', 'aegean', 'slow', 'warrior'],
    instruments: ['davul', 'zurna', 'bağlama'],
    swingable: false,
    story: 'The solemn warrior dance of the Aegean Zeybeks — crouching, turning, swooping like an eagle. Each movement is deliberate, and the slow 9/8 leaves room for every deliberate step.',
    relatedIds: ['aksak'],
  },
  {
    id: 'halay',
    name: 'Halay',
    origin: 'Turkey · Eastern Anatolia',
    tradition: 'Anatolian line dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 480, min: 400, max: 640 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['folk', 'line-dance', 'wedding', 'anatolian'],
    instruments: ['davul', 'zurna'],
    swingable: false,
    story: 'Linked hands, a handkerchief waving at the head of the line, and davul-zurna driving the pulse. Halay starts measured and accelerates until the whole village is moving as one body.',
  },
  {
    id: 'roman-havasi',
    name: 'Roman Havası',
    origin: 'Turkey · Thrace',
    tradition: 'Romani 9/8',
    genre: 'folk-dance',
    timeSig: '9/8',
    grouping: [2, 2, 2, 3],
    stepUnit: 8,
    steps: 9,
    bpm: { default: 150, min: 130, max: 180 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 2, 0, 0],
      SN: [0, 2, 0, 2, 0, 2, 0, 1, 2],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['romani', 'thrace', 'dance', 'wedding'],
    instruments: ['darbuka', 'clarinet', 'violin'],
    swingable: false,
    story: 'Karşılama pushed into a sweat by an Edirne Romani clarinettist. More syncopation, more grease — the sound of a wedding already four hours deep.',
    relatedIds: ['karsilama', 'cocek'],
  },
  {
    id: 'kasap-havasi',
    name: 'Kasap Havası',
    origin: 'Turkey · Thrace',
    tradition: 'Thracian folk dance',
    genre: 'folk-dance',
    timeSig: '9/8',
    grouping: [2, 2, 2, 3],
    stepUnit: 8,
    steps: 9,
    bpm: { default: 145, min: 130, max: 160 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 2, 2, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 2, 2],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['folk', 'thrace', 'dance', 'outdoor'],
    instruments: ['davul', 'zurna', 'darbuka'],
    swingable: false,
    story: 'The butchers\' dance — a stomping Thracian cousin of Karşılama, heavier on the foot, played outdoors where the davul has to cut through open air.',
    relatedIds: ['karsilama'],
  },
  {
    id: 'curcuna-fast',
    name: 'Curcuna (Fast)',
    origin: 'Turkey',
    tradition: 'Ottoman classical',
    genre: 'classical',
    timeSig: '10/8',
    grouping: [3, 2, 2, 3],
    stepUnit: 8,
    steps: 10,
    bpm: { default: 160, min: 130, max: 200 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 2, 0, 2, 0, 2, 0, 0],
      SN: [0, 2, 2, 0, 2, 0, 2, 0, 2, 2],
      HH: [2, 1, 2, 2, 1, 2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['ottoman', 'classical', 'asymmetric', '10-8'],
    instruments: ['kudüm', 'ud', 'ney'],
    swingable: false,
    story: 'A faster cousin of Curcuna grouped 3+2+2+3 — the same asymmetric skeleton, but pushed toward semi-classical ensemble playing where it shares territory with Arab Samai Thaqil.',
    relatedIds: ['curcuna', 'samai-thaqil'],
  },
  {
    id: 'arabesk',
    name: 'Arabesk',
    origin: 'Turkey · Istanbul',
    tradition: 'Gecekondu urban',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 300, min: 240, max: 360 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      HH: [0, 0, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['arabesque', 'urban', 'melancholic', '20th-century'],
    instruments: ['darbuka', 'bağlama', 'strings'],
    swingable: false,
    story: 'Orhan Gencebay turning the bağlama toward Cairo, Ibrahim Tatlıses wailing through a cassette radio in a minibus. Heavy, slow, drenched in fate — the music of Istanbul\'s gecekondu migrations.',
  },
  {
    id: 'anadolu-rock',
    name: 'Anadolu Rock',
    origin: 'Turkey',
    tradition: 'Anatolian rock fusion',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 500, min: 440, max: 560 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['anatolian-rock', 'fusion', '1970s', 'baris-manco'],
    instruments: ['bağlama', 'drum kit', 'electric guitar'],
    swingable: false,
    story: 'Barış Manço, Erkin Koray and Cem Karaca bolting folk aksak to a backbeat. The kick echoes davul patterns while the snare lands on 2 and 4 like any rock band, and somewhere a fuzzed-out bağlama is taking the solo.',
  },
  {
    id: 'davul-zurna',
    name: 'Davul-Zurna',
    origin: 'Turkey · Anatolia',
    tradition: 'Outdoor festival',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 520, min: 400, max: 640 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['outdoor', 'wedding', 'circumcision', 'davul', 'zurna'],
    instruments: ['davul', 'zurna'],
    swingable: false,
    story: 'The thunderous pairing that can be heard across three valleys — the davul stick hits bass, a thin switch plays treble, and the zurna cries on top. Weddings, circumcisions, village square on any night that matters.',
  },
];
