import type { Pattern } from '../types';

export const WEST_AFRICA_PATTERNS: Pattern[] = [
  {
    id: 'agbekor',
    name: 'Agbekor',
    origin: 'Ghana · Ewe',
    tradition: 'Anlo Ewe war dance',
    genre: 'ceremonial',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 115, min: 100, max: 130 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2],
      HH: [2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2, 0],
    },
    defaultKit: '727',
    country: 'GH',
    region: 'west-africa',
    tags: ['ewe', 'war-dance', 'bell', 'ceremony'],
    instruments: ['gankogui', 'axatse', 'atsimevu'],
    swingable: false,
    story: 'An Anlo Ewe war dance from Ghana, now performed at funerals and festivals. The gankogui bell timeline holds everything together while sogo and atsimevu interlock.',
  },
  {
    id: 'gahu',
    name: 'Gahu',
    origin: 'Ghana · Ewe',
    tradition: 'Social dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 480, min: 440, max: 540 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0],
    },
    defaultKit: '727',
    country: 'GH',
    region: 'west-africa',
    tags: ['ewe', 'social', 'dance', 'yoruba-origin'],
    instruments: ['gankogui', 'axatse', 'kidi'],
    swingable: false,
    story: 'Borrowed by the Ewe from Yoruba-speaking peoples via Benin. Lighter and more celebratory than Agbekor, and often the first ensemble rhythm a drum-class learns.',
    relatedIds: ['agbekor'],
  },
  {
    id: 'kpanlogo',
    name: 'Kpanlogo',
    origin: 'Ghana · Ga',
    tradition: 'Social dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 460, min: 420, max: 500 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0],
      HH: [2, 0, 0, 2, 0, 0, 2, 1, 0, 0, 2, 0, 0, 2, 0, 1],
    },
    defaultKit: '727',
    country: 'GH',
    region: 'west-africa',
    tags: ['ga', 'urban', 'dance', 'highlife'],
    instruments: ['kpanlogo drums', 'nono bell', 'afiri'],
    swingable: false,
    story: 'Invented in 1960s Accra by Ga youth — a conga-based social dance that fused traditional Ga drumming with highlife and rock, now Ghana\'s de facto national rhythm.',
  },
  {
    id: 'kuku',
    name: 'Kuku',
    origin: 'Guinea · Malinke',
    tradition: 'Fishermen\'s celebration',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 145, min: 130, max: 160 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 1, 2, 0, 1, 0, 2, 0],
      HH: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
    },
    defaultKit: '727',
    country: 'GN',
    region: 'west-africa',
    tags: ['djembe', 'malinke', 'celebration', 'beginner-ensemble'],
    instruments: ['djembe', 'dundun', 'kenkeni'],
    swingable: false,
    story: 'Originally played for women returning from fishing trips. Now the first djembe ensemble rhythm taught worldwide — driving, joyful, endlessly danceable.',
  },
  {
    id: 'soli',
    name: 'Soli',
    origin: 'Guinea · Malinke',
    tradition: 'Initiation ceremony',
    genre: 'ceremonial',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 120, min: 100, max: 140 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 1, 0, 2, 0, 1, 0, 2, 0],
      HH: [2, 1, 0, 2, 1, 2, 2, 0, 1, 2, 0, 0],
    },
    defaultKit: '727',
    country: 'GN',
    region: 'west-africa',
    tags: ['djembe', 'malinke', 'ritual', 'initiation'],
    instruments: ['djembe', 'dundunba', 'sangban'],
    swingable: false,
    story: 'The initiation rhythm of Malinke Guinea — it accompanies the dance-stories of young people crossing from childhood to adulthood. Sacred in its traditional context.',
  },
  {
    id: 'dununba',
    name: 'Dununba',
    origin: 'Guinea · Malinke',
    tradition: 'Strong men\'s dance',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 520, min: 440, max: 580 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0],
      SN: [0, 0, 2, 1, 2, 1, 0, 0, 0, 2, 1, 2, 1, 0, 0, 0],
      HH: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
    },
    defaultKit: '727',
    country: 'GN',
    region: 'west-africa',
    tags: ['djembe', 'dundun', 'strength', 'acrobatic'],
    instruments: ['dundunba', 'djembe', 'kenkeni'],
    swingable: false,
    story: 'The dance of the strong men — acrobatic, muscular, led by the booming dundunba drum the rhythm is named after.',
  },
  {
    id: 'fanga',
    name: 'Fanga',
    origin: 'Liberia · Pan-West-African',
    tradition: 'Welcome dance',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 460, min: 400, max: 520 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'LR',
    region: 'west-africa',
    tags: ['welcome', 'pan-african', 'beginner'],
    instruments: ['djembe', 'conga', 'shekere'],
    swingable: false,
    story: 'A welcome rhythm spread across the African diaspora in the 1960s by Babatunde Olatunji. The doors open, the drums speak, the guests enter.',
  },
  {
    id: 'adowa',
    name: 'Adowa',
    origin: 'Ghana · Ashanti',
    tradition: 'Funeral / royal dance',
    genre: 'ceremonial',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 110, min: 90, max: 130 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0],
      SN: [0, 0, 2, 0, 1, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2, 0],
    },
    defaultKit: '727',
    country: 'GH',
    region: 'west-africa',
    tags: ['akan', 'ashanti', 'funeral', 'royal'],
    instruments: ['atumpan', 'adowa drums', 'dawuro'],
    swingable: false,
    story: 'The most widespread Akan dance — performed at funerals, royal gatherings, and festivals. Graceful hand-and-foot gestures tell proverbs through movement.',
  },
  {
    id: 'bembe-68',
    name: 'Bembé 6/8',
    origin: 'West Africa · Yoruba',
    tradition: 'Sacred bell timeline',
    genre: 'devotional',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 230, min: 180, max: 300 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
      SN: [0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 2, 0],
      HH: [2, 0, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2],
    },
    defaultKit: '727',
    region: 'west-africa',
    tags: ['yoruba', 'bell', 'sacred', 'standard-pattern'],
    instruments: ['agogô', 'bata', 'shekere'],
    swingable: false,
    story: 'The "standard pattern" — the 12/8 bell timeline that traveled from Yorubaland to Havana to Salvador and anchors half the African diaspora\'s music.',
    relatedIds: ['bembe'],
  },
  {
    id: 'djembe-standard',
    name: 'Djembe Standard',
    origin: 'Mali · Mande',
    tradition: 'Djembe ensemble',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 130, min: 110, max: 160 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 1, 0, 2, 0, 0, 2, 1, 0, 2],
      HH: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
    },
    defaultKit: '727',
    country: 'ML',
    region: 'west-africa',
    tags: ['djembe', 'mande', 'foundation', 'ensemble'],
    instruments: ['djembe', 'dundun', 'kenkeni'],
    swingable: false,
    story: 'The archetypal djembe accompaniment — tones and slaps interlocking over the kenkeni pulse. Mande culture\'s most traveled rhythmic export.',
  },
  {
    id: 'tiriba',
    name: 'Tiriba',
    origin: 'Guinea · Malinke',
    tradition: 'Women\'s celebration / harvest',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 140, min: 130, max: 155 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0],
      SN: [2, 0, 0, 0, 0, 2, 2, 0, 2, 0, 0, 2],
      HH: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
    },
    defaultKit: '727',
    country: 'GN',
    region: 'west-africa',
    tags: ['djembe', 'malinke', 'women', 'harvest'],
    instruments: ['djembe', 'sangban', 'dundunba'],
    swingable: false,
    story: 'A joyful rhythm traditionally played for women\'s celebrations — harvest, fertility, coming-of-age. The sangban\'s bell pattern is what you\'ll hear first and remember longest.',
    relatedIds: ['kuku', 'yankadi'],
  },
  {
    id: 'yankadi',
    name: 'Yankadi',
    origin: 'Guinea · Malinke / Susu',
    tradition: 'Slow courtship dance',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 95, min: 85, max: 110 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
      HH: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
    },
    defaultKit: '727',
    country: 'GN',
    region: 'west-africa',
    tags: ['djembe', 'malinke', 'courtship', 'beginner-ensemble'],
    instruments: ['djembe', 'kenkeni', 'sangban'],
    swingable: false,
    story: 'Young men and women face each other in two lines and take turns stepping forward to express interest. Gentle, patient, and an ideal first djembe ensemble rhythm.',
    relatedIds: ['makru'],
  },
  {
    id: 'makru',
    name: 'Makru',
    origin: 'Guinea · Malinke / Susu',
    tradition: 'Fast courtship dance',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 155, min: 140, max: 170 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0],
      SN: [2, 0, 2, 2, 0, 2, 2, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 2, 0, 2, 2, 0, 2, 2, 0, 2],
    },
    defaultKit: '727',
    country: 'GN',
    region: 'west-africa',
    tags: ['djembe', 'malinke', 'courtship', 'fast'],
    instruments: ['djembe', 'kenkeni', 'sangban'],
    swingable: false,
    story: 'Yankadi\'s fast partner. The lead drummer signals the transition and the whole dance explodes — one of West African music\'s most thrilling gear-changes.',
    relatedIds: ['yankadi'],
  },
  {
    id: 'djansa',
    name: 'Djansa',
    origin: 'Guinea · Malinke',
    tradition: 'Celebration / wedding',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 520, min: 480, max: 580 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0],
      SN: [0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 0],
      HH: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
    },
    defaultKit: '727',
    country: 'GN',
    region: 'west-africa',
    tags: ['djembe', 'mande', 'wedding', 'celebration'],
    instruments: ['djembe', 'dundunba', 'kenkeni'],
    swingable: false,
    story: 'A rolling, forward-moving Mande celebration rhythm played at weddings and naming ceremonies. The dundun interplay is what makes it unmistakable.',
  },
  {
    id: 'sunu',
    name: 'Sunu',
    origin: 'Guinea · Malinke',
    tradition: 'Community gathering',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 125, min: 115, max: 140 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 2, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0],
      HH: [2, 0, 0, 2, 0, 2, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'GN',
    region: 'west-africa',
    tags: ['djembe', 'malinke', 'community', 'storytelling'],
    instruments: ['djembe', 'sangban', 'dundunba'],
    swingable: false,
    story: 'A swaying, storytelling rhythm. The sangban\'s rocking bell creates a cradle for the drums and singers to lean into.',
  },
  {
    id: 'bobobo',
    name: 'Bobobo',
    origin: 'Ghana · Northern Ewe',
    tradition: 'Social / recreational dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 420, min: 360, max: 460 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0],
    },
    defaultKit: '727',
    country: 'GH',
    region: 'west-africa',
    tags: ['ewe', 'northern-ewe', 'beginner-ensemble', 'social'],
    instruments: ['gankogui', 'axatse', 'kagan'],
    swingable: false,
    story: 'The northern Ewe\'s most accessible recreational dance — simpler than Agbekor or Gahu, and usually the first rhythm drum-class newcomers learn.',
    relatedIds: ['gahu', 'agbekor'],
  },
  {
    id: 'atsiagbekor',
    name: 'Atsiagbekor',
    origin: 'Ghana · Anlo Ewe',
    tradition: 'War dance (full ritual form)',
    genre: 'ceremonial',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 125, min: 95, max: 140 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2],
      HH: [2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2, 0],
    },
    defaultKit: '727',
    country: 'GH',
    region: 'west-africa',
    tags: ['ewe', 'war-dance', 'ceremony', 'ritual'],
    instruments: ['gankogui', 'atsimevu', 'sogo'],
    swingable: false,
    story: 'The complete ritual form of the Ewe war dance — slow processional before a fast dance of combat. Some scholars treat Agbekor and Atsiagbekor as the same tradition seen from two angles.',
    relatedIds: ['agbekor'],
  },
  {
    id: 'gadzo',
    name: 'Gadzo',
    origin: 'Ghana · Ewe',
    tradition: 'Social / work song',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 110, min: 100, max: 120 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2],
      HH: [2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2, 0],
    },
    defaultKit: '727',
    country: 'GH',
    region: 'west-africa',
    tags: ['ewe', 'work-song', 'beginner', 'timeline'],
    instruments: ['gankogui', 'axatse', 'kidi'],
    swingable: false,
    story: 'A gentle Ewe rhythm tied to everyday work and gathering. Ideal for learning how the standard 12/8 bell locks the supporting drums into place.',
    relatedIds: ['agbekor', 'bobobo'],
  },
  {
    id: 'tokoe',
    name: 'Tokoe',
    origin: 'Ghana · Ewe',
    tradition: 'Social dance',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 125, min: 115, max: 135 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0, 0],
      HH: [2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2, 0],
    },
    defaultKit: '727',
    country: 'GH',
    region: 'west-africa',
    tags: ['ewe', 'social', 'festive', 'syncopation'],
    instruments: ['gankogui', 'kidi', 'kagan'],
    swingable: false,
    story: 'A festive Ewe rhythm where the kidi weaves syncopations between every accent of the bell. The energy is pure celebration.',
  },
  {
    id: 'bata-shango',
    name: 'Bata — Shango',
    origin: 'Nigeria · Yoruba',
    tradition: 'Orisha worship (orisha of thunder)',
    genre: 'devotional',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 110, min: 90, max: 130 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 0],
      SN: [2, 0, 0, 2, 0, 2, 2, 0, 0, 2, 0, 2],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'NG',
    region: 'west-africa',
    tags: ['yoruba', 'sacred', 'orisha', 'bata'],
    instruments: ['iya', 'itotele', 'okonkolo'],
    swingable: false,
    story: 'The fire-and-thunder rhythm for Shango, orisha of lightning. The three-drum Bata trio speaks Yoruba — here we collapse it: okonkolo timeline on HH, iya lead on KK, itotele response on SN.',
    relatedIds: ['bembe-68'],
  },
  {
    id: 'dundun-yoruba',
    name: 'Dundun / Talking Drum',
    origin: 'Nigeria · Yoruba',
    tradition: 'Praise and proverb',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 460, min: 380, max: 520 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0],
      SN: [0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'NG',
    region: 'west-africa',
    tags: ['yoruba', 'talking-drum', 'praise', 'tonal'],
    instruments: ['iya dundun', 'gangan', 'gudugudu'],
    swingable: false,
    story: 'The hourglass tension drum squeezed under the armpit bends pitch to mimic Yoruba tonal speech — here a framework groove for the iya dundun to "speak" over.',
  },
  {
    id: 'apala',
    name: 'Apala',
    origin: 'Nigeria · Yoruba',
    tradition: 'Social / Islamic-influenced',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 440, min: 400, max: 480 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 2, 0, 2, 0, 2],
    },
    defaultKit: '727',
    country: 'NG',
    region: 'west-africa',
    tags: ['yoruba', 'islamic', 'drum-and-vocal', 'haruna-ishola'],
    instruments: ['agidigbo', 'omele', 'sekere'],
    swingable: false,
    story: 'Yoruba Muslim social music, popularised by Haruna Ishola in the 1940s–60s. No melodic instruments — only drums, thumb-piano, and voice.',
  },
  {
    id: 'highlife-ghana',
    name: 'Highlife (Ghana)',
    origin: 'Ghana · Accra / Kumasi',
    tradition: 'Guitar-band highlife',
    genre: 'popular',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 115, min: 105, max: 125 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
      SN: [0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0],
      HH: [2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2, 0],
    },
    defaultKit: '727',
    country: 'GH',
    region: 'west-africa',
    tags: ['highlife', 'guitar-band', 'sikyi-bell', 'et-mensah'],
    instruments: ['guitar', 'horns', 'sikyi bell'],
    swingable: true,
    story: 'The sikyi bell timeline runs the whole of Ghanaian highlife — the cosmopolitan, horn-driven sound of E.T. Mensah and the guitar-band era.',
  },
  {
    id: 'afrobeat',
    name: 'Afrobeat (Tony Allen)',
    origin: 'Nigeria · Lagos',
    tradition: 'Fela Kuti / Tony Allen',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 440, min: 400, max: 480 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'NG',
    region: 'west-africa',
    tags: ['afrobeat', 'tony-allen', 'fela', 'funk-jazz-fusion'],
    instruments: ['drum kit', 'congas', 'shekere'],
    swingable: false,
    story: '"I play the drums as if I am four people." Tony Allen built Afrobeat\'s floating pocket by displacing the snare off the backbeat and weaving the kick around it.',
  },
  {
    id: 'sabar',
    name: 'Sabar',
    origin: 'Senegal · Wolof',
    tradition: 'Wolof griot drumming',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 520, min: 440, max: 640 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'SN',
    region: 'west-africa',
    tags: ['wolof', 'sabar', 'bakks', 'griot'],
    instruments: ['nder', 'mbung mbung', 'tungune'],
    swingable: false,
    story: 'The Wolof griot\'s drum family. The lead nder shouts rhythmic "bakks" — spoken-sentence phrases — that the dancers must answer with specific steps.',
  },
];
