import type { Pattern } from '../types';

export const WEST_AFRICA_PATTERNS: Pattern[] = [
  {
    id: 'agbekor',
    name: 'Agbekor',
    origin: 'Ghana · Ewe',
    tradition: 'Anlo Ewe war dance',
    genre: 'ceremonial',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 115, min: 100, max: 130 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2],
      HH: [2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2, 0],
    },
    defaultKit: '727',
    country: 'GH',
    region: 'west-africa',
    tags: ['ewe', 'war-dance', 'bell', 'ceremony'],
    instruments: ['gankogui', 'axatse', 'atsimevu'],
    swingable: false,
    story: 'An Anlo Ewe war dance from Ghana, now performed at funerals and festivals. The gankogui bell timeline holds everything together while sogo and atsimevu interlock.',
  },
  {
    id: 'gahu',
    name: 'Gahu',
    origin: 'Ghana · Ewe',
    tradition: 'Social dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 120, min: 110, max: 135 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0],
    },
    defaultKit: '727',
    country: 'GH',
    region: 'west-africa',
    tags: ['ewe', 'social', 'dance', 'yoruba-origin'],
    instruments: ['gankogui', 'axatse', 'kidi'],
    swingable: false,
    story: 'Borrowed by the Ewe from Yoruba-speaking peoples via Benin. Lighter and more celebratory than Agbekor, and often the first ensemble rhythm a drum-class learns.',
    relatedIds: ['agbekor'],
  },
  {
    id: 'kpanlogo',
    name: 'Kpanlogo',
    origin: 'Ghana · Ga',
    tradition: 'Social dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 115, min: 105, max: 125 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0],
      HH: [2, 0, 0, 2, 0, 0, 2, 1, 0, 0, 2, 0, 0, 2, 0, 1],
    },
    defaultKit: '727',
    country: 'GH',
    region: 'west-africa',
    tags: ['ga', 'urban', 'dance', 'highlife'],
    instruments: ['kpanlogo drums', 'nono bell', 'afiri'],
    swingable: false,
    story: 'Invented in 1960s Accra by Ga youth — a conga-based social dance that fused traditional Ga drumming with highlife and rock, now Ghana\'s de facto national rhythm.',
  },
  {
    id: 'kuku',
    name: 'Kuku',
    origin: 'Guinea · Malinke',
    tradition: 'Fishermen\'s celebration',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 145, min: 130, max: 160 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 1, 2, 0, 1, 0, 2, 0],
      HH: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
    },
    defaultKit: '727',
    country: 'GN',
    region: 'west-africa',
    tags: ['djembe', 'malinke', 'celebration', 'beginner-ensemble'],
    instruments: ['djembe', 'dundun', 'kenkeni'],
    swingable: false,
    story: 'Originally played for women returning from fishing trips. Now the first djembe ensemble rhythm taught worldwide — driving, joyful, endlessly danceable.',
  },
  {
    id: 'soli',
    name: 'Soli',
    origin: 'Guinea · Malinke',
    tradition: 'Initiation ceremony',
    genre: 'ceremonial',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 120, min: 100, max: 140 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 1, 0, 2, 0, 1, 0, 2, 0],
      HH: [2, 1, 0, 2, 1, 2, 2, 0, 1, 2, 0, 0],
    },
    defaultKit: '727',
    country: 'GN',
    region: 'west-africa',
    tags: ['djembe', 'malinke', 'ritual', 'initiation'],
    instruments: ['djembe', 'dundunba', 'sangban'],
    swingable: false,
    story: 'The initiation rhythm of Malinke Guinea — it accompanies the dance-stories of young people crossing from childhood to adulthood. Sacred in its traditional context.',
  },
  {
    id: 'dununba',
    name: 'Dununba',
    origin: 'Guinea · Malinke',
    tradition: 'Strong men\'s dance',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 130, min: 110, max: 145 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0],
      SN: [0, 0, 2, 1, 2, 1, 0, 0, 0, 2, 1, 2, 1, 0, 0, 0],
      HH: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
    },
    defaultKit: '727',
    country: 'GN',
    region: 'west-africa',
    tags: ['djembe', 'dundun', 'strength', 'acrobatic'],
    instruments: ['dundunba', 'djembe', 'kenkeni'],
    swingable: false,
    story: 'The dance of the strong men — acrobatic, muscular, led by the booming dundunba drum the rhythm is named after.',
  },
  {
    id: 'fanga',
    name: 'Fanga',
    origin: 'Liberia · Pan-West-African',
    tradition: 'Welcome dance',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 115, min: 100, max: 130 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'LR',
    region: 'west-africa',
    tags: ['welcome', 'pan-african', 'beginner'],
    instruments: ['djembe', 'conga', 'shekere'],
    swingable: false,
    story: 'A welcome rhythm spread across the African diaspora in the 1960s by Babatunde Olatunji. The doors open, the drums speak, the guests enter.',
  },
  {
    id: 'adowa',
    name: 'Adowa',
    origin: 'Ghana · Ashanti',
    tradition: 'Funeral / royal dance',
    genre: 'ceremonial',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 110, min: 90, max: 130 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0],
      SN: [0, 0, 2, 0, 1, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2, 0],
    },
    defaultKit: '727',
    country: 'GH',
    region: 'west-africa',
    tags: ['akan', 'ashanti', 'funeral', 'royal'],
    instruments: ['atumpan', 'adowa drums', 'dawuro'],
    swingable: false,
    story: 'The most widespread Akan dance — performed at funerals, royal gatherings, and festivals. Graceful hand-and-foot gestures tell proverbs through movement.',
  },
  {
    id: 'bembe-68',
    name: 'Bembé 6/8',
    origin: 'West Africa · Yoruba',
    tradition: 'Sacred bell timeline',
    genre: 'devotional',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 230, min: 180, max: 300 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
      SN: [0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 2, 0],
      HH: [2, 0, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2],
    },
    defaultKit: '727',
    region: 'west-africa',
    tags: ['yoruba', 'bell', 'sacred', 'standard-pattern'],
    instruments: ['agogô', 'bata', 'shekere'],
    swingable: false,
    story: 'The "standard pattern" — the 12/8 bell timeline that traveled from Yorubaland to Havana to Salvador and anchors half the African diaspora\'s music.',
    relatedIds: ['bembe'],
  },
  {
    id: 'djembe-standard',
    name: 'Djembe Standard',
    origin: 'Mali · Mande',
    tradition: 'Djembe ensemble',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 130, min: 110, max: 160 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 1, 0, 2, 0, 0, 2, 1, 0, 2],
      HH: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
    },
    defaultKit: '727',
    country: 'ML',
    region: 'west-africa',
    tags: ['djembe', 'mande', 'foundation', 'ensemble'],
    instruments: ['djembe', 'dundun', 'kenkeni'],
    swingable: false,
    story: 'The archetypal djembe accompaniment — tones and slaps interlocking over the kenkeni pulse. Mande culture\'s most traveled rhythmic export.',
  },
];
