// First-pass seed library — 10 world patterns + 5 polyrhythm exercises.
// Full 85-pattern library arrives in batch 3 via research-corpus migration.

import type { Pattern } from './types';

export const PATTERNS: Pattern[] = [
  // ── TURKISH / OTTOMAN ────────────────────────────────────────────
  {
    id: 'karsilama',
    name: 'Karşılama',
    origin: 'Turkey · Thrace',
    tradition: 'Wedding dance',
    genre: 'folk-dance',
    timeSig: '9/8',
    grouping: [2, 2, 2, 3],
    stepUnit: 8,
    steps: 9,
    bpm: { default: 276, min: 200, max: 360 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 2, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 1, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['wedding', 'dance', 'romani', 'thracian'],
    instruments: ['frame drum', 'bağlama', 'clarinet'],
    swingable: false,
    story:
      'Karşılama means "face to face" — the dance has two rows of dancers greeting each other. The 2+2+2+3 grouping gives the whole thing its iconic skip.',
    relatedIds: ['daichovo'],
  },
  {
    id: 'horon',
    name: 'Horon',
    origin: 'Turkey · Black Sea',
    tradition: 'Coastal line dance',
    genre: 'folk-dance',
    timeSig: '7/8',
    grouping: [2, 2, 3],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 360, min: 280, max: 460 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 0, 1, 1],
      HH: [2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['dance', 'line-dance', 'coastal'],
    instruments: ['kemençe', 'davul', 'tulum'],
    swingable: false,
    story: 'Horon is the fisherman shaking on a trawler deck. Played at Mach speed on kemençe and davul.',
    relatedIds: ['ruchenitsa'],
  },
  {
    id: 'turk-aksagi',
    name: 'Türk Aksağı',
    origin: 'Turkey',
    tradition: 'Ottoman / folk',
    genre: 'classical',
    timeSig: '5/8',
    grouping: [2, 3],
    stepUnit: 8,
    steps: 5,
    bpm: { default: 260, min: 200, max: 340 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 1],
      HH: [2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['ottoman', 'asymmetric'],
    instruments: ['kudüm', 'def', 'ud'],
    swingable: false,
    story: 'The Turkish limp in 5 — two then three, forever rolling forward.',
  },
  {
    id: 'curcuna',
    name: 'Curcuna',
    origin: 'Turkey',
    tradition: 'Ottoman classical',
    genre: 'classical',
    timeSig: '10/8',
    grouping: [2, 3, 2, 3],
    stepUnit: 8,
    steps: 10,
    bpm: { default: 200, min: 140, max: 260 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 0, 2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 1, 0, 1, 0, 1, 1],
      HH: [2, 1, 2, 1, 1, 2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['ottoman', 'asymmetric', 'classical'],
    instruments: ['kudüm', 'bendir', 'ney'],
    swingable: false,
    story: 'Two Türk Aksağıs stacked — 2+3+2+3. The archetypal Ottoman asymmetric.',
  },
  {
    id: 'duyek',
    name: 'Düyek',
    origin: 'Turkey',
    tradition: 'Ottoman folk',
    genre: 'folk-dance',
    timeSig: '8/8',
    grouping: [4, 4],
    stepUnit: 8,
    steps: 8,
    bpm: { default: 220, min: 140, max: 280 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0],
      HH: [1, 1, 1, 1, 1, 1, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['beginner', 'foundation', 'darbuka'],
    instruments: ['darbuka', 'ud'],
    swingable: false,
    story: 'The first rhythm every darbuka student learns. A foundation stone of Ottoman music.',
  },

  // ── BALKAN ───────────────────────────────────────────────────────
  {
    id: 'ruchenitsa',
    name: 'Rŭchenitsa',
    origin: 'Bulgaria',
    tradition: 'Folk dance',
    genre: 'folk-dance',
    timeSig: '7/8',
    grouping: [2, 2, 3],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 320, min: 240, max: 420 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0],
      SN: [0, 0, 0, 0, 0, 1, 1],
      HH: [2, 1, 2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'balkans',
    country: 'BG',
    tags: ['dance', 'line-dance', 'bulgarian'],
    instruments: ['gaida', 'kaval', 'tapan'],
    swingable: false,
    story: "Bulgaria's most danced rhythm — \"quick-quick-sloooow\" is how kids learn it.",
    relatedIds: ['horon'],
  },
  {
    id: 'kopanitsa',
    name: 'Kopanitsa',
    origin: 'Bulgaria · Shope',
    tradition: 'Folk dance',
    genre: 'folk-dance',
    timeSig: '11/8',
    grouping: [2, 2, 3, 2, 2],
    stepUnit: 8,
    steps: 11,
    bpm: { default: 400, min: 320, max: 520 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0],
      SN: [0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: 'frameDrum',
    region: 'balkans',
    country: 'BG',
    tags: ['dance', 'advanced', 'shope'],
    instruments: ['gaida', 'kaval', 'tapan'],
    swingable: false,
    story: '11/8 stomping through a tavern. The long beat is in the middle here.',
  },
  {
    id: 'daichovo',
    name: 'Daichovo',
    origin: 'Bulgaria',
    tradition: 'Folk dance',
    genre: 'folk-dance',
    timeSig: '9/8',
    grouping: [2, 2, 2, 3],
    stepUnit: 8,
    steps: 9,
    bpm: { default: 340, min: 280, max: 440 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 0, 1, 0, 1, 1],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: 'frameDrum',
    region: 'balkans',
    country: 'BG',
    tags: ['dance', 'bulgarian'],
    instruments: ['gaida', 'kaval'],
    swingable: false,
    story: 'Same 2+2+2+3 skeleton as Karşılama but faster, bouncier, pan-flute territory.',
    relatedIds: ['karsilama'],
  },

  // ── AFRO-CUBAN ───────────────────────────────────────────────────
  {
    id: 'son-clave',
    name: 'Son Clave 3-2',
    origin: 'Cuba',
    tradition: 'Afro-Cuban',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 380, min: 280, max: 800 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1],
    },
    defaultKit: '727',
    region: 'cuba-afrocaribbean',
    country: 'CU',
    tags: ['clave', 'foundation', 'salsa'],
    instruments: ['claves', 'congas', 'bongos'],
    swingable: true,
    story: 'The spine of every Cuban son, salsa, and half of Latin music since 1800.',
  },
  {
    id: 'bembe',
    name: 'Bembé',
    origin: 'Cuba · Yoruba diaspora',
    tradition: 'Sacred bell pattern',
    genre: 'devotional',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 230, min: 180, max: 300 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    region: 'cuba-afrocaribbean',
    country: 'CU',
    tags: ['bell', 'sacred', 'afrobeat-ancestor'],
    instruments: ['atoke', 'congas', 'bata'],
    swingable: false,
    story: 'The 12/8 bell that underlies bembé, abakuá, and half the West African diaspora.',
  },

  // ── POLYRHYTHM EXERCISES (per-track subdivisions) ────────────────
  {
    id: 'hemiola-3-2',
    name: 'Hemiola (3:2)',
    origin: '—',
    tradition: 'Polyrhythm exercise',
    genre: 'exercise',
    timeSig: '2/4',
    grouping: [2],
    stepUnit: 4,
    steps: 2,
    poly: true,
    bpm: { default: 120, min: 60, max: 200 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0],
      SN: { pattern: [2, 0, 0], subdivisions: 3 },
    },
    defaultKit: '707',
    region: 'exercise',
    tags: ['polyrhythm', '3-over-2', 'exercise'],
    swingable: false,
    story: 'The simplest polyrhythm — three notes in the time of two. The foundation of most polyrhythmic music, from West African bell patterns to jazz.',
  },
  {
    id: 'triplet-over-quarters',
    name: 'Triplets over Quarters (3:4)',
    origin: '—',
    tradition: 'Polyrhythm exercise',
    genre: 'exercise',
    timeSig: '4/4',
    grouping: [4],
    stepUnit: 4,
    steps: 4,
    poly: true,
    bpm: { default: 120, min: 60, max: 200 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 2, 0],
      HH: { pattern: [2, 0, 0], subdivisions: 3 },
    },
    defaultKit: '707',
    region: 'exercise',
    tags: ['polyrhythm', '3-over-4', 'triplet', 'exercise'],
    swingable: false,
    story: 'Three evenly-spaced notes across one bar of four — the classic jazz/funk polyrhythm. Every practicing drummer should internalize this.',
  },
  {
    id: 'four-over-three',
    name: 'Four over Three (4:3)',
    origin: '—',
    tradition: 'Polyrhythm exercise',
    genre: 'exercise',
    timeSig: '3/4',
    grouping: [3],
    stepUnit: 4,
    steps: 3,
    poly: true,
    bpm: { default: 100, min: 60, max: 180 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0],
      HH: { pattern: [2, 0, 0, 0], subdivisions: 4 },
    },
    defaultKit: '707',
    region: 'exercise',
    tags: ['polyrhythm', '4-over-3', 'exercise'],
    swingable: false,
    story: "The inverse of 3-over-4. Feels 'slippery' because neither side lines up except at the downbeat.",
  },
  {
    id: 'five-over-four',
    name: 'Five over Four (5:4)',
    origin: '—',
    tradition: 'Polyrhythm exercise',
    genre: 'exercise',
    timeSig: '4/4',
    grouping: [4],
    stepUnit: 4,
    steps: 4,
    poly: true,
    bpm: { default: 100, min: 60, max: 180 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0],
      HH: { pattern: [2, 0, 0, 0, 0], subdivisions: 5 },
    },
    defaultKit: '707',
    region: 'exercise',
    tags: ['polyrhythm', '5-over-4', 'experimental', 'exercise'],
    swingable: false,
    story: 'Quintuplets over quarters. Found in Carnatic khanda and contemporary jazz — Vijay Iyer territory.',
  },
  {
    id: 'seven-over-four',
    name: 'Seven over Four (7:4)',
    origin: '—',
    tradition: 'Polyrhythm exercise',
    genre: 'exercise',
    timeSig: '4/4',
    grouping: [4],
    stepUnit: 4,
    steps: 4,
    poly: true,
    bpm: { default: 100, min: 60, max: 160 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0],
      HH: { pattern: [2, 0, 0, 0, 0, 0, 0], subdivisions: 7 },
    },
    defaultKit: '707',
    region: 'exercise',
    tags: ['polyrhythm', '7-over-4', 'experimental', 'exercise'],
    swingable: false,
    story: 'Septuplets over quarters. Rare in tradition — common in konnakol (Indian rhythmic solfège) exercises.',
  },
];

export function patternById(id: string): Pattern | undefined {
  return PATTERNS.find((p) => p.id === id);
}
