// First-pass seed library — 10 world patterns + 5 polyrhythm exercises.
// Full 85-pattern library arrives in batch 3 via research-corpus migration.

import type { Pattern } from './types';

export const PATTERNS: Pattern[] = [
  // ── TURKISH / OTTOMAN ────────────────────────────────────────────
  {
    id: 'karsilama',
    name: 'Karşılama',
    origin: 'Turkey · Thrace',
    tradition: 'Wedding dance',
    genre: 'folk-dance',
    timeSig: '9/8',
    grouping: [2, 2, 2, 3],
    stepUnit: 8,
    steps: 9,
    bpm: { default: 276, min: 200, max: 360 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 2, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 1, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['wedding', 'dance', 'romani', 'thracian'],
    instruments: ['frame drum', 'bağlama', 'clarinet'],
    swingable: false,
    story:
      'Karşılama means "face to face" — the dance has two rows of dancers greeting each other. The 2+2+2+3 grouping gives the whole thing its iconic skip.',
    relatedIds: ['daichovo'],
  },
  {
    id: 'horon',
    name: 'Horon',
    origin: 'Turkey · Black Sea',
    tradition: 'Coastal line dance',
    genre: 'folk-dance',
    timeSig: '7/8',
    grouping: [2, 2, 3],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 360, min: 280, max: 460 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 0, 1, 1],
      HH: [2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['dance', 'line-dance', 'coastal'],
    instruments: ['kemençe', 'davul', 'tulum'],
    swingable: false,
    story: 'Horon is the fisherman shaking on a trawler deck. Played at Mach speed on kemençe and davul.',
    relatedIds: ['ruchenitsa'],
  },
  {
    id: 'turk-aksagi',
    name: 'Türk Aksağı',
    origin: 'Turkey',
    tradition: 'Ottoman / folk',
    genre: 'classical',
    timeSig: '5/8',
    grouping: [2, 3],
    stepUnit: 8,
    steps: 5,
    bpm: { default: 260, min: 200, max: 340 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 1],
      HH: [2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['ottoman', 'asymmetric'],
    instruments: ['kudüm', 'def', 'ud'],
    swingable: false,
    story: 'The Turkish limp in 5 — two then three, forever rolling forward.',
  },
  {
    id: 'curcuna',
    name: 'Curcuna',
    origin: 'Turkey',
    tradition: 'Ottoman classical',
    genre: 'classical',
    timeSig: '10/8',
    grouping: [2, 3, 2, 3],
    stepUnit: 8,
    steps: 10,
    bpm: { default: 200, min: 140, max: 260 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 0, 2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 1, 0, 1, 0, 1, 1],
      HH: [2, 1, 2, 1, 1, 2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['ottoman', 'asymmetric', 'classical'],
    instruments: ['kudüm', 'bendir', 'ney'],
    swingable: false,
    story: 'Two Türk Aksağıs stacked — 2+3+2+3. The archetypal Ottoman asymmetric.',
  },
  {
    id: 'duyek',
    name: 'Düyek',
    origin: 'Turkey',
    tradition: 'Ottoman folk',
    genre: 'folk-dance',
    timeSig: '8/8',
    grouping: [4, 4],
    stepUnit: 8,
    steps: 8,
    bpm: { default: 220, min: 140, max: 280 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0],
      HH: [1, 1, 1, 1, 1, 1, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'turkey-ottoman',
    country: 'TR',
    tags: ['beginner', 'foundation', 'darbuka'],
    instruments: ['darbuka', 'ud'],
    swingable: false,
    story: 'The first rhythm every darbuka student learns. A foundation stone of Ottoman music.',
  },

  // ── BALKAN ───────────────────────────────────────────────────────
  {
    id: 'ruchenitsa',
    name: 'Rŭchenitsa',
    origin: 'Bulgaria',
    tradition: 'Folk dance',
    genre: 'folk-dance',
    timeSig: '7/8',
    grouping: [2, 2, 3],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 320, min: 240, max: 420 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0],
      SN: [0, 0, 0, 0, 0, 1, 1],
      HH: [2, 1, 2, 1, 2, 1, 1],
    },
    defaultKit: 'frameDrum',
    region: 'balkans',
    country: 'BG',
    tags: ['dance', 'line-dance', 'bulgarian'],
    instruments: ['gaida', 'kaval', 'tapan'],
    swingable: false,
    story: "Bulgaria's most danced rhythm — \"quick-quick-sloooow\" is how kids learn it.",
    relatedIds: ['horon'],
  },
  {
    id: 'kopanitsa',
    name: 'Kopanitsa',
    origin: 'Bulgaria · Shope',
    tradition: 'Folk dance',
    genre: 'folk-dance',
    timeSig: '11/8',
    grouping: [2, 2, 3, 2, 2],
    stepUnit: 8,
    steps: 11,
    bpm: { default: 400, min: 320, max: 520 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0],
      SN: [0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: 'frameDrum',
    region: 'balkans',
    country: 'BG',
    tags: ['dance', 'advanced', 'shope'],
    instruments: ['gaida', 'kaval', 'tapan'],
    swingable: false,
    story: '11/8 stomping through a tavern. The long beat is in the middle here.',
  },
  {
    id: 'daichovo',
    name: 'Daichovo',
    origin: 'Bulgaria',
    tradition: 'Folk dance',
    genre: 'folk-dance',
    timeSig: '9/8',
    grouping: [2, 2, 2, 3],
    stepUnit: 8,
    steps: 9,
    bpm: { default: 340, min: 280, max: 440 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 0, 1, 0, 1, 1],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    defaultKit: 'frameDrum',
    region: 'balkans',
    country: 'BG',
    tags: ['dance', 'bulgarian'],
    instruments: ['gaida', 'kaval'],
    swingable: false,
    story: 'Same 2+2+2+3 skeleton as Karşılama but faster, bouncier, pan-flute territory.',
    relatedIds: ['karsilama'],
  },
  {
    id: 'cocek',
    name: 'Čoček',
    origin: 'Balkans · Romani',
    tradition: 'Romani dance',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 240, min: 180, max: 340 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 1, 0],
      SN: [0, 0, 2, 0, 2, 0, 1, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'RS',
    region: 'balkans',
    tags: ['romani', 'dance', 'ottoman', 'syncopated'],
    instruments: ['zurna', 'tupan', 'clarinet'],
    swingable: false,
    story: 'The signature Romani dance of the Balkans — descended from Ottoman court dance, played on zurna and tupan at weddings.',
  },
  {
    id: 'kalamatianos',
    name: 'Kalamatianós',
    origin: 'Greece · Peloponnese',
    tradition: 'Circle dance',
    genre: 'folk-dance',
    timeSig: '7/8',
    grouping: [3, 2, 2],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 270, min: 220, max: 340 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 2, 0],
      SN: [0, 0, 1, 0, 1, 0, 1],
      HH: [2, 1, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'GR',
    region: 'balkans',
    tags: ['dance', 'circle', 'greek'],
    instruments: ['bouzouki', 'klarino', 'toubeleki'],
    swingable: false,
    story: 'The Greek national circle dance. Long-short-short, everyone holding hands.',
  },

  // ── AFRO-CUBAN ───────────────────────────────────────────────────
  {
    id: 'son-clave',
    name: 'Son Clave 3-2',
    origin: 'Cuba',
    tradition: 'Afro-Cuban',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 380, min: 280, max: 800 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1],
    },
    defaultKit: '727',
    region: 'cuba-afrocaribbean',
    country: 'CU',
    tags: ['clave', 'foundation', 'salsa'],
    instruments: ['claves', 'congas', 'bongos'],
    swingable: true,
    story: 'The spine of every Cuban son, salsa, and half of Latin music since 1800.',
  },
  {
    id: 'bembe',
    name: 'Bembé',
    origin: 'Cuba · Yoruba diaspora',
    tradition: 'Sacred bell pattern',
    genre: 'devotional',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 230, min: 180, max: 300 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    region: 'cuba-afrocaribbean',
    country: 'CU',
    tags: ['bell', 'sacred', 'afrobeat-ancestor'],
    instruments: ['atoke', 'congas', 'bata'],
    swingable: false,
    story: 'The 12/8 bell that underlies bembé, abakuá, and half the West African diaspora.',
  },
  {
    id: 'rumba-clave-3-2',
    name: 'Rumba Clave 3-2',
    origin: 'Cuba',
    tradition: 'Afro-Cuban rumba',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 400, min: 320, max: 560 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['clave', 'rumba', 'foundation'],
    instruments: ['claves', 'congas', 'palitos'],
    swingable: true,
    story: "Rumba's clave — the three-side's last stroke comes one 16th later than son. That delay is everything.",
    relatedIds: ['son-clave', 'guaguanco'],
  },
  {
    id: 'bolero',
    name: 'Bolero Cubano',
    origin: 'Cuba · Santiago',
    tradition: 'Afro-Cuban ballad',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 160, min: 100, max: 220 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 1, 0, 2, 0, 1, 0, 2, 0, 1, 0, 2, 0, 1, 0],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['romantic', 'slow', 'trova'],
    instruments: ['guitar', 'bongo', 'maracas'],
    swingable: false,
    story: 'The Cuban ballad — slow, tender, and built around the trova tradition of moonlit guitar serenades.',
  },
  {
    id: 'cha-cha',
    name: 'Cha-Cha-Chá',
    origin: 'Cuba',
    tradition: 'Dance hall',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 128, min: 100, max: 160 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['dance', 'ballroom', 'popular'],
    instruments: ['güiro', 'cha-cha bell', 'congas'],
    swingable: false,
    story: 'Violinist Enrique Jorrín slowed the mambo down so everybody could dance. The name comes from dancers\' shuffling feet.',
  },
  {
    id: 'mambo',
    name: 'Mambo',
    origin: 'Cuba · Havana',
    tradition: 'Dance hall / salsa',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 190, min: 160, max: 230 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 1, 0, 2, 0, 1, 0, 0, 1, 2, 0, 1, 0, 1, 0],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['salsa', 'big-band', 'dance'],
    instruments: ['timbales', 'mambo bell', 'conga'],
    swingable: true,
    story: 'The climax section of any salsa arrangement — when the band opens up and the mambo bell takes over.',
    relatedIds: ['son-clave'],
  },
  {
    id: 'guaguanco',
    name: 'Guaguancó',
    origin: 'Cuba · Havana / Matanzas',
    tradition: 'Rumba',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 108, min: 90, max: 130 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 1, 0, 0, 0, 2, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['rumba', 'folk', 'afro-cuban', 'palitos'],
    instruments: ['conga', 'claves', 'palitos'],
    swingable: false,
    story: 'The most popular form of rumba — a secular ritual born in Havana courtyards, where a male dancer pursues a female dancer in stylized courtship.',
    relatedIds: ['rumba-clave-3-2', 'rumba-columbia'],
  },
  {
    id: 'rumba-columbia',
    name: 'Rumba Columbia',
    origin: 'Cuba · Matanzas',
    tradition: 'Rumba (fast 6/8)',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 280, min: 240, max: 340 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
      SN: [0, 1, 0, 0, 0, 2, 0, 1, 0, 0, 0, 2],
      HH: [2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 0, 2],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['rumba', '12-8', 'abakua', 'virtuosic'],
    instruments: ['quinto', 'guataca', 'conga'],
    swingable: false,
    story: 'The fastest, most virtuosic rumba — a solo male dance of acrobatic and sometimes dangerous moves, rooted in Abakuá sacred rhythms from Calabar.',
    relatedIds: ['bembe'],
  },
  {
    id: 'comparsa',
    name: 'Comparsa',
    origin: 'Cuba · Santiago',
    tradition: 'Carnival procession',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 125, min: 110, max: 140 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0],
      HH: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['carnival', 'procession', 'street'],
    instruments: ['sartén', 'cowbell', 'conga'],
    swingable: false,
    story: 'The costumed carnival processions of Santiago — frying pans mounted on blocks, cowbells, and a river of drums rolling through the streets.',
  },
  {
    id: 'cascara',
    name: 'Cáscara',
    origin: 'Cuba',
    tradition: 'Timbale shell pattern',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 220, min: 160, max: 320 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 1, 2],
    },
    defaultKit: '727',
    country: 'CU',
    region: 'cuba-afrocaribbean',
    tags: ['timbale', 'salsa', 'shell', 'verse'],
    instruments: ['timbales', 'palitos', 'cowbell'],
    swingable: true,
    story: 'Played on the side of a timbal — slinky, sideways, reserved for mambo verses before the montuno opens up.',
    relatedIds: ['mambo'],
  },

  // ── ARABIC / SWANA ───────────────────────────────────────────────
  {
    id: 'maqsoum',
    name: 'Maqsoum',
    origin: 'Egypt',
    tradition: 'Pan-Arab pop',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 120, min: 100, max: 140 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 1, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'EG',
    region: 'arabic-swana',
    tags: ['pop', 'foundation', 'darbuka', 'bellydance'],
    instruments: ['darbuka', 'riqq', 'tabla baladi'],
    swingable: false,
    story: 'Dum-tek-tek, dum-tek. If you\'ve heard any Arabic pop song, you\'ve heard this — the most ubiquitous rhythm in the SWANA world.',
  },
  {
    id: 'baladi',
    name: 'Baladi',
    origin: 'Egypt',
    tradition: 'Folk / belly dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 100, min: 80, max: 120 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'EG',
    region: 'arabic-swana',
    tags: ['folk', 'bellydance', 'egyptian'],
    instruments: ['tabla baladi', 'mizmar', 'rebaba'],
    swingable: false,
    story: '"Baladi" means "of the country" — heavier and earthier than Maqsoum thanks to the double doum at the top of the bar.',
    relatedIds: ['maqsoum'],
  },
  {
    id: 'saidi',
    name: 'Saidi',
    origin: 'Egypt · Upper Egypt',
    tradition: 'Stick-dance (tahtib)',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 115, min: 100, max: 140 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'EG',
    region: 'arabic-swana',
    tags: ['folk', 'tahtib', 'martial', 'saidi'],
    instruments: ['tabla baladi', 'mizmar', 'rababa'],
    swingable: false,
    story: 'The rhythm of the Sa\'id region — Upper Egypt\'s stick-fighting dance. Heavy and martial, with a double-doum stomp that shakes the floor.',
  },
  {
    id: 'masmoudi-kebir',
    name: 'Masmoudi Kebir',
    origin: 'Egypt · Pan-Arab',
    tradition: 'Classical / belly dance entrance',
    genre: 'classical',
    timeSig: '8/4',
    grouping: [4, 4, 4, 4, 4, 4, 4, 4],
    stepUnit: 16,
    steps: 32,
    bpm: { default: 80, min: 60, max: 100 },
    difficulty: 'intermediate',
    tracks: {
      KK: [
        2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      ],
      SN: [
        0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0,
        0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0,
      ],
      HH: [
        2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1,
        2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1,
      ],
    },
    defaultKit: 'frameDrum',
    region: 'arabic-swana',
    tags: ['classical', 'bellydance', 'grand', 'entrance'],
    instruments: ['darbuka', 'riqq', 'oud'],
    swingable: false,
    story: '"Grand Masmoudi" — a stately 8-beat cycle used for dignified entrances and the openings of belly-dance sets. The spaciousness leaves room for dramatic gestures.',
  },
  {
    id: 'wahda',
    name: 'Wahda',
    origin: 'Pan-Arab',
    tradition: 'Classical taxim',
    genre: 'classical',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 65, min: 40, max: 90 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
    },
    defaultKit: 'frameDrum',
    region: 'arabic-swana',
    tags: ['classical', 'taxim', 'slow', 'unity'],
    instruments: ['riqq', 'oud', 'ney'],
    swingable: false,
    story: '"Wahda" means "one" — the rhythm of unity. Slow and spacious, it frames the soloist\'s taxim improvisation in classical wasla.',
  },
  {
    id: 'ayoub',
    name: 'Ayoub',
    origin: 'Egypt · Levant',
    tradition: 'Sufi / zar',
    genre: 'devotional',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 120, min: 80, max: 160 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    region: 'arabic-swana',
    tags: ['sufi', 'zar', 'trance', 'ancient'],
    instruments: ['bendir', 'daf', 'tar'],
    swingable: false,
    story: 'One of the oldest rhythms in SWANA — hypnotic simplicity that drives Sufi dhikr and zar healing ceremonies into trance as the tempo climbs.',
  },
  {
    id: 'samai-thaqil',
    name: 'Samai Thaqil',
    origin: 'Pan-Arab · Ottoman',
    tradition: 'Classical wasla',
    genre: 'classical',
    timeSig: '10/8',
    grouping: [3, 2, 2, 3],
    stepUnit: 8,
    steps: 10,
    bpm: { default: 75, min: 60, max: 100 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 2, 0, 2, 0, 0],
      SN: [0, 0, 0, 2, 0, 0, 2, 0, 0, 2],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    region: 'arabic-swana',
    tags: ['classical', 'ottoman', 'samai', 'wasla'],
    instruments: ['riqq', 'qanun', 'ud'],
    swingable: false,
    story: 'The grand classical rhythm of the samai compositional form — stately, slow, and central to the Arabic wasla suite.',
  },
  {
    id: 'chiftetelli',
    name: 'Chiftetelli',
    origin: 'Turkey · Pan-Ottoman',
    tradition: 'Belly dance / Romani',
    genre: 'popular',
    timeSig: '8/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 100, min: 80, max: 120 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'TR',
    region: 'arabic-swana',
    tags: ['bellydance', 'romani', 'ottoman', 'oriental'],
    instruments: ['darbuka', 'ud', 'clarinet'],
    swingable: false,
    story: 'The iconic belly-dance rhythm — "double-stringed," deep in Romani and oriental dance traditions from Istanbul to Athens.',
  },

  // ── PERSIA ───────────────────────────────────────────────────────
  {
    id: 'reng',
    name: 'Reng',
    origin: 'Iran',
    tradition: 'Persian classical finale',
    genre: 'classical',
    timeSig: '6/8',
    grouping: [3, 3],
    stepUnit: 8,
    steps: 6,
    bpm: { default: 150, min: 120, max: 200 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0],
      SN: [0, 0, 2, 0, 2, 1],
      HH: [2, 1, 2, 2, 1, 2],
    },
    defaultKit: 'frameDrum',
    country: 'IR',
    region: 'persia',
    tags: ['classical', 'dastgah', 'dance', 'finale'],
    instruments: ['tombak', 'daf', 'tar'],
    swingable: false,
    story: 'The dance finale of a Persian dastgah suite — light, playful, a release after the meditative avaz sections.',
  },
  {
    id: 'tasnif-4-4',
    name: 'Tasnif',
    origin: 'Iran',
    tradition: 'Persian art song',
    genre: 'classical',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 90, min: 70, max: 120 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'frameDrum',
    country: 'IR',
    region: 'persia',
    tags: ['art-song', 'classical', 'vocal'],
    instruments: ['tombak', 'tar', 'setar'],
    swingable: false,
    story: 'The metric art-song form at the heart of Persian classical music — a poem set within a rhythmic cycle, where tombak and voice weave together.',
  },
  {
    id: 'chaharmezrab',
    name: 'Chaharmezrab',
    origin: 'Iran',
    tradition: 'Persian virtuoso piece',
    genre: 'classical',
    timeSig: '6/16',
    grouping: [3, 3],
    stepUnit: 16,
    steps: 6,
    bpm: { default: 180, min: 140, max: 240 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0],
      SN: [0, 2, 1, 0, 2, 1],
      HH: [2, 2, 2, 2, 2, 2],
    },
    defaultKit: 'frameDrum',
    country: 'IR',
    region: 'persia',
    tags: ['virtuoso', 'fast', 'dastgah'],
    instruments: ['santur', 'tombak', 'tar'],
    swingable: false,
    story: '"Four-plectrum-strokes" — a fast, virtuosic instrumental étude built on a repeating rhythmic cell, used to display technique in a dastgah.',
  },

  // ── INDIA ────────────────────────────────────────────────────────
  {
    id: 'tintal',
    name: 'Tintal',
    origin: 'India · Hindustani',
    tradition: 'Tabla cycle',
    genre: 'classical',
    timeSig: '16/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 8,
    steps: 16,
    bpm: { default: 180, min: 120, max: 400 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 1, 0, 0, 0, 1, 0, 2, 0, 1, 0, 0, 0, 1, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'hindustani', 'foundation', 'classical'],
    instruments: ['tabla', 'sitar', 'sarod'],
    swingable: false,
    story: '16 beats, four vibhags, one of the most common cycles in Hindustani music. The khali on beat 9 is the moment everything relaxes before returning home.',
  },
  {
    id: 'dadra',
    name: 'Dadra',
    origin: 'India · Hindustani',
    tradition: 'Light classical / film',
    genre: 'classical',
    timeSig: '6/4',
    grouping: [3, 3],
    stepUnit: 4,
    steps: 6,
    bpm: { default: 110, min: 80, max: 140 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0],
      SN: [0, 2, 1, 0, 2, 1],
      HH: [2, 1, 2, 2, 1, 2],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'light-classical', 'thumri', 'film'],
    instruments: ['tabla', 'harmonium', 'sarangi'],
    swingable: false,
    story: 'A gentle 6-beat cycle that lilts like a waltz — the signature groove of thumri, bhajans, and romantic Bollywood ballads.',
  },
  {
    id: 'rupak',
    name: 'Rupak Tal',
    origin: 'India · Hindustani',
    tradition: 'Tabla cycle',
    genre: 'classical',
    timeSig: '7/4',
    grouping: [3, 2, 2],
    stepUnit: 4,
    steps: 7,
    bpm: { default: 90, min: 60, max: 130 },
    difficulty: 'intermediate',
    tracks: {
      KK: [0, 0, 0, 2, 0, 2, 0],
      SN: [2, 1, 1, 0, 0, 0, 0],
      HH: [1, 1, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'hindustani', 'asymmetric', 'khali-start'],
    instruments: ['tabla', 'bansuri', 'sitar'],
    swingable: false,
    story: 'Rupak is unusual — the first beat (sam) is actually a khali (empty) stroke. The cycle starts weak and resolves inward.',
  },
  {
    id: 'ektal',
    name: 'Ektal',
    origin: 'India · Hindustani',
    tradition: 'Vilambit khayal',
    genre: 'classical',
    timeSig: '12/4',
    grouping: [2, 2, 2, 2, 2, 2],
    stepUnit: 4,
    steps: 12,
    bpm: { default: 40, min: 20, max: 80 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0],
      SN: [0, 0, 0, 0, 2, 0, 2, 0, 0, 1, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'vilambit', 'khayal', 'slow'],
    instruments: ['tabla', 'sarangi', 'voice'],
    swingable: false,
    story: '12 beats, six vibhags. At vilambit tempo each beat becomes a canvas — the master tabla player elaborates endlessly between the landmarks.',
  },
  {
    id: 'jhaptal',
    name: 'Jhaptal',
    origin: 'India · Hindustani',
    tradition: 'Tabla cycle',
    genre: 'classical',
    timeSig: '10/4',
    grouping: [2, 3, 2, 3],
    stepUnit: 4,
    steps: 10,
    bpm: { default: 96, min: 60, max: 140 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 2, 0, 0, 2, 0],
      SN: [0, 1, 0, 0, 1, 0, 1, 0, 0, 1],
      HH: [2, 1, 1, 2, 1, 2, 1, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'hindustani', 'asymmetric', 'dhrupad'],
    instruments: ['tabla', 'rudra veena', 'voice'],
    swingable: false,
    story: '10 beats grouped 2+3+2+3 — the same skeleton as Ottoman Curcuna, but arrived at through a completely different tradition.',
    relatedIds: ['curcuna'],
  },
  {
    id: 'keherwa',
    name: 'Keherwa',
    origin: 'India · Hindustani',
    tradition: 'Folk / light classical',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4],
    stepUnit: 8,
    steps: 8,
    bpm: { default: 120, min: 80, max: 200 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 1, 0, 0, 2, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'folk', 'bhajan', 'qawwali', 'bollywood'],
    instruments: ['tabla', 'dholak', 'harmonium'],
    swingable: false,
    story: 'The most common tala in Indian light music — bhajans, ghazals, qawwalis, and half the Bollywood catalogue rest on this 8-beat foundation.',
  },
  {
    id: 'deepchandi',
    name: 'Deepchandi',
    origin: 'India · Hindustani',
    tradition: 'Thumri / romantic classical',
    genre: 'classical',
    timeSig: '14/4',
    grouping: [3, 4, 3, 4],
    stepUnit: 4,
    steps: 14,
    bpm: { default: 65, min: 40, max: 100 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0],
      HH: [2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['tabla', 'thumri', 'romantic', 'asymmetric'],
    instruments: ['tabla', 'sarangi', 'voice'],
    swingable: false,
    story: 'A majestic 14-beat tala for thumri and romantic classical forms — the alternating 3+4 grouping creates a long, lilting rocking cycle.',
  },
  {
    id: 'chautal',
    name: 'Chautal',
    origin: 'India · Hindustani',
    tradition: 'Dhrupad',
    genre: 'classical',
    timeSig: '12/4',
    grouping: [2, 2, 2, 2, 2, 2],
    stepUnit: 4,
    steps: 12,
    bpm: { default: 120, min: 80, max: 180 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 2, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['pakhawaj', 'dhrupad', 'classical'],
    instruments: ['pakhawaj', 'rudra veena', 'voice'],
    swingable: false,
    story: 'The 12-beat cycle of dhrupad — India\'s oldest surviving classical vocal form, played on the thunderous pakhawaj rather than tabla.',
  },
  {
    id: 'adi-tala',
    name: 'Adi Tala',
    origin: 'India · Carnatic',
    tradition: 'South Indian classical',
    genre: 'classical',
    timeSig: '8/4',
    grouping: [4, 2, 2],
    stepUnit: 8,
    steps: 16,
    bpm: { default: 110, min: 60, max: 160 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['mridangam', 'carnatic', 'foundation', 'classical'],
    instruments: ['mridangam', 'ghatam', 'veena'],
    swingable: false,
    story: 'The most common Carnatic tala — "adi" means "first" or "primary." 8 beats: laghu, drutam, drutam. The bedrock of South Indian classical music.',
  },
  {
    id: 'khanda-chapu',
    name: 'Khanda Chapu',
    origin: 'India · Carnatic',
    tradition: 'South Indian classical',
    genre: 'classical',
    timeSig: '5/4',
    grouping: [2, 1, 2],
    stepUnit: 8,
    steps: 10,
    bpm: { default: 120, min: 80, max: 160 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 1, 0, 0, 0, 0, 2, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: 'tabla',
    country: 'IN',
    region: 'india',
    tags: ['mridangam', 'carnatic', '5-beat', 'chapu'],
    instruments: ['mridangam', 'kanjira', 'voice'],
    swingable: false,
    story: '"Khanda" means five. A 5-beat Carnatic tala grouped 2+1+2 — uneven, with a distinctive hop at the single-beat middle.',
  },

  // ── WEST AFRICA ──────────────────────────────────────────────────
  {
    id: 'agbekor',
    name: 'Agbekor',
    origin: 'Ghana · Ewe',
    tradition: 'Anlo Ewe war dance',
    genre: 'ceremonial',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 115, min: 100, max: 130 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2],
      HH: [2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2, 0],
    },
    defaultKit: '727',
    country: 'GH',
    region: 'west-africa',
    tags: ['ewe', 'war-dance', 'bell', 'ceremony'],
    instruments: ['gankogui', 'axatse', 'atsimevu'],
    swingable: false,
    story: 'An Anlo Ewe war dance from Ghana, now performed at funerals and festivals. The gankogui bell timeline holds everything together while sogo and atsimevu interlock.',
  },
  {
    id: 'gahu',
    name: 'Gahu',
    origin: 'Ghana · Ewe',
    tradition: 'Social dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 120, min: 110, max: 135 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0],
    },
    defaultKit: '727',
    country: 'GH',
    region: 'west-africa',
    tags: ['ewe', 'social', 'dance', 'yoruba-origin'],
    instruments: ['gankogui', 'axatse', 'kidi'],
    swingable: false,
    story: 'Borrowed by the Ewe from Yoruba-speaking peoples via Benin. Lighter and more celebratory than Agbekor, and often the first ensemble rhythm a drum-class learns.',
    relatedIds: ['agbekor'],
  },
  {
    id: 'kpanlogo',
    name: 'Kpanlogo',
    origin: 'Ghana · Ga',
    tradition: 'Social dance',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 115, min: 105, max: 125 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0],
      HH: [2, 0, 0, 2, 0, 0, 2, 1, 0, 0, 2, 0, 0, 2, 0, 1],
    },
    defaultKit: '727',
    country: 'GH',
    region: 'west-africa',
    tags: ['ga', 'urban', 'dance', 'highlife'],
    instruments: ['kpanlogo drums', 'nono bell', 'afiri'],
    swingable: false,
    story: 'Invented in 1960s Accra by Ga youth — a conga-based social dance that fused traditional Ga drumming with highlife and rock, now Ghana\'s de facto national rhythm.',
  },
  {
    id: 'kuku',
    name: 'Kuku',
    origin: 'Guinea · Malinke',
    tradition: 'Fishermen\'s celebration',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 145, min: 130, max: 160 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 1, 2, 0, 1, 0, 2, 0],
      HH: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
    },
    defaultKit: '727',
    country: 'GN',
    region: 'west-africa',
    tags: ['djembe', 'malinke', 'celebration', 'beginner-ensemble'],
    instruments: ['djembe', 'dundun', 'kenkeni'],
    swingable: false,
    story: 'Originally played for women returning from fishing trips. Now the first djembe ensemble rhythm taught worldwide — driving, joyful, endlessly danceable.',
  },
  {
    id: 'soli',
    name: 'Soli',
    origin: 'Guinea · Malinke',
    tradition: 'Initiation ceremony',
    genre: 'ceremonial',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 120, min: 100, max: 140 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 1, 0, 2, 0, 1, 0, 2, 0],
      HH: [2, 1, 0, 2, 1, 2, 2, 0, 1, 2, 0, 0],
    },
    defaultKit: '727',
    country: 'GN',
    region: 'west-africa',
    tags: ['djembe', 'malinke', 'ritual', 'initiation'],
    instruments: ['djembe', 'dundunba', 'sangban'],
    swingable: false,
    story: 'The initiation rhythm of Malinke Guinea — it accompanies the dance-stories of young people crossing from childhood to adulthood. Sacred in its traditional context.',
  },
  {
    id: 'dununba',
    name: 'Dununba',
    origin: 'Guinea · Malinke',
    tradition: 'Strong men\'s dance',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 130, min: 110, max: 145 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0],
      SN: [0, 0, 2, 1, 2, 1, 0, 0, 0, 2, 1, 2, 1, 0, 0, 0],
      HH: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
    },
    defaultKit: '727',
    country: 'GN',
    region: 'west-africa',
    tags: ['djembe', 'dundun', 'strength', 'acrobatic'],
    instruments: ['dundunba', 'djembe', 'kenkeni'],
    swingable: false,
    story: 'The dance of the strong men — acrobatic, muscular, led by the booming dundunba drum the rhythm is named after.',
  },
  {
    id: 'fanga',
    name: 'Fanga',
    origin: 'Liberia · Pan-West-African',
    tradition: 'Welcome dance',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 115, min: 100, max: 130 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'LR',
    region: 'west-africa',
    tags: ['welcome', 'pan-african', 'beginner'],
    instruments: ['djembe', 'conga', 'shekere'],
    swingable: false,
    story: 'A welcome rhythm spread across the African diaspora in the 1960s by Babatunde Olatunji. The doors open, the drums speak, the guests enter.',
  },
  {
    id: 'adowa',
    name: 'Adowa',
    origin: 'Ghana · Ashanti',
    tradition: 'Funeral / royal dance',
    genre: 'ceremonial',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 110, min: 90, max: 130 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0],
      SN: [0, 0, 2, 0, 1, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 2, 0],
    },
    defaultKit: '727',
    country: 'GH',
    region: 'west-africa',
    tags: ['akan', 'ashanti', 'funeral', 'royal'],
    instruments: ['atumpan', 'adowa drums', 'dawuro'],
    swingable: false,
    story: 'The most widespread Akan dance — performed at funerals, royal gatherings, and festivals. Graceful hand-and-foot gestures tell proverbs through movement.',
  },
  {
    id: 'bembe-68',
    name: 'Bembé 6/8',
    origin: 'West Africa · Yoruba',
    tradition: 'Sacred bell timeline',
    genre: 'devotional',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 230, min: 180, max: 300 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
      SN: [0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 2, 0],
      HH: [2, 0, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2],
    },
    defaultKit: '727',
    region: 'west-africa',
    tags: ['yoruba', 'bell', 'sacred', 'standard-pattern'],
    instruments: ['agogô', 'bata', 'shekere'],
    swingable: false,
    story: 'The "standard pattern" — the 12/8 bell timeline that traveled from Yorubaland to Havana to Salvador and anchors half the African diaspora\'s music.',
    relatedIds: ['bembe'],
  },
  {
    id: 'djembe-standard',
    name: 'Djembe Standard',
    origin: 'Mali · Mande',
    tradition: 'Djembe ensemble',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 130, min: 110, max: 160 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 1, 0, 2, 0, 0, 2, 1, 0, 2],
      HH: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
    },
    defaultKit: '727',
    country: 'ML',
    region: 'west-africa',
    tags: ['djembe', 'mande', 'foundation', 'ensemble'],
    instruments: ['djembe', 'dundun', 'kenkeni'],
    swingable: false,
    story: 'The archetypal djembe accompaniment — tones and slaps interlocking over the kenkeni pulse. Mande culture\'s most traveled rhythmic export.',
  },

  // ── BRAZIL ───────────────────────────────────────────────────────
  {
    id: 'bossa-nova',
    name: 'Bossa Nova',
    origin: 'Brazil · Rio de Janeiro',
    tradition: 'Cool jazz / samba',
    genre: 'jazz',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 128, min: 70, max: 160 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['jazz', 'cool', 'partido-alto', 'ipanema'],
    instruments: ['nylon guitar', 'brushes', 'surdo'],
    swingable: true,
    story: 'Jobim and João Gilberto slowed samba down, stripped it bare, and dressed it in cool-jazz harmony. The cross-stick traces the partido-alto skeleton.',
    relatedIds: ['samba-partido-alto'],
  },
  {
    id: 'samba-partido-alto',
    name: 'Samba Partido Alto',
    origin: 'Brazil · Rio de Janeiro',
    tradition: 'Samba subgenre',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 110, min: 90, max: 130 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 2, 0, 0, 2, 0],
      HH: [2, 0, 1, 0, 2, 0, 1, 0],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['samba', 'partido-alto', 'pagode', 'pandeiro'],
    instruments: ['pandeiro', 'tantã', 'cavaquinho'],
    swingable: true,
    story: 'Older, rootsier samba — circled around improvised verses and hand percussion. The partido-alto pattern became the "Brazilian clave" that crossed into bossa and jazz.',
  },
  {
    id: 'samba-reggae',
    name: 'Samba-Reggae',
    origin: 'Brazil · Salvador, Bahia',
    tradition: 'Olodum / bloco afro',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 105, min: 90, max: 120 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['bahia', 'olodum', 'bloco-afro', 'interlocking-surdos'],
    instruments: ['surdo', 'repique', 'caixa'],
    swingable: false,
    story: 'Created in 1986 by Neguinho do Samba for Olodum — samba\'s surdo foundation married to reggae\'s tempo, three drums interlocking into a wall of bass through the streets of Salvador.',
  },
  {
    id: 'baiao',
    name: 'Baião',
    origin: 'Brazil · Northeast',
    tradition: 'Forró',
    genre: 'folk-dance',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 120, min: 100, max: 140 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 1, 0, 0, 0, 0, 1],
      HH: [2, 0, 2, 2, 2, 0, 2, 2],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['forró', 'zabumba', 'accordion', 'sertão'],
    instruments: ['zabumba', 'triangle', 'sanfona'],
    swingable: false,
    story: 'The foundational rhythm of forró, from the arid sertão of Pernambuco — zabumba bass-and-slap, triangle, accordion. Luiz Gonzaga brought it to the whole country.',
  },
  {
    id: 'maracatu',
    name: 'Maracatu',
    origin: 'Brazil · Pernambuco',
    tradition: 'Afro-Brazilian procession',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 95, min: 80, max: 110 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '727',
    country: 'BR',
    region: 'brazil',
    tags: ['afro-brazilian', 'procession', 'alfaia', 'candomble'],
    instruments: ['alfaia', 'gongue', 'caixa'],
    swingable: false,
    story: 'One of Brazil\'s oldest Afro-descended traditions — born from the coronation processions of enslaved African "kings and queens" in colonial Pernambuco.',
  },

  // ── CARIBBEAN MODERN ─────────────────────────────────────────────
  {
    id: 'reggaeton-dembow',
    name: 'Reggaeton Dembow',
    origin: 'Puerto Rico · Dominican Republic',
    tradition: 'Urbano',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 95, min: 85, max: 105 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
      SN: [0, 0, 0, 1, 2, 0, 0, 1, 0, 0, 0, 1, 2, 0, 0, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '808',
    country: 'PR',
    region: 'caribbean',
    tags: ['urbano', 'dembow', 'perreo', 'latin'],
    instruments: ['808 kick', 'clap', 'timbale'],
    swingable: false,
    story: 'The dembow riddim that conquered the world — Jamaican dancehall mutated through Panama, Puerto Rico and the DR into the global sound of reggaeton.',
    relatedIds: ['dancehall'],
  },
  {
    id: 'dancehall',
    name: 'Dancehall',
    origin: 'Jamaica',
    tradition: 'Dancehall riddim',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 100, min: 80, max: 120 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '808',
    country: 'JM',
    region: 'caribbean',
    tags: ['jamaica', 'riddim', 'sound-system'],
    instruments: ['808', 'syndrum', 'bass'],
    swingable: false,
    story: 'Kingston sound systems, digital riddims, Shabba Ranks and Vybz Kartel. Every modern Caribbean dance pattern traces back here.',
  },
  {
    id: 'kompa',
    name: 'Kompa',
    origin: 'Haiti',
    tradition: 'Haitian popular',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 115, min: 100, max: 130 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '808',
    country: 'HT',
    region: 'caribbean',
    tags: ['haiti', 'tanbou', 'sensual', 'mini-djaz'],
    instruments: ['tanbou', 'cowbell', 'bass'],
    swingable: false,
    story: 'Nemours Jean-Baptiste\'s 1955 invention — a slow, sensual grind built on cowbell, tanbou, and bass. Haiti\'s national sound, and UNESCO heritage since 2025.',
  },
  {
    id: 'soca',
    name: 'Soca',
    origin: 'Trinidad and Tobago',
    tradition: 'Carnival',
    genre: 'popular',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 142, min: 130, max: 160 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 1],
      HH: [2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1],
    },
    defaultKit: '808',
    country: 'TT',
    region: 'caribbean',
    tags: ['carnival', 'trinidad', 'indian-fusion', 'soca'],
    instruments: ['drums', 'iron', 'tassa'],
    swingable: false,
    story: 'Lord Shorty\'s 1970s fusion of calypso with East Indian rhythms — the "soul of calypso." The signature hi-hat opens on the last sixteenth of every beat.',
  },

  // ── IBERIA / FLAMENCO ────────────────────────────────────────────
  {
    id: 'buleria',
    name: 'Bulería',
    origin: 'Spain · Jerez',
    tradition: 'Flamenco fiesta',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [2, 2, 2, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 220, min: 180, max: 260 },
    difficulty: 'advanced',
    tracks: {
      KK: [0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0],
      SN: [2, 0, 0, 2, 0, 0, 2, 0, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'gitano', 'compas', 'fiesta'],
    instruments: ['cajón', 'palmas', 'guitarra'],
    swingable: false,
    story: 'The fastest flamenco palo — the climax of any Gitano fiesta in Jerez. Accents fall on 3, 6, 8, 10, and 12, but phrases typically start on beat 12 itself.',
    relatedIds: ['solea'],
  },
  {
    id: 'solea',
    name: 'Soleá',
    origin: 'Spain · Seville / Cádiz',
    tradition: 'Cante jondo',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [2, 2, 2, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 100, min: 80, max: 120 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 2, 0, 2, 0, 2],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'cante-jondo', 'compas', 'deep'],
    instruments: ['cajón', 'palmas', 'guitarra'],
    swingable: false,
    story: 'The "mother" of flamenco — slow, dignified, deeply emotional. Same 12-beat accent pattern as bulería but at half the speed and twice the weight.',
    relatedIds: ['buleria'],
  },
  {
    id: 'tangos-flamenco',
    name: 'Tangos (Flamenco)',
    origin: 'Spain · Cádiz / Seville',
    tradition: 'Flamenco palo',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 130, min: 120, max: 160 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '727',
    country: 'ES',
    region: 'iberia-flamenco',
    tags: ['flamenco', 'tangos', '4-beat', 'dance'],
    instruments: ['cajón', 'palmas', 'guitarra'],
    swingable: false,
    story: 'Not Argentine tango — the flamenco tangos of Cádiz and Triana. The first beat of each group is subdued; beats 2, 3, 4 carry the drive.',
  },

  // ── GAMELAN / SE ASIA ────────────────────────────────────────────
  {
    id: 'lancaran',
    name: 'Lancaran',
    origin: 'Indonesia · Java',
    tradition: 'Javanese gamelan',
    genre: 'classical',
    timeSig: '16/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 8,
    steps: 16,
    bpm: { default: 120, min: 90, max: 160 },
    difficulty: 'intermediate',
    tracks: {
      KK: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2],
      SN: [0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
      OH: [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2],
      CP: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: 'gamelan',
    country: 'ID',
    region: 'gamelan-southeast-asia',
    tags: ['javanese', 'colotomic', 'fast', 'gongan'],
    instruments: ['gong', 'kenong', 'kempul', 'saron'],
    swingable: false,
    story: 'The shortest standard Javanese gongan — lively and fast. The gong ageng closes the 16-beat cycle, kenong marks each kenongan, and kempul fills in the middle.',
  },
  {
    id: 'kotekan',
    name: 'Kotekan',
    origin: 'Indonesia · Bali',
    tradition: 'Balinese gamelan',
    genre: 'classical',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 160, min: 140, max: 200 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
      OH: [0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2],
    },
    defaultKit: 'gamelan',
    country: 'ID',
    region: 'gamelan-southeast-asia',
    tags: ['balinese', 'interlocking', 'kebyar', 'polos-sangsih'],
    instruments: ['reyong', 'gangsa', 'gong'],
    swingable: false,
    story: 'The interlocking heart of Balinese kebyar — polos falls on the beat, sangsih between them. Alone each is incomplete; together they sound twice as fast as either can play.',
  },
  {
    id: 'gendhing-sederhana',
    name: 'Gendhing Sederhana',
    origin: 'Indonesia · Java',
    tradition: 'Javanese court gamelan',
    genre: 'classical',
    timeSig: '16/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 8,
    steps: 16,
    bpm: { default: 75, min: 50, max: 100 },
    difficulty: 'intermediate',
    tracks: {
      KK: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2],
      SN: [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2],
      HH: [2, 0, 1, 0, 2, 0, 1, 0, 2, 0, 1, 0, 2, 0, 1, 0],
      CP: [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
    },
    defaultKit: 'gamelan',
    country: 'ID',
    region: 'gamelan-southeast-asia',
    tags: ['javanese', 'colotomic', 'meditative', 'court'],
    instruments: ['gong ageng', 'kethuk', 'kempyang'],
    swingable: false,
    story: 'A simple gendhing — the meditative, introspective form heard in kraton court music and behind vocal and dance performance. The gong breathes slowly.',
  },

  // ── EAST ASIA ────────────────────────────────────────────────────
  {
    id: 'taiko-base',
    name: 'Taiko Jiuchi',
    origin: 'Japan',
    tradition: 'Kumi-daiko',
    genre: 'ceremonial',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 130, min: 80, max: 180 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 1, 2, 0, 0, 1, 2, 0, 0, 1, 2, 0, 0, 1, 2],
      HH: [2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
    },
    defaultKit: '808',
    country: 'JP',
    region: 'east-asia',
    tags: ['taiko', 'matsuri', 'japanese', 'festival'],
    instruments: ['odaiko', 'shime-daiko', 'chappa'],
    swingable: false,
    story: 'The "don-ka don-ka" jiuchi that underlies nearly every matsuri festival piece — odaiko center hits, shime rim answers, the heartbeat of Japanese ensemble drumming.',
  },
  {
    id: 'samulnori',
    name: 'Samulnori · Jajinmori',
    origin: 'Korea',
    tradition: 'Four-instrument percussion',
    genre: 'folk-dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 160, min: 140, max: 200 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2],
      HH: [2, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1],
      OH: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    },
    defaultKit: 'gamelan',
    country: 'KR',
    region: 'east-asia',
    tags: ['korean', 'changdan', 'pungmul', 'percussion'],
    instruments: ['janggu', 'kkwaenggwari', 'buk', 'jing'],
    swingable: false,
    story: 'Kim Duk-soo\'s 1978 reinvention of outdoor pungmul drumming for the concert stage — small gong leads, hourglass janggu answers, barrel buk and great jing ground the cycle.',
  },

  // ── CELTIC / EUROPE ──────────────────────────────────────────────
  {
    id: 'irish-reel',
    name: 'Irish Reel',
    origin: 'Ireland',
    tradition: 'Ceili session',
    genre: 'folk-dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 115, min: 100, max: 130 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
      HH: [2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0],
    },
    defaultKit: '707',
    country: 'IE',
    region: 'celtic-europe',
    tags: ['celtic', 'irish', 'session', 'bodhran'],
    instruments: ['bodhrán', 'fiddle', 'tin whistle'],
    swingable: false,
    story: 'The most common tune type in Irish sessions — driving eighth notes, strong pulse on 1 and 3, bodhrán accenting the main beats with a tipper.',
  },
  {
    id: 'jig',
    name: 'Irish Jig',
    origin: 'Ireland',
    tradition: 'Ceili / dance',
    genre: 'folk-dance',
    timeSig: '6/8',
    grouping: [3, 3],
    stepUnit: 8,
    steps: 6,
    bpm: { default: 120, min: 100, max: 135 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 1, 0, 0],
      SN: [0, 0, 2, 0, 0, 2],
      HH: [2, 1, 2, 2, 1, 2],
    },
    defaultKit: '707',
    country: 'IE',
    region: 'celtic-europe',
    tags: ['celtic', 'irish', 'compound', '6-8', 'dance'],
    instruments: ['bodhrán', 'fiddle', 'flute'],
    swingable: false,
    story: 'Two groups of three — "DI-di-di, DI-di-di" — the bouncing lilt that fuels half the Irish repertoire after the reel.',
  },
  {
    id: 'scandi-polska',
    name: 'Scandi Polska',
    origin: 'Sweden · Dalarna',
    tradition: 'Swedish folk couple dance',
    genre: 'folk-dance',
    timeSig: '3/4',
    grouping: [4, 4, 4],
    stepUnit: 16,
    steps: 12,
    bpm: { default: 120, min: 100, max: 140 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0],
      HH: [2, 0, 1, 0, 2, 0, 1, 0, 2, 0, 1, 0],
    },
    defaultKit: '707',
    country: 'SE',
    region: 'celtic-europe',
    tags: ['scandinavian', 'swedish', 'asymmetric', 'nyckelharpa'],
    instruments: ['nyckelharpa', 'fiddle'],
    swingable: true,
    story: 'A Swedish couple dance in 3 — but the beats are unequal. Played on nyckelharpa, the beat-2 delay is an intentional feature tied to the dance, not a mistake.',
  },

  // ── ELECTRONIC / WESTERN ─────────────────────────────────────────
  {
    id: 'boom-bap',
    name: 'Boom Bap',
    origin: 'USA · New York',
    tradition: 'Golden-era hip-hop',
    genre: 'hip-hop',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 90, min: 82, max: 98 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    defaultKit: '808',
    country: 'US',
    region: 'electronic-western',
    tags: ['hip-hop', 'sampler', 'golden-era', 'sp-1200'],
    instruments: ['MPC', 'SP-1200', 'vinyl'],
    swingable: true,
    story: 'The crunchy, sampled drum break of 1990s New York hip-hop — DJ Premier, Pete Rock, and the SP-1200. Kick, snare, and swung sixteenths on a chopped loop.',
  },
  {
    id: 'four-on-the-floor',
    name: 'Four on the Floor',
    origin: 'USA · Chicago / Detroit',
    tradition: 'House / techno',
    genre: 'electronic',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 124, min: 110, max: 140 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    defaultKit: '909',
    country: 'US',
    region: 'electronic-western',
    tags: ['house', 'techno', '909', 'foundation'],
    instruments: ['TR-909', 'clap', 'hi-hat'],
    swingable: false,
    story: 'Every 909 house record ever — four straight kicks, offbeat hats, clap on 2 and 4. The metronome-to-club pipeline in one bar.',
  },

  // ── POLYRHYTHM EXERCISES (per-track subdivisions) ────────────────
  {
    id: 'hemiola-3-2',
    name: 'Hemiola (3:2)',
    origin: '—',
    tradition: 'Polyrhythm exercise',
    genre: 'exercise',
    timeSig: '2/4',
    grouping: [2],
    stepUnit: 4,
    steps: 2,
    poly: true,
    bpm: { default: 120, min: 60, max: 200 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0],
      SN: { pattern: [2, 0, 0], subdivisions: 3 },
    },
    defaultKit: '707',
    region: 'exercise',
    tags: ['polyrhythm', '3-over-2', 'exercise'],
    swingable: false,
    story: 'The simplest polyrhythm — three notes in the time of two. The foundation of most polyrhythmic music, from West African bell patterns to jazz.',
  },
  {
    id: 'triplet-over-quarters',
    name: 'Triplets over Quarters (3:4)',
    origin: '—',
    tradition: 'Polyrhythm exercise',
    genre: 'exercise',
    timeSig: '4/4',
    grouping: [4],
    stepUnit: 4,
    steps: 4,
    poly: true,
    bpm: { default: 120, min: 60, max: 200 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 2, 0],
      HH: { pattern: [2, 0, 0], subdivisions: 3 },
    },
    defaultKit: '707',
    region: 'exercise',
    tags: ['polyrhythm', '3-over-4', 'triplet', 'exercise'],
    swingable: false,
    story: 'Three evenly-spaced notes across one bar of four — the classic jazz/funk polyrhythm. Every practicing drummer should internalize this.',
  },
  {
    id: 'four-over-three',
    name: 'Four over Three (4:3)',
    origin: '—',
    tradition: 'Polyrhythm exercise',
    genre: 'exercise',
    timeSig: '3/4',
    grouping: [3],
    stepUnit: 4,
    steps: 3,
    poly: true,
    bpm: { default: 100, min: 60, max: 180 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0],
      HH: { pattern: [2, 0, 0, 0], subdivisions: 4 },
    },
    defaultKit: '707',
    region: 'exercise',
    tags: ['polyrhythm', '4-over-3', 'exercise'],
    swingable: false,
    story: "The inverse of 3-over-4. Feels 'slippery' because neither side lines up except at the downbeat.",
  },
  {
    id: 'five-over-four',
    name: 'Five over Four (5:4)',
    origin: '—',
    tradition: 'Polyrhythm exercise',
    genre: 'exercise',
    timeSig: '4/4',
    grouping: [4],
    stepUnit: 4,
    steps: 4,
    poly: true,
    bpm: { default: 100, min: 60, max: 180 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0],
      HH: { pattern: [2, 0, 0, 0, 0], subdivisions: 5 },
    },
    defaultKit: '707',
    region: 'exercise',
    tags: ['polyrhythm', '5-over-4', 'experimental', 'exercise'],
    swingable: false,
    story: 'Quintuplets over quarters. Found in Carnatic khanda and contemporary jazz — Vijay Iyer territory.',
  },
  {
    id: 'seven-over-four',
    name: 'Seven over Four (7:4)',
    origin: '—',
    tradition: 'Polyrhythm exercise',
    genre: 'exercise',
    timeSig: '4/4',
    grouping: [4],
    stepUnit: 4,
    steps: 4,
    poly: true,
    bpm: { default: 100, min: 60, max: 160 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0],
      HH: { pattern: [2, 0, 0, 0, 0, 0, 0], subdivisions: 7 },
    },
    defaultKit: '707',
    region: 'exercise',
    tags: ['polyrhythm', '7-over-4', 'experimental', 'exercise'],
    swingable: false,
    story: 'Septuplets over quarters. Rare in tradition — common in konnakol (Indian rhythmic solfège) exercises.',
  },
];

export function patternById(id: string): Pattern | undefined {
  return PATTERNS.find((p) => p.id === id);
}
