// First-pass seed library — 10 patterns spanning 5/8, 7/8, 8/8, 9/8, 10/8, 11/8, 12/8, 4/4.
// Stress-tests the engine across meters. More patterns arrive as we grow the library.

import type { Pattern } from './types';

export const PATTERNS: Pattern[] = [
  {
    id: 'karsilama',
    name: 'Karşılama',
    origin: 'Turkey · Thrace',
    tradition: 'Wedding dance',
    timeSig: '9/8',
    grouping: [2, 2, 2, 3],
    stepUnit: 8,
    steps: 9,
    bpm: { default: 276, min: 200, max: 360 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 2, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 1, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 1],
    },
    story:
      'Karşılama means "face to face" — the dance has two rows of dancers greeting each other. The 2+2+2+3 grouping gives the whole thing its iconic skip.',
  },
  {
    id: 'horon',
    name: 'Horon',
    origin: 'Turkey · Black Sea',
    tradition: 'Coastal line dance',
    timeSig: '7/8',
    grouping: [2, 2, 3],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 360, min: 280, max: 460 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 0, 1, 1],
      HH: [2, 2, 2, 2, 2, 2, 2],
    },
    story: 'Horon is the fisherman shaking on a trawler deck. Played at Mach speed on kemençe and davul.',
  },
  {
    id: 'turk-aksagi',
    name: 'Türk Aksağı',
    origin: 'Turkey',
    tradition: 'Ottoman / folk',
    timeSig: '5/8',
    grouping: [2, 3],
    stepUnit: 8,
    steps: 5,
    bpm: { default: 260, min: 200, max: 340 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 1],
      HH: [2, 1, 2, 1, 1],
    },
    story: 'The Turkish limp in 5 — two then three, forever rolling forward.',
  },
  {
    id: 'curcuna',
    name: 'Curcuna',
    origin: 'Turkey',
    tradition: 'Ottoman classical',
    timeSig: '10/8',
    grouping: [2, 3, 2, 3],
    stepUnit: 8,
    steps: 10,
    bpm: { default: 200, min: 140, max: 260 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 0, 2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 1, 0, 1, 0, 1, 1],
      HH: [2, 1, 2, 1, 1, 2, 1, 2, 1, 1],
    },
    story: 'Two Türk Aksağıs stacked — 2+3+2+3. The archetypal Ottoman asymmetric.',
  },
  {
    id: 'duyek',
    name: 'Düyek',
    origin: 'Turkey',
    tradition: 'Ottoman folk',
    timeSig: '8/8',
    grouping: [4, 4],
    stepUnit: 8,
    steps: 8,
    bpm: { default: 220, min: 140, max: 280 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0],
      HH: [1, 1, 1, 1, 1, 1, 1, 1],
    },
    story: 'The first rhythm every darbuka student learns. A foundation stone of Ottoman music.',
  },
  {
    id: 'ruchenitsa',
    name: 'Rŭchenitsa',
    origin: 'Bulgaria',
    tradition: 'Folk dance',
    timeSig: '7/8',
    grouping: [2, 2, 3],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 320, min: 240, max: 420 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0],
      SN: [0, 0, 0, 0, 0, 1, 1],
      HH: [2, 1, 2, 1, 2, 1, 1],
    },
    story: "Bulgaria's most danced rhythm — \"quick-quick-sloooow\" is how kids learn it.",
  },
  {
    id: 'kopanitsa',
    name: 'Kopanitsa',
    origin: 'Bulgaria · Shope',
    tradition: 'Folk dance',
    timeSig: '11/8',
    grouping: [2, 2, 3, 2, 2],
    stepUnit: 8,
    steps: 11,
    bpm: { default: 400, min: 320, max: 520 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0],
      SN: [0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    story: '11/8 stomping through a tavern. The long beat is in the middle here.',
  },
  {
    id: 'daichovo',
    name: 'Daichovo',
    origin: 'Bulgaria',
    tradition: 'Folk dance',
    timeSig: '9/8',
    grouping: [2, 2, 2, 3],
    stepUnit: 8,
    steps: 9,
    bpm: { default: 340, min: 280, max: 440 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 0, 1, 0, 1, 1],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    story: 'Same 2+2+2+3 skeleton as Karşılama but faster, bouncier, pan-flute territory.',
  },
  {
    id: 'son-clave',
    name: 'Son Clave 3-2',
    origin: 'Cuba',
    tradition: 'Afro-Cuban',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 380, min: 280, max: 800 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1],
    },
    story: 'The spine of every Cuban son, salsa, and half of Latin music since 1800.',
  },
  {
    id: 'bembe',
    name: 'Bembé',
    origin: 'Cuba · Yoruba diaspora',
    tradition: 'Sacred bell pattern',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 230, min: 180, max: 300 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 2, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    story: 'The 12/8 bell that underlies bembé, abakuá, and half the West African diaspora.',
  },
];

export function patternById(id: string): Pattern | undefined {
  return PATTERNS.find((p) => p.id === id);
}
