// BeatForge — curated pattern library (30 world rhythms)
// Grid encoding: each pattern has `steps` (total step count), `grouping`
// (beat-group breakdown summing to steps/stepsPerBeat-equivalent), and
// tracks keyed by KK/SN/HH with 0 (off) / 1 (weak) / 2 (strong) per step.
// For polyrhythm tracks we allow an override `cycle` (steps) that may
// differ from the master step count — the engine walks each track on its
// own cursor and takes LCM for the super-cycle.

// stepUnit: 8 means each step = 1 eighth; 16 means 1 sixteenth. Grouping
// is expressed in steps (not beats). For 9/8 as 2+2+2+3, stepUnit=8,
// steps=9, grouping=[2,2,2,3]. For 4/4 as 4+4+4+4 sixteenths,
// stepUnit=16, steps=16, grouping=[4,4,4,4].

export const PATTERNS = [
  // ── TURKISH / ANATOLIAN ───────────────────────────────────────────────
  {
    id: 'karsilama',
    name: 'Karşılama',
    origin: 'Turkey · Thrace',
    tradition: 'Wedding dance',
    timeSig: '9/8',
    grouping: [2, 2, 2, 3],
    stepUnit: 8,
    steps: 9,
    bpm: { default: 276, min: 200, max: 360 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 2, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 1, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 1],
    },
    story: 'Karşılama means "face to face" — the dance has two rows of dancers greeting each other. The 2+2+2+3 grouping gives the whole thing its iconic skip.',
  },
  {
    id: 'roman-havasi',
    name: 'Roman Havası',
    origin: 'Turkey · Edirne',
    tradition: 'Romani wedding',
    timeSig: '9/8',
    grouping: [2, 2, 2, 3],
    stepUnit: 8,
    steps: 9,
    bpm: { default: 300, min: 240, max: 400 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 0, 1, 0, 1, 1],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    story: 'The Thracian Romani groove — clarinet-led, hot, aggressive. Where Karşılama skips, this sprints.',
  },
  {
    id: 'aksak',
    name: 'Aksak',
    origin: 'Turkey · Anatolia',
    tradition: 'Ottoman classical',
    timeSig: '9/8',
    grouping: [2, 2, 2, 3],
    stepUnit: 8,
    steps: 9,
    bpm: { default: 236, min: 160, max: 300 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 2, 0, 0],
      SN: [0, 0, 1, 0, 0, 1, 0, 1, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 1],
    },
    story: '"Aksak" literally means "limping" — the uneven gait is the point, not a bug.',
  },
  {
    id: 'zeybek',
    name: 'Zeybek',
    origin: 'Turkey · Aegean',
    tradition: 'Mountain dance',
    timeSig: '9/8',
    grouping: [2, 2, 2, 3],
    stepUnit: 8,
    steps: 9,
    bpm: { default: 124, min: 80, max: 180 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 0],
      SN: [0, 0, 1, 0, 0, 0, 1, 0, 1],
      HH: [2, 0, 1, 0, 2, 0, 1, 0, 1],
    },
    story: 'Slow, weighty, sung by bandits. Each beat is a step in a warrior\'s walk.',
  },
  {
    id: 'horon',
    name: 'Horon',
    origin: 'Turkey · Black Sea',
    tradition: 'Coastal line dance',
    timeSig: '7/8',
    grouping: [2, 2, 3],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 360, min: 280, max: 460 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 0, 1, 1],
      HH: [2, 2, 2, 2, 2, 2, 2],
    },
    story: 'Horon is the fisherman shaking on a trawler deck. Played at Mach speed on kemençe and davul.',
  },
  {
    id: 'devr-i-hindi',
    name: 'Devr-i Hindi',
    origin: 'Turkey',
    tradition: 'Ottoman classical',
    timeSig: '7/8',
    grouping: [3, 2, 2],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 216, min: 160, max: 280 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0],
      SN: [0, 1, 1, 0, 1, 0, 1],
      HH: [2, 1, 1, 2, 1, 2, 1],
    },
    story: 'A stately court rhythm. The 3 comes first here — heavier, more formal than Horon.',
  },
  {
    id: 'turk-aksagi',
    name: 'Türk Aksağı',
    origin: 'Turkey',
    tradition: 'Ottoman / folk',
    timeSig: '5/8',
    grouping: [2, 3],
    stepUnit: 8,
    steps: 5,
    bpm: { default: 260, min: 200, max: 340 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 1],
      HH: [2, 1, 2, 1, 1],
    },
    story: 'The Turkish limp in 5 — two then three, forever rolling forward.',
  },
  {
    id: 'curcuna',
    name: 'Curcuna',
    origin: 'Turkey',
    tradition: 'Ottoman classical',
    timeSig: '10/8',
    grouping: [2, 3, 2, 3],
    stepUnit: 8,
    steps: 10,
    bpm: { default: 200, min: 140, max: 260 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 0, 2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 1, 0, 1, 0, 1, 1],
      HH: [2, 1, 2, 1, 1, 2, 1, 2, 1, 1],
    },
    story: 'Two Türk Aksağıs stacked — 2+3+2+3. The archetypal Ottoman asymmetric.',
  },
  {
    id: 'duyek',
    name: 'Düyek',
    origin: 'Turkey',
    tradition: 'Ottoman folk',
    timeSig: '8/8',
    grouping: [4, 4],
    stepUnit: 8,
    steps: 8,
    bpm: { default: 220, min: 140, max: 280 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 2, 0, 0, 0, 2, 0],
      HH: [1, 1, 1, 1, 1, 1, 1, 1],
    },
    story: 'The first rhythm every darbuka student learns. A foundation stone of Ottoman music.',
  },

  // ── BALKAN ────────────────────────────────────────────────────────────
  {
    id: 'ruchenitsa',
    name: 'Rŭchenitsa',
    origin: 'Bulgaria',
    tradition: 'Folk dance',
    timeSig: '7/8',
    grouping: [2, 2, 3],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 320, min: 240, max: 420 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0],
      SN: [0, 0, 0, 0, 0, 1, 1],
      HH: [2, 1, 2, 1, 2, 1, 1],
    },
    story: 'Bulgaria\'s most danced rhythm — "quick-quick-sloooow" is how kids learn it.',
  },
  {
    id: 'kopanitsa',
    name: 'Kopanitsa',
    origin: 'Bulgaria · Shope',
    tradition: 'Folk dance',
    timeSig: '11/8',
    grouping: [2, 2, 3, 2, 2],
    stepUnit: 8,
    steps: 11,
    bpm: { default: 400, min: 320, max: 520 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 0, 2, 0, 2, 0],
      SN: [0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    story: '11/8 stomping through a tavern. The long beat is in the middle here.',
  },
  {
    id: 'kalamatianos',
    name: 'Kalamatianós',
    origin: 'Greece · Peloponnese',
    tradition: 'Circle dance',
    timeSig: '7/8',
    grouping: [3, 2, 2],
    stepUnit: 8,
    steps: 7,
    bpm: { default: 270, min: 220, max: 340 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 2, 0],
      SN: [0, 0, 1, 0, 1, 0, 1],
      HH: [2, 1, 1, 2, 1, 2, 1],
    },
    story: 'The Greek national circle dance. Long-short-short, everyone holding hands.',
  },
  {
    id: 'daichovo',
    name: 'Daichovo',
    origin: 'Bulgaria',
    tradition: 'Folk dance',
    timeSig: '9/8',
    grouping: [2, 2, 2, 3],
    stepUnit: 8,
    steps: 9,
    bpm: { default: 340, min: 280, max: 440 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 2, 0, 2, 0, 2, 0, 0],
      SN: [0, 1, 0, 1, 0, 1, 0, 1, 1],
      HH: [2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    story: 'Same 2+2+2+3 skeleton as Karşılama but faster, bouncier, pan-flute territory.',
  },

  // ── AFRO-CUBAN / CARIBBEAN / LATIN ────────────────────────────────────
  {
    id: 'son-clave',
    name: 'Son Clave 3-2',
    origin: 'Cuba',
    tradition: 'Afro-Cuban',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 380, min: 280, max: 800 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1],
    },
    story: 'The spine of every Cuban son, salsa, and half of Latin music since 1800.',
  },
  {
    id: 'rumba-clave',
    name: 'Rumba Clave 3-2',
    origin: 'Cuba',
    tradition: 'Afro-Cuban rumba',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 400, min: 320, max: 560 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1],
    },
    story: 'Rumba\'s clave — the three-side has its last stroke one 16th late vs. son. That shift is everything.',
  },
  {
    id: 'bembe',
    name: 'Bembé',
    origin: 'Cuba · Yoruba diaspora',
    tradition: 'Sacred bell pattern',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 230, min: 180, max: 300 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0],
      SN: [0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 2, 0],
      HH: [2, 0, 1, 2, 1, 2, 0, 1, 2, 1, 2, 1],
    },
    story: 'The "standard pattern" of the African diaspora — shows up from Havana to Salvador to New Orleans.',
  },
  {
    id: 'cascara',
    name: 'Cáscara',
    origin: 'Cuba',
    tradition: 'Timbale shell pattern',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 480, min: 360, max: 800 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 1, 2],
    },
    story: 'Play on the side of a timbal. Slinky, sideways, made for mambo verses.',
  },
  {
    id: 'tresillo',
    name: 'Tresillo',
    origin: 'Pan-Caribbean',
    tradition: 'Foundational figure',
    timeSig: '4/4',
    grouping: [3, 3, 2],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 392, min: 240, max: 720 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 2, 0],
      SN: [0, 0, 1, 0, 0, 1, 0, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1],
    },
    story: 'Three-three-two. The single most globally exported African rhythmic cell. In 4/4 displayed as 3+3+2 eighths.',
  },

  // ── WEST AFRICAN ──────────────────────────────────────────────────────
  {
    id: 'agbekor',
    name: 'Agbekor',
    origin: 'Ghana · Ewe',
    tradition: 'War dance',
    timeSig: '12/8',
    grouping: [3, 3, 3, 3],
    stepUnit: 8,
    steps: 12,
    bpm: { default: 230, min: 190, max: 280 },
    difficulty: 'advanced',
    tracks: {
      KK: [2, 0, 0, 2, 0, 0, 0, 2, 0, 2, 0, 0],
      SN: [0, 0, 1, 0, 1, 2, 0, 0, 2, 0, 1, 0],
      HH: [2, 0, 1, 2, 1, 2, 0, 1, 2, 1, 2, 0],
    },
    story: 'Ewe war dance from Ghana. The gankogui bell carries the 12/8 time-line; the rest interlocks.',
  },
  {
    id: 'kpanlogo',
    name: 'Kpanlogo',
    origin: 'Ghana · Ga',
    tradition: 'Social dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 460, min: 380, max: 540 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [2, 0, 1, 1, 2, 0, 1, 1, 2, 0, 1, 1, 2, 0, 1, 1],
    },
    story: 'Youth-music of 1960s Accra — a conga-based social dance that became Ghana\'s national rhythm.',
  },

  // ── INDIAN ────────────────────────────────────────────────────────────
  {
    id: 'rupak',
    name: 'Rupak Tal',
    origin: 'India · Hindustani',
    tradition: 'Tabla cycle',
    timeSig: '7/4',
    grouping: [3, 2, 2],
    stepUnit: 4,
    steps: 7,
    bpm: { default: 90, min: 60, max: 130 },
    difficulty: 'intermediate',
    tracks: {
      KK: [0, 0, 0, 2, 0, 2, 0],
      SN: [2, 1, 1, 0, 0, 0, 0],
      HH: [1, 1, 1, 2, 1, 2, 1],
    },
    story: 'Rupak is unusual — the first beat (sam) is actually a *khali* (empty) stroke. The cycle starts weak.',
  },
  {
    id: 'jhaptal',
    name: 'Jhaptal',
    origin: 'India · Hindustani',
    tradition: 'Tabla cycle',
    timeSig: '10/4',
    grouping: [2, 3, 2, 3],
    stepUnit: 4,
    steps: 10,
    bpm: { default: 96, min: 60, max: 140 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 2, 0, 2, 0, 0, 2, 0],
      SN: [0, 1, 0, 0, 1, 0, 1, 0, 0, 1],
      HH: [2, 1, 1, 2, 1, 2, 1, 1, 2, 1],
    },
    story: 'The 10-beat cycle — 2+3+2+3. Same skeleton as Curcuna; different tradition.',
  },
  {
    id: 'tintal',
    name: 'Tintal',
    origin: 'India · Hindustani',
    tradition: 'Tabla cycle',
    timeSig: '16/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 8,
    steps: 16,
    bpm: { default: 180, min: 120, max: 400 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 1, 0, 0, 0, 1, 0, 2, 0, 1, 0, 0, 0, 1, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1],
    },
    story: '16 beats, four vibhags. The most common tabla cycle — and a conveniently familiar 4/4 when you squint.',
  },

  // ── MIDDLE EASTERN ────────────────────────────────────────────────────
  {
    id: 'maqsoum',
    name: 'Maqsoum',
    origin: 'Egypt',
    tradition: 'Pan-Arab pop',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 460, min: 360, max: 600 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 1, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    story: 'Dum-tek-tek, dum-tek. If you\'ve heard any Arabic pop song, you\'ve heard this.',
  },
  {
    id: 'baladi',
    name: 'Baladi',
    origin: 'Egypt',
    tradition: 'Folk / belly dance',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 380, min: 300, max: 480 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      SN: [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 1, 0],
      HH: [2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1],
    },
    story: '"Baladi" = "of the country." Heavier and slower than Maqsoum — two doums up front.',
  },
  {
    id: 'malfuf',
    name: 'Malfuf',
    origin: 'Pan-Arab',
    tradition: 'Dance / procession',
    timeSig: '2/4',
    grouping: [4, 4],
    stepUnit: 16,
    steps: 8,
    bpm: { default: 560, min: 400, max: 800 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 2, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 1],
      HH: [2, 1, 2, 1, 2, 1, 2, 1],
    },
    story: 'Zippy dance rhythm — "malfuf" means "wrapped," referring to how the beats wrap tight.',
  },

  // ── POLYRHYTHM DEMOS ──────────────────────────────────────────────────
  // These override track `cycle` so each track walks its own length.
  {
    id: 'poly-3-4',
    name: '3 over 4',
    origin: 'Cross-cultural',
    tradition: 'Polyrhythm primer',
    timeSig: '—',
    grouping: [4, 4, 4, 4], // master display = 16 steps
    stepUnit: 16,
    steps: 16,
    bpm: { default: 440, min: 280, max: 640 },
    difficulty: 'intermediate',
    poly: true,
    tracks: {
      // KK hits every 4 steps (1 per beat). SN hits every 16/3 steps (3 hits spread over 16). HH keeps straight eighths.
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: { cycle: 3, pattern: [2, 1, 1] },
      HH: [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
    },
    story: 'Two cursors, different lengths, same tempo. Feel how they line up every 12 beats and reset.',
  },
  {
    id: 'poly-5-4',
    name: '5 over 4',
    origin: 'Cross-cultural',
    tradition: 'Polyrhythm',
    timeSig: '—',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 20, // LCM of 4 and 5 in sixteenth-note terms
    bpm: { default: 400, min: 240, max: 560 },
    difficulty: 'advanced',
    poly: true,
    tracks: {
      KK: { cycle: 4, pattern: [2, 0, 0, 0] }, // beat
      SN: { cycle: 5, pattern: [2, 1, 0, 1, 0] },
      HH: [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
    },
    story: 'Five across four. Super-cycle is 20 sixteenths. Try humming "every good boy does fine" against a 4/4 pulse.',
  },
  {
    id: 'poly-7-4',
    name: '7 over 4',
    origin: 'Cross-cultural',
    tradition: 'Polyrhythm',
    timeSig: '—',
    grouping: [4, 4, 4, 4, 4, 4, 4],
    stepUnit: 16,
    steps: 28,
    bpm: { default: 368, min: 240, max: 520 },
    difficulty: 'advanced',
    poly: true,
    tracks: {
      KK: { cycle: 4, pattern: [2, 0, 0, 0] },
      SN: { cycle: 7, pattern: [2, 0, 1, 0, 1, 1, 0] },
      HH: { cycle: 2, pattern: [1, 0] },
    },
    story: 'Seven across four. Rare air — you hear it in prog, Carnatic konnakol, some Balkan brass.',
  },

  // ── ELECTRONIC ────────────────────────────────────────────────────────
  {
    id: 'four-on-floor',
    name: 'Four on the Floor',
    origin: 'Detroit → everywhere',
    tradition: 'House / techno',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 496, min: 440, max: 560 },
    difficulty: 'beginner',
    tracks: {
      KK: [2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
      SN: [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
      HH: [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
    },
    story: 'Every TR-909 house record ever. The metronome-to-club pipeline.',
  },
  {
    id: 'amapiano',
    name: 'Amapiano',
    origin: 'South Africa',
    tradition: 'Township house',
    timeSig: '4/4',
    grouping: [4, 4, 4, 4],
    stepUnit: 16,
    steps: 16,
    bpm: { default: 448, min: 400, max: 472 },
    difficulty: 'intermediate',
    tracks: {
      KK: [2, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0],
      SN: [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
      HH: [2, 0, 1, 0, 2, 0, 1, 0, 2, 0, 1, 0, 2, 0, 1, 0],
    },
    story: 'The log-drum dances; the kick breathes. Amapiano lets the groove sit way back.',
  },
];

export function patternById(id) {
  return PATTERNS.find((p) => p.id === id) || PATTERNS[0];
}
